const HOME='3G7X+FJ2, Gaurav Path, Shastrinagar, Naranpura, Ahmedabad, Gujarat 380063';
const HOTEL='Hotel Landmark, College Road, Opp. COCO Petrol Pump, Banswara, Rajasthan 327001';
const KEY='riderhub_v6';
const HISTORY_KEY='riderhub_v6_undo';
const DB='riderhub_private_docs';

const days=[
{day:1,date:'2026-08-28',title:'Ahmedabad → Banswara',from:'Ahmedabad',to:'Banswara',end:'21:30',segments:[
 {label:'Part 1 · Home → Balasinor',origin:HOME,destination:'Balasinor, Gujarat',waypoints:['Odhav Circle, Ahmedabad','BPCL R B Patel Sons, Kuha, Gujarat','Haldharvas Chokdi, Gujarat','Ladvel Chokdi, Gujarat']},
 {label:'Part 2 · Balasinor → Mangarh',origin:'Balasinor, Gujarat',destination:'Mangarh Dham, Anandpuri, Rajasthan',waypoints:['Lunawada, Gujarat','Santrampur, Gujarat','Khedapada, Santrampur, Mahisagar, Gujarat']},
 {label:'Part 3 · Mangarh → Hotel',origin:'Mangarh Dham, Anandpuri, Rajasthan',destination:HOTEL,waypoints:['Anandpuri Bus Stand, Rajasthan','New Bus Stand, Banswara, Rajasthan']}],backup:[
 {label:'Backup 1 · Home → Godhra',origin:HOME,destination:'Godhra Bypass, Gujarat',waypoints:['Odhav Circle, Ahmedabad','BPCL R B Patel Sons, Kuha, Gujarat','Haldharvas Chokdi, Gujarat','Ladvel Chokdi, Gujarat','Vavadi Khurd Toll Plaza, Gujarat']},
 {label:'Backup 2 · Godhra → Jhalod',origin:'Godhra Bypass, Gujarat',destination:'Jhalod, Gujarat',waypoints:['Bhatwada Toll Plaza, Gujarat','Limkheda Bypass, Gujarat','Dahod Bypass, Gujarat']},
 {label:'Backup 3 · Jhalod → Hotel',origin:'Jhalod, Gujarat',destination:HOTEL,waypoints:[]}],tasks:[['04:15','Wake / light food','Final tyre, chain, brakes, rain gear, straps and documents.'],['05:00','Leave Home','Start before traffic builds.'],['07:00','Breakfast + break','20–30 min, water and stretch.'],['09:15','Mangarh Dham','Quiet morning target.'],['12:00','Hotel check-in','Lunch and remove wet gear.'],['12:30','Rest','Recovery + charge electronics.'],['15:15','Anand Sagar + Kalpavriksha','Short quiet stop.'],['16:15','Kagdi Pick Up Weir','Leave if crowded.'],['17:10','Dialab Lake · optional','Only if both riders are fresh.'],['18:30','Dinner','Simple meal.'],['20:00','Fuel + prep','Fill bike and prep Saturday bag.'],['21:15','Sleep','Saturday starts early.']]},
{day:2,date:'2026-08-29',title:'Banswara Adventure Loop',from:'Banswara',to:'Banswara',end:'21:15',segments:[
 {label:'Part 1 · Hotel → Chacha Kota → Mahi',origin:HOTEL,destination:'Mahi Bajaj Sagar Dam, Banswara, Rajasthan',waypoints:['Chacha Kota, Banswara, Rajasthan']},
 {label:'Part 2 · Mahi → Singhpura → Hotel',origin:'Mahi Bajaj Sagar Dam, Banswara, Rajasthan',destination:HOTEL,waypoints:['Ghatol, Rajasthan','Singhpura, Ghatol, Banswara, Rajasthan','Singhpura Falls, Rajasthan']}],tasks:[['04:45','Wake','Tea / banana / biscuits.'],['05:10','Leave hotel','Be rolling before normal visitors.'],['05:35','Chacha Kota','Normal access + safe firm dirt/grass only.'],['07:00','Mahi Dam','Visitor road only; obey barricades.'],['08:00','Breakfast','Proper breakfast + short rest.'],['09:00','Leave for Singhpura','Navigate to Singhpura/Ghatol first.'],['09:45','Singhpura Falls','Park, walk; do not ride through pedestrian water crossing.'],['13:15','Back Banswara','Lunch.'],['14:15','Rest','Dry boots/socks/rain gear.'],['18:00','Flexible evening','Nothing compulsory.'],['21:15','Sleep','Sunday starts early.']]},
{day:3,date:'2026-08-30',title:'Banswara → Ahmedabad',from:'Banswara',to:'Ahmedabad',end:'18:00',segments:[
 {label:'Part 1 · Hotel → Jagmer → Hotel',origin:HOTEL,destination:HOTEL,waypoints:['Jagmer Hills, Banswara, Rajasthan']},
 {label:'Part 2 · Hotel → Lunawada via Arthuna',origin:HOTEL,destination:'Lunawada, Gujarat',waypoints:['Arthuna Group of Temples, Rajasthan','Khedapada, Santrampur, Mahisagar, Gujarat','Santrampur Bus Station, Gujarat']},
 {label:'Part 3 · Lunawada → Home',origin:'Lunawada, Gujarat',destination:HOME,waypoints:['Balasinor, Gujarat','Ladvel Chokdi, Gujarat','BPCL R B Patel Sons, Kuha, Gujarat','Odhav Circle, Ahmedabad']}],tasks:[['04:45','Wake + pack','Keep only a light Jagmer bag if hotel can hold luggage.'],['05:10','Leave hotel','Light bike for dirt riding.'],['05:30','Jagmer / Jagmeru','Paved approach → firm red dirt/grass; rough parts solo only.'],['07:15','Return hotel','Collect luggage.'],['07:30','Breakfast + checkout','Final tyre, chain and luggage check.'],['08:15','Leave for Arthuna','Normal public road.'],['09:15','Arthuna','Explore archaeological complex properly.'],['10:45','Leave for Ahmedabad','No more sightseeing.'],['12:30','Lunch + rest','30–45 min.'],['16:30','Ahmedabad target','Rain/traffic buffer until 18:00.']]}
];

const DEFAULT_GEAR=[
{id:'g_ls2_helmet',name:'LS2 FF800 Storm II Helmet',category:'Riding Gear',owner:'Jayrut',status:'owned',amount:11300,qty:1,note:'Bought.'},
{id:'g_solace_jacket',name:'Solace Furious V4.0 Touring Jacket',category:'Riding Gear',owner:'Jayrut',status:'owned',amount:16899,qty:1,note:'Bought.'},
{id:'g_smk_mom',name:'SMK Typhoon Helmet',category:'Riding Gear',owner:'Mom',status:'owned',amount:5650,qty:1,note:'Replacement order; price remains editable if item-only amount differs.'},
{id:'g_tarmac_mom',name:'Tarmac Drifter II Level 2 Jacket',category:'Riding Gear',owner:'Mom',status:'owned',amount:6699,qty:1,note:'₹6,499 item + ₹200 shipping.'},
{id:'g_grid_mk3',name:'ViaTerra Grid MK3 Gloves',category:'Riding Gear',owner:'Jayrut',status:'planned',amount:7000,qty:1,note:'Planned.'},
{id:'g_coolpro',name:'Solace Coolpro Sus V4T Mesh Pants',category:'Riding Gear',owner:'Jayrut',status:'planned',amount:11500,qty:1,note:'Planned.'},
{id:'g_xt_evo',name:'Solace XT Evo Pro Boots',category:'Riding Gear',owner:'Jayrut',status:'planned',amount:null,qty:1,note:'Planned.'},
{id:'g_rain_gloves',name:'Solace V2.0 Rain Over Gloves',category:'Riding Gear',owner:'Jayrut',status:'planned',amount:1350,qty:1,note:'Planned.'},
{id:'g_holeshot_mom',name:'ViaTerra Holeshot Short Gloves',category:'Riding Gear',owner:'Mom',status:'planned',amount:3500,qty:1,note:'Planned.'},
{id:'g_miller_mom',name:"ViaTerra Miller Women's Mesh Pants",category:'Riding Gear',owner:'Mom',status:'planned',amount:8000,qty:1,note:'Planned.'},
{id:'g_raida_mom',name:'Raida Tourer Boots',category:'Riding Gear',owner:'Mom',status:'planned',amount:4250,qty:1,note:'Planned.'},
{id:'g_balaclava',name:'LS2 Lycra Balaclava',category:'Riding Gear',owner:'Jayrut',status:'owned',amount:null,qty:1,note:'Quantity 1.'},
{id:'g_water_bladd',name:'Solace Water Bladder',category:'Luggage',owner:'Jayrut',status:'planned',amount:1750,qty:1,note:'Planned.'},
{id:'g_leh70',name:'ViaTerra LEH 70L Saddlebags',category:'Luggage',owner:'Bike / Shared',status:'owned',amount:null,qty:1,note:'Bought.'},
{id:'g_rynox_tank',name:'Rynox Optimus 3 Tank Bag 21L',category:'Luggage',owner:'Bike / Shared',status:'owned',amount:3900,qty:1,note:'Bought.'},
{id:'g_saddle_stay',name:'MotoCare Saddle Stay',category:'Luggage',owner:'Bike / Shared',status:'owned',amount:null,qty:1,note:'Bought; combined MotoCare order with rack/backrest ₹6,320.'},
{id:'g_rack_backrest',name:'MotoCare Rear Rack + Backrest / Pipe Carrier',category:'Luggage',owner:'Bike / Shared',status:'owned',amount:null,qty:1,note:'Bought; combined MotoCare order with saddle stay ₹6,320.'},
{id:'g_ejeas',name:'EJEAS Q8 Mesh Intercom',category:'Electronics',owner:'Bike / Shared',status:'owned',amount:10998,qty:2,note:'2 units.'},
{id:'g_aoocci',name:'Aoocci C3 Pro 5" Smart Screen',category:'Electronics',owner:'Bike / Shared',status:'owned',amount:8882.09,qty:1,note:'Actual debit.'},
{id:'g_vayu',name:'Portronics Vayu 5.0 Tyre Inflator',category:'Electronics',owner:'Bike / Shared',status:'owned',amount:2289.10,qty:1,note:'Portronics only.'},
{id:'g_windshield',name:'MotoCare Windshield',category:'Bike Accessories',owner:'Bike / Shared',status:'owned',amount:2240,qty:1,note:'Bought.'},
{id:'g_knuckle',name:'Sarkart Knuckle Guards',category:'Bike Accessories',owner:'Bike / Shared',status:'owned',amount:null,qty:1,note:'Bought.'},
{id:'g_crash',name:'Moto Torque Crash Guard',category:'Bike Accessories',owner:'Bike / Shared',status:'owned',amount:4700,qty:1,note:'Bought.'},
{id:'g_headlight',name:'Moto Torque Headlight Guard',category:'Bike Accessories',owner:'Bike / Shared',status:'owned',amount:1300,qty:1,note:'Bought.'},
{id:'g_radiator',name:'Moto Torque Radiator Guard',category:'Bike Accessories',owner:'Bike / Shared',status:'owned',amount:700,qty:1,note:'Bought.'},
{id:'g_side',name:'Moto Torque Side Stand Extender',category:'Bike Accessories',owner:'Bike / Shared',status:'owned',amount:450,qty:1,note:'Bought.'},
{id:'g_caliper',name:'TVS Caliper Guard',category:'Bike Accessories',owner:'Bike / Shared',status:'owned',amount:509,qty:1,note:'Bought.'},
{id:'g_tankgrip',name:'TVS Tank Grip',category:'Bike Accessories',owner:'Bike / Shared',status:'owned',amount:783,qty:1,note:'Bought.'},
{id:'g_fork',name:'Fork Cover',category:'Bike Accessories',owner:'Bike / Shared',status:'owned',amount:378,qty:1,note:'Bought.'},
{id:'g_chin',name:'MotoVibe LS2 FF800 Chin Mount',category:'Camera & Mounts',owner:'Jayrut',status:'owned',amount:null,qty:1,note:'Bought.'},
{id:'g_lensmount',name:'MotoVibe DJI Action Lens-Centre POV Mount',category:'Camera & Mounts',owner:'Jayrut',status:'owned',amount:null,qty:1,note:'Bought; MotoVibe order total ₹1,298.'},
{id:'g_motul_chain',name:'Motul Chain Lube + Cleaner',category:'Cleaning & Care',owner:'Bike / Shared',status:'owned',amount:426,qty:1,note:'Bought.'},
{id:'g_chainbrush',name:'Chain Brush',category:'Cleaning & Care',owner:'Bike / Shared',status:'owned',amount:110,qty:1,note:'Bought.'},
{id:'g_wavex',name:'WaveX Matte Shampoo / Cleaner',category:'Cleaning & Care',owner:'Bike / Shared',status:'owned',amount:625,qty:1,note:'Bought.'},
{id:'g_wd40',name:'WD-40',category:'Cleaning & Care',owner:'Bike / Shared',status:'owned',amount:497,qty:1,note:'Bought.'},
{id:'g_trim',name:'Turtle Wax Trim Restorer',category:'Cleaning & Care',owner:'Bike / Shared',status:'owned',amount:729,qty:1,note:'Bought.'},
{id:'g_tireshine',name:'Sheeba Tyre Shine',category:'Cleaning & Care',owner:'Bike / Shared',status:'owned',amount:160,qty:1,note:'Bought.'},
{id:'g_pads',name:'WaveX Applicator Pads',category:'Cleaning & Care',owner:'Bike / Shared',status:'owned',amount:296,qty:1,note:'Bought.'},
{id:'g_microfiber',name:'Microfiber Set',category:'Cleaning & Care',owner:'Bike / Shared',status:'owned',amount:399,qty:1,note:'Bought.'},
{id:'g_brushset',name:'Detailing Brush Set',category:'Cleaning & Care',owner:'Bike / Shared',status:'owned',amount:310,qty:1,note:'Bought.'},
{id:'g_washer',name:'Cordless Pressure Washer',category:'Cleaning & Care',owner:'Bike / Shared',status:'owned',amount:1685,qty:1,note:'Bought.'},
{id:'g_cover',name:'Neodrift Bike Cover',category:'Bike Accessories',owner:'Bike / Shared',status:'owned',amount:999,qty:1,note:'Bought.'},
{id:'g_screen',name:'Screen Guard',category:'Bike Accessories',owner:'Bike / Shared',status:'owned',amount:199,qty:1,note:'Bought.'}
];

const DOCS=[
{id:'vehicle_invoice',name:'Vehicle invoice',summary:'10 Jun 2026 · ₹150,340',detail:'Dealer vehicle invoice. Sensitive identifiers are hidden by default.'},
{id:'vehicle_tax',name:'Lifetime vehicle tax',summary:'₹1,693',detail:'Municipal lifetime vehicle tax record.'},
{id:'insurance',name:'ICICI Lombard insurance',summary:'OD to 04 Jun 2027 · TP to 04 Jun 2031',detail:'Bundled policy · Zero Dep + RTI. Sensitive policy identifiers remain masked.'},
{id:'licence',name:'Learner licence',summary:'02 Jun–01 Dec 2026',detail:'Learner licence validity summary. Licence number remains masked.'},
{id:'service_invoice',name:'First service invoice',summary:'19 Jun 2026 · 767 km · ₹1,000',detail:'1st Free Service · oil + filter · 767 km.'},
{id:'hotelBooking',name:'Hotel Landmark booking',summary:'28–30 Aug 2026 · ₹2,470 paid',detail:'2 nights · Deluxe Room · 2 adults · Room Only.'}
];

const base={bike:{name:'TVS Ronin',manufacturer:'TVS',model:'Ronin',trim:'Mid • Charcoal Ember • 2026',variant:'Mid',colour:'Charcoal Ember',year:2026,odo:3200,purchase:'Jun 2026',firstService:{odo:767,date:'19 Jun 2026',cost:1000},nextServiceKm:5500,nextServiceDate:'07 Dec 2026',chainLast:3000,braking:'Dual-Channel ABS',engine:'225.9 cc single-cylinder',fuelTank:'14 L',transmission:'5-speed',tyres:'Tubeless',insurance:'ICICI Lombard bundled policy',serviceHistory:[{name:'1st Free Service',date:'19 Jun 2026',odo:767,cost:1000,work:'Engine oil + oil filter'}]},ride:{selectedDay:0,budgetMax:7170,expenses:{hotel:2470,fuel:0,food:0,parking:0,misc:0},fuelLogs:[],notes:'',issues:[],packing:{rain:false,firstaid:false,puncture:false,tools:false,power:false,documents:false,water:false,socks:false},content:{departure:false,mangarh:false,chacha:false,mahi:false,singhpura:false,jagmer:false,arthuna:false,arrival:false},backup:{action5:false,phone:false,photos:false,booking:false},preflight:{},tasks:{},customEmergency:['','',''],weather:null,weatherUpdated:null},gear:DEFAULT_GEAR,ui:{page:'home'}};

let state=load();let undoStack=loadUndo();let modalWindowScroll=0;let modalRideScroll=0;let draftExpenses=null;let timerHandle=null;let gearStatusFilter='all';let gearOwnerFilter='all';let gearQuery='';let selectedGearId=null;let trafficMap=null;let trafficLayer=null;let mapsLoader=null;
function $(s){return document.querySelector(s)}function $$(s){return[...document.querySelectorAll(s)]}function clone(x){return JSON.parse(JSON.stringify(x))}function money(n){return n==null||n===''?'—':'₹'+Math.round(Number(n)||0).toLocaleString('en-IN')}function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function merge(a,b){for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])&&a[k]&&typeof a[k]==='object'&&!Array.isArray(a[k]))merge(a[k],b[k]);else a[k]=b[k]}return a}
function normal(s=''){return s.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function restoreGear(g){const existing=Array.isArray(g)?g:(g&&Array.isArray(g.items)?g.items:[]);if(existing.length<20&&existing.some(x=>/^g\d+$/.test(x.id||'')))return clone(DEFAULT_GEAR);const byName=new Map(DEFAULT_GEAR.map(x=>[normal(x.name),clone(x)]));for(const x of existing){const k=normal(x.name||'');if(k&&byName.has(k))byName.set(k,{...byName.get(k),...x});else if(k)byName.set(k,x)}return[...byName.values()]}
function load(){try{const s=merge(clone(base),JSON.parse(localStorage.getItem(KEY)||'{}'));s.gear=restoreGear(s.gear);return s}catch{return clone(base)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render();scheduleAudit()}
function loadUndo(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{return[]}}
function snapshot(label){undoStack.push({label,state:clone(state)});if(undoStack.length>40)undoStack.shift();localStorage.setItem(HISTORY_KEY,JSON.stringify(undoStack));updateUndo()}
function undo(){const x=undoStack.pop();if(!x)return toast('Nothing to undo');state=x.state;state.gear=restoreGear(state.gear);localStorage.setItem(HISTORY_KEY,JSON.stringify(undoStack));localStorage.setItem(KEY,JSON.stringify(state));render();toast('Undid '+x.label)}
function updateUndo(){const b=$('#undoBtn');if(b){b.disabled=!undoStack.length;b.title=undoStack.length?'Undo: '+undoStack[undoStack.length-1].label:'Nothing to undo'}}
function currentDay(){return days[state.ride.selectedDay]}function taskKey(i,d=currentDay()){return d.day+'_'+i}function status(i,d=currentDay()){return state.ride.tasks[taskKey(i,d)]||'upcoming'}function dayProgress(d=currentDay()){const done=d.tasks.filter((_,i)=>['done','skipped'].includes(status(i,d))).length;return Math.round(done/d.tasks.length*100)}function actualSpent(){return Object.values(state.ride.expenses).reduce((a,b)=>a+(Number(b)||0),0)}function chainKm(){return Math.max(0,state.bike.odo-state.bike.chainLast)}
function toast(t){const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}

function renderPage(page){if(page==='home')renderHome();if(page==='bike')renderBike();if(page==='rides')renderRides();if(page==='gear')renderGear();if(page==='docs')renderDocs()}
function setPage(page,push=true){state.ui.page=page;$$('.page').forEach(p=>p.classList.toggle('active',p.id===page));$$('.navbtn[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(push)history.pushState({page},'',location.pathname+'#'+page);window.scrollTo(0,0);renderPage(page)}
function initHistory(){const h=location.hash.slice(1);if(['home','bike','rides','gear','docs'].includes(h))state.ui.page=h;history.replaceState({page:state.ui.page||'home'},'',location.pathname+'#'+(state.ui.page||'home'))}
function universalUndoHtml(){const x=undoStack[undoStack.length-1];return x?`<div class="undo-row" style="margin:0 0 10px"><span class="caption">Last change: ${esc(x.label)}</span><button class="secondary" style="height:34px" onclick="undo();closeModal()">↶ Undo</button></div>`:''}
function setModalHtml(html){$('#modal').innerHTML='<div class="grab"></div>'+universalUndoHtml()+html}
function openModal(html){const already=$('#modalWrap').classList.contains('open');if(!already){modalWindowScroll=window.scrollY;modalRideScroll=$('#rideMode').scrollTop||0;$('#modalWrap').classList.add('open');document.body.style.overflow='hidden';history.pushState({...history.state,modal:true},'',location.href)}setModalHtml(html)}
function hideModalOnly(){$('#modalWrap').classList.remove('open');document.body.style.overflow=$('#rideMode').classList.contains('open')?'hidden':'';setTimeout(()=>{if($('#rideMode').classList.contains('open'))$('#rideMode').scrollTop=modalRideScroll;else window.scrollTo(0,modalWindowScroll)},0)}
function closeModal(){if(history.state?.modal)history.back();else hideModalOnly()}
$('#modalWrap').addEventListener('click',e=>{if(e.target.id==='modalWrap')closeModal()});
function hideRideModeOnly(){$('#rideMode').classList.remove('open');document.body.style.overflow='';}
window.addEventListener('popstate',e=>{if($('#modalWrap').classList.contains('open')){hideModalOnly();return}if($('#rideMode').classList.contains('open')&&!e.state?.rideMode){hideRideModeOnly();return}const p=e.state?.page||location.hash.slice(1)||'home';state.ui.page=p;$$('.page').forEach(x=>x.classList.toggle('active',x.id===p));$$('.navbtn[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p));renderPage(p)});

function render(){renderHome();renderBike();renderGear();renderRides();renderDocs();updateUndo();$$('.page').forEach(p=>p.classList.toggle('active',p.id===(state.ui.page||'home')));$$('.navbtn[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===(state.ui.page||'home')));renderCountdown()}
function renderHome(){const c=chainKm();$('#home').innerHTML=`<div class="card hero"><div class="kicker">RIDER HUB</div><h1>Your motorcycle OS.<br><span>Ready for the next ride.</span></h1><div class="bikeplate" onclick="setPage('bike')"><div class="row between"><div><strong>${state.bike.name}</strong><div class="caption">${state.bike.trim}</div></div><span class="pill ${c>500?'due':c>=400?'soon':'good'}">CHAIN ${c} KM</span></div><div class="metrics"><div class="metric"><label>ODOMETER</label><b>${state.bike.odo.toLocaleString('en-IN')} km</b></div><div class="metric"><label>NEXT SERVICE</label><b class="ember">${state.bike.nextServiceKm.toLocaleString('en-IN')} km</b></div></div></div></div><div class="section-head"><div><div class="kicker">QUICK ACCESS</div><h2>Rider controls</h2></div></div><div class="quickgrid"><button class="quick" onclick="setPage('rides')"><b>↗</b><span>Upcoming ride</span></button><button class="quick" onclick="editOdo()"><b>◉</b><span>Odometer</span></button><button class="quick" onclick="openExpenses()"><b>₹</b><span>Expenses</span></button><button class="quick" onclick="openNotifications()"><b>!</b><span>Alerts</span></button></div><div class="section-head"><div><div class="kicker">NEEDS ATTENTION</div><h2>Bike status</h2></div></div><div class="card attention"><div class="row between"><div><strong>Chain care</strong><div class="caption">Rider Hub reminder at 400 km · due by 500 km</div></div><span class="pill ${c>500?'due':c>=400?'soon':'good'}">${c<400?'GOOD':c<=500?'DUE SOON':'OVERDUE'}</span></div><div class="progress" style="margin-top:12px"><i style="width:${Math.min(100,c/5)}%"></i></div></div>`}

function renderBike(){const b=state.bike,c=chainKm(),acc=state.gear.filter(x=>x.category==='Bike Accessories'&&x.status==='owned');$('#bike').innerHTML=`<div class="card bike-hero"><div class="kicker">MY MOTORCYCLE</div><h1>${b.name}</h1><p>${b.trim}</p><div class="metrics"><div class="metric"><label>MASTER ODOMETER</label><b>${b.odo.toLocaleString('en-IN')} km</b></div><div class="metric"><label>OWNED SINCE</label><b>${b.purchase}</b></div></div></div><div class="section-head"><div><div class="kicker">OVERVIEW</div><h2>Bike information</h2></div><button class="secondary" onclick="editOdo()">Edit odo</button></div><div class="bike-info-grid">${[['Manufacturer',b.manufacturer],['Model',b.model],['Variant',b.variant],['Colour',b.colour],['Year',b.year],['Engine',b.engine],['Braking',b.braking],['Transmission',b.transmission],['Fuel tank',b.fuelTank],['Tyres',b.tyres],['Insurance',b.insurance],['First service',`${b.firstService.odo} km · ${b.firstService.date} · ${money(b.firstService.cost)}`],['Next service',`${b.nextServiceKm.toLocaleString('en-IN')} km or ${b.nextServiceDate}`]].map(x=>`<div class="info"><label>${String(x[0]).toUpperCase()}</label><b>${x[1]}</b></div>`).join('')}</div><div class="section-head"><div><div class="kicker">MAINTENANCE</div><h2>Maintenance engine</h2></div></div><div class="card list"><div class="listrow"><div class="ico">⛓</div><div><strong>Chain clean + lube</strong><p>${c} km since last care. Manufacturer interval: 500 km. Rider Hub custom reminder begins at 400 km.</p></div><span class="pill ${c>500?'due':c>=400?'soon':'good'}">${c>500?'OVERDUE':c>=400?'SOON':'GOOD'}</span></div><div class="listrow"><div class="ico">🔧</div><div><strong>Second service</strong><p>5,500–6,000 km or 6 months, whichever comes first.</p></div><span class="pill soon">UPCOMING</span></div><div class="listrow"><div class="ico">🛞</div><div><strong>Tyre pressure</strong><p>Check weekly and before long rides.</p></div><span class="pill good">WEEKLY</span></div></div><div class="section-head"><div><div class="kicker">SERVICE HISTORY</div><h2>Completed work</h2></div></div><div class="card list">${(b.serviceHistory||[]).map(x=>`<div class="listrow"><div class="ico">✓</div><div><strong>${esc(x.name)}</strong><p>${esc(x.date)} · ${x.odo} km · ${esc(x.work)}</p></div><b>${money(x.cost)}</b></div>`).join('')}</div><div class="section-head"><div><div class="kicker">ACCESSORIES</div><h2>Installed / owned</h2></div></div><div class="card list">${acc.slice(0,12).map(x=>`<div class="listrow"><div class="ico">◇</div><div><strong>${esc(x.name)}</strong><p>${esc(x.note||'Bike accessory')}</p></div><span class="pill good">OWNED</span></div>`).join('')}</div>`}
function editOdo(){openModal(`<div class="modalhead"><div><div class="kicker">MASTER ODOMETER</div><h3>Update reading</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="field"><label>ODOMETER KM</label><input id="odoInput" inputmode="numeric" value="${state.bike.odo}"></div><div id="odoWarn" class="alert" style="display:none"></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Close</button><button class="confirm" onclick="saveOdo()">✓ Confirm</button></div>`)}
function saveOdo(){const v=Math.round(Number($('#odoInput').value));if(!Number.isFinite(v)||v<0)return toast('Check the odometer');if(v<state.bike.odo){$('#odoWarn').style.display='block';$('#odoWarn').innerHTML=`This is lower than the current master odometer (${state.bike.odo.toLocaleString('en-IN')} km). If this is a correction, tap Confirm again.`;if($('#odoWarn').dataset.armed!=='1'){ $('#odoWarn').dataset.armed='1';return}}snapshot('odometer');state.bike.odo=v;save();closeModal();toast('Odometer updated')}

function gearSummary(){const owned=state.gear.filter(x=>x.status==='owned'),planned=state.gear.filter(x=>x.status==='planned');return{owned:owned.length,planned:planned.length,spent:owned.reduce((a,x)=>a+(Number(x.amount)||0),0),budget:planned.reduce((a,x)=>a+(Number(x.amount)||0),0)}}
function renderGear(){const sm=gearSummary();$('#gear').innerHTML=`<div class="card gear-hero"><div class="kicker">GEAR GARAGE</div><h1>Your riding setup</h1><p>Riding gear, luggage, electronics, bike accessories, camera mounts and care products.</p><div class="grid2" style="margin-top:14px"><div class="tile"><label>BOUGHT</label><b>${sm.owned}</b></div><div class="tile"><label>WILL BUY</label><b>${sm.planned}</b></div><div class="tile"><label>KNOWN SPEND</label><b>${money(sm.spent)}</b></div><div class="tile"><label>PLANNED BUDGET</label><b>${money(sm.budget)}</b></div></div></div><div class="section-head"><div><div class="kicker">INVENTORY</div><h2>Gear + accessories</h2></div><button class="secondary" onclick="openGearEditor()">+ Add</button></div><div class="field" style="margin-top:0"><input id="gearSearch" placeholder="Search gear…" value="${esc(gearQuery)}" oninput="gearQuery=this.value;renderGearList()"></div><div class="row" style="overflow:auto;margin:9px 0 10px"><button class="secondary" onclick="gearStatusFilter='all';renderGearList()">All</button><button class="secondary" onclick="gearStatusFilter='owned';renderGearList()">Bought</button><button class="secondary" onclick="gearStatusFilter='planned';renderGearList()">Will buy</button><button class="secondary" onclick="gearOwnerFilter='all';renderGearList()">All owners</button><button class="secondary" onclick="gearOwnerFilter='Jayrut';renderGearList()">Jayrut</button><button class="secondary" onclick="gearOwnerFilter='Mom';renderGearList()">Mom</button></div><div id="gearList"></div>`;renderGearList()}
function renderGearList(){const root=$('#gearList');if(!root)return;const q=gearQuery.trim().toLowerCase();const items=state.gear.filter(x=>(gearStatusFilter==='all'||x.status===gearStatusFilter)&&(gearOwnerFilter==='all'||x.owner===gearOwnerFilter)&&(!q||`${x.name} ${x.category} ${x.owner} ${x.note||''}`.toLowerCase().includes(q)));const order=['Riding Gear','Luggage','Electronics','Bike Accessories','Camera & Mounts','Cleaning & Care'];root.innerHTML=order.map(cat=>{const rows=items.filter(x=>x.category===cat);if(!rows.length)return'';return`<div class="section-head" style="margin-top:18px"><div><div class="kicker">${esc(cat)}</div><h2>${rows.length} item${rows.length===1?'':'s'}</h2></div></div><div class="card list">${rows.map(x=>`<div class="listrow" onclick="openGearDetail('${x.id}')" style="cursor:pointer"><div class="ico">${cat==='Riding Gear'?'◒':cat==='Luggage'?'▣':cat==='Electronics'?'◉':cat==='Camera & Mounts'?'◎':'◇'}</div><div><strong>${esc(x.name)}${x.qty>1?` ×${x.qty}`:''}</strong><p>${esc(x.owner)} · ${esc(x.category)}</p></div><div style="text-align:right"><b style="font-size:10px">${money(x.amount)}</b><div><span class="pill ${x.status==='owned'?'good':'soon'}">${x.status==='owned'?'BOUGHT':'WILL BUY'}</span></div></div></div>`).join('')}</div>`}).join('')||'<div class="card" style="padding:18px"><div class="caption">No items match these filters.</div></div>'}
function openGearDetail(id){const x=state.gear.find(g=>g.id===id);if(!x)return;selectedGearId=id;openModal(`<div class="modalhead"><div><div class="kicker">${x.status==='owned'?'BOUGHT':'PLANNED'}</div><h3>${esc(x.name)}</h3><p class="caption">${esc(x.owner)} · ${esc(x.category)}</p></div><button class="round" onclick="closeModal()">×</button></div><div class="grid2"><div class="tile"><label>STATUS</label><b>${x.status==='owned'?'Bought / Owned':'Will Buy'}</b></div><div class="tile"><label>${x.status==='owned'?'PAID':'EXPECTED'}</label><b>${money(x.amount)}</b></div><div class="tile"><label>QUANTITY</label><b>${x.qty||1}</b></div><div class="tile"><label>OWNER</label><b>${esc(x.owner)}</b></div></div><div class="alert">${esc(x.note||'No note yet.')}</div><div class="grid2" style="margin-top:12px"><button class="secondary" onclick="openGearEditor('${x.id}')">Edit</button><button class="secondary" onclick="toggleGearStatus('${x.id}')">${x.status==='owned'?'Move to Will Buy':'Mark bought'}</button></div>`)}
function openGearEditor(id=null){const x=id?state.gear.find(g=>g.id===id):null;selectedGearId=id;openModal(`<div class="modalhead"><div><div class="kicker">GEAR GARAGE</div><h3>${x?'Edit item':'Add item'}</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="field"><label>NAME</label><input id="gName" value="${esc(x?.name||'')}"></div><div class="grid2"><div class="field"><label>CATEGORY</label><select id="gCat">${['Riding Gear','Luggage','Electronics','Bike Accessories','Camera & Mounts','Cleaning & Care'].map(v=>`<option ${x?.category===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>OWNER</label><select id="gOwner">${['Jayrut','Mom','Bike / Shared'].map(v=>`<option ${x?.owner===v?'selected':''}>${v}</option>`).join('')}</select></div></div><div class="grid2"><div class="field"><label>STATUS</label><select id="gStatus"><option value="owned" ${x?.status==='owned'?'selected':''}>Bought</option><option value="planned" ${x?.status==='planned'?'selected':''}>Will Buy</option></select></div><div class="field"><label>QUANTITY</label><input id="gQty" inputmode="numeric" value="${x?.qty||1}"></div></div><div class="field"><label>PRICE ₹ · leave blank if TBD</label><input id="gAmount" inputmode="decimal" value="${x?.amount??''}"></div><div class="field"><label>NOTE</label><textarea id="gNote">${esc(x?.note||'')}</textarea></div><div class="modal-actions"><button class="secondary" onclick="${x?`openGearDelete('${x.id}')`:'closeModal()'}">${x?'Delete':'Cancel'}</button><button class="confirm" onclick="saveGearItem('${x?.id||''}')">✓ Save</button></div>`)}
function saveGearItem(id){const name=$('#gName').value.trim();if(!name)return toast('Add a name');const raw=$('#gAmount').value.trim();const amount=raw===''?null:Number(raw);if(amount!=null&&!Number.isFinite(amount))return toast('Check price');const item={id:id||'g_'+Date.now().toString(36),name,category:$('#gCat').value,owner:$('#gOwner').value,status:$('#gStatus').value,qty:Math.max(1,Math.round(Number($('#gQty').value)||1)),amount,note:$('#gNote').value.trim()};snapshot(id?'edit gear':'add gear');if(id){const i=state.gear.findIndex(x=>x.id===id);state.gear[i]={...state.gear[i],...item}}else state.gear.push(item);save();closeModal();toast(id?'Gear updated':'Gear added')}
function toggleGearStatus(id){const x=state.gear.find(g=>g.id===id);if(!x)return;snapshot('gear status');x.status=x.status==='owned'?'planned':'owned';save();closeModal();toast(x.status==='owned'?'Marked bought':'Moved to Will Buy')}
function openGearDelete(id){const x=state.gear.find(g=>g.id===id);if(!x)return;openModal(`<div class="modalhead"><div><div class="kicker">DELETE GEAR</div><h3>${esc(x.name)}</h3><p class="caption">This can be undone from the global Undo button.</p></div><button class="round" onclick="openGearDetail('${id}')">×</button></div><div class="modal-actions"><button class="secondary" onclick="openGearDetail('${id}')">Cancel</button><button class="danger" onclick="deleteGear('${id}')">Delete</button></div>`)}
function deleteGear(id){snapshot('delete gear');state.gear=state.gear.filter(x=>x.id!==id);save();closeModal();toast('Gear deleted')}

function renderDocs(){$('#docs').innerHTML=`<div class="card doc-hero"><div class="kicker">DOCUMENT VAULT</div><h1>Bike + rider documents</h1><p>Sensitive identifiers stay hidden by default. Private files stay on this device until we move to authenticated cloud storage.</p><div class="grid3" style="margin-top:14px"><div class="tile"><label>RECORDS</label><b>${DOCS.length}</b></div><div class="tile"><label>INSURANCE</label><b>Active</b></div><div class="tile"><label>SERVICE</label><b>1 invoice</b></div></div></div><div class="section-head"><div><div class="kicker">VAULT</div><h2>Stored records</h2></div></div><div class="card list">${DOCS.map(x=>`<div class="listrow" onclick="openDocDetail('${x.id}')" style="cursor:pointer"><div class="ico">▤</div><div><strong>${esc(x.name)}</strong><p>${esc(x.summary)}</p></div><span class="pill good">SAVED</span></div>`).join('')}</div><div class="section-head"><div><div class="kicker">DIGILOCKER</div><h2>Verified documents</h2></div></div><div class="card" style="padding:14px"><div class="row between"><div><strong>DigiLocker connector</strong><div class="caption">Architecture-ready, but official Requester/partner credentials are required before a real connection can go live.</div></div><span class="pill soon">NOT CONNECTED</span></div><button class="secondary full" style="margin-top:10px" onclick="openDigiLockerInfo()">Integration requirements</button></div>`}
function openDocDetail(id){const x=DOCS.find(d=>d.id===id);if(!x)return;openModal(`<div class="modalhead"><div><div class="kicker">DOCUMENT</div><h3>${esc(x.name)}</h3><p class="caption">${esc(x.summary)}</p></div><button class="round" onclick="closeModal()">×</button></div><div class="alert">${esc(x.detail)}</div><div class="grid2" style="margin-top:12px"><button class="secondary" onclick="openPrivateDoc('${x.id}')">Open / attach file</button>${x.id==='hotelBooking'?'<button class="secondary" onclick="openBookingPdf()">Open booking</button>':'<button class="secondary" onclick="removePrivateDocPrompt(\''+x.id+'\')">Manage attachment</button>'}</div>`)}
function openDigiLockerInfo(){openModal(`<div class="modalhead"><div><div class="kicker">DIGILOCKER</div><h3>Official integration path</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="alert">Rider Hub cannot safely connect to DigiLocker with only front-end HTML/JavaScript. We need official DigiLocker Requester onboarding, OAuth credentials and a secure server-side callback/token service. The app architecture will keep a Document Service connector so manual files, cloud storage and DigiLocker can coexist.</div><div class="caption" style="margin-top:10px">No DigiLocker password, OTP or API secret will ever be stored in browser code.</div>`)}
function openDb(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains('docs'))q.result.createObjectStore('docs')};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function savePrivateDoc(key,file){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction('docs','readwrite');tx.objectStore('docs').put(file,key);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function getPrivateDoc(key){const db=await openDb();return new Promise((res,rej)=>{const q=db.transaction('docs').objectStore('docs').get(key);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function deletePrivateDoc(key){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction('docs','readwrite');tx.objectStore('docs').delete(key);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function openPrivateDoc(key){const f=await getPrivateDoc(key);if(f){window.open(URL.createObjectURL(f),'_blank');return}openPrivateDocPicker(key)}
function openPrivateDocPicker(key){const x=DOCS.find(d=>d.id===key);openModal(`<div class="modalhead"><div><div class="kicker">PRIVATE FILE</div><h3>Attach ${esc(x?.name||'document')}</h3><p class="caption">The file stays in this browser's IndexedDB and is not published to the public GitHub repository.</p></div><button class="round" onclick="closeModal()">×</button></div><input id="privateDocFile" type="file" accept="application/pdf,image/*" hidden onchange="showPrivateFileName(this)"><div class="row" style="margin-top:12px"><button class="secondary" onclick="$('#privateDocFile').click()">Choose file</button><span id="privateFileName" class="caption">No file selected</span></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="confirm" onclick="attachPrivateDoc('${key}')">✓ Save privately</button></div>`)}
function showPrivateFileName(i){$('#privateFileName').textContent=i.files?.[0]?.name||'No file selected'}
async function attachPrivateDoc(key){const f=$('#privateDocFile')?.files?.[0];if(!f)return toast('Choose a file');await savePrivateDoc(key,f);if(key==='hotelBooking')state.ride.backup.booking=true;save();closeModal();toast('Private document saved')}
async function removePrivateDocPrompt(key){const f=await getPrivateDoc(key);if(!f)return openPrivateDocPicker(key);openModal(`<div class="modalhead"><div><div class="kicker">PRIVATE FILE</div><h3>Attachment saved</h3><p class="caption">${esc(f.name||'Attached file')}</p></div><button class="round" onclick="closeModal()">×</button></div><div class="grid2"><button class="secondary" onclick="openPrivateDoc('${key}')">Open</button><button class="danger" onclick="removePrivateDoc('${key}')">Remove</button></div>`)}
async function removePrivateDoc(key){await deletePrivateDoc(key);closeModal();toast('Private attachment removed')}
async function openBookingPdf(){const f=await getPrivateDoc('hotelBooking');if(f){window.open(URL.createObjectURL(f),'_blank');return}openModal(`<div class="modalhead"><div><div class="kicker">HOTEL BOOKING</div><h3>Attach the original booking PDF once</h3><p class="caption">The public GitHub site cannot safely contain your personal booking voucher. Attach the exact PDF once; Rider Hub stores it only on this device.</p></div><button class="round" onclick="closeModal()">×</button></div><input id="bookingFile" type="file" accept="application/pdf" hidden onchange="showBookingFileName(this)"><div class="row" style="margin-top:12px"><button class="secondary" onclick="$('#bookingFile').click()">Choose booking PDF</button><span id="bookingFileName" class="caption">No PDF selected</span></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Close</button><button class="confirm" onclick="attachBooking()">✓ Save privately</button></div>`)}
function showBookingFileName(i){$('#bookingFileName').textContent=i.files?.[0]?.name||'No PDF selected'}
async function attachBooking(){const f=$('#bookingFile')?.files?.[0];if(!f)return toast('Choose the booking PDF');await savePrivateDoc('hotelBooking',f);state.ride.backup.booking=true;save();closeModal();toast('Original booking PDF saved privately')}

function renderRides(){const d=currentDay(),p=dayProgress();$('#rides').innerHTML=`<div class="card ride-hero"><div class="kicker">UPCOMING RIDE</div><h1>Banswara 3-Day Ronin Adventure</h1><p>28–30 Aug 2026 · 2 riders · TVS Ronin</p><div class="ride-mode-cta"><button class="primary" onclick="openRideMode()">Open Ride Mode · Day ${d.day}</button><div class="countdown"><div class="kicker">NEXT</div><b id="nextTaskTime">—</b></div></div><button class="secondary full" onclick="addNextTaskToCalendar()">Add next task to Google Calendar</button></div><div id="weatherCard" class="card weather">Loading live Banswara weather…</div><div class="card booking" style="margin-top:10px"><div class="row between"><div><div class="kicker">STAY CONFIRMED</div><h3>Hotel Landmark, Banswara</h3><div class="caption">28–30 Aug · 2 nights · Deluxe Room · ₹2,470 paid</div></div><span class="pill good">PAID</span></div><div class="booking-actions"><button class="secondary" onclick="openBookingPdf()">Open booking</button><button class="secondary" onclick="openHotelMap()">Map hotel</button></div></div><div class="section-head"><div><div class="kicker">CHOOSE DAY</div><h2>Ride plan</h2></div></div><div class="daytabs">${days.map((x,i)=>`<button class="daytab ${i===state.ride.selectedDay?'active':''}" onclick="selectDay(${i})">Day ${x.day} · ${x.from} → ${x.to}</button>`).join('')}</div><div class="card" style="padding:14px;margin-top:8px"><div class="row between"><div><div class="kicker">DAY ${d.day}</div><strong>${d.title}</strong></div><span class="pill soon">${p}% DONE</span></div><div class="progress" style="margin:12px 0"><i style="width:${p}%"></i></div><div class="timeline">${d.tasks.map((t,i)=>taskRow(t,i)).join('')}</div></div><div class="section-head"><div><div class="kicker">TRIP TOOLKIT</div><h2>Ride operations</h2></div></div><div class="toolgrid">${[['₹','Expenses','openExpenses()'],['📝','Notes','openNotes()'],['⛽','Fuel log','openFuel()'],['⚠','Bike issue','openIssue()'],['◉','Content','openChecklist("content")'],['☁','Media backup','openChecklist("backup")'],['▣','Packing','openChecklist("packing")'],['→','Tomorrow','openTomorrow()'],['SOS','Emergency','openEmergency()'],['↕','Traffic','openTraffic()'],['⇄','Export / import','openTransfer()'],['Σ','Ride Summary','openSummary()']].map(x=>`<button class="tool" onclick='${x[2]}'><b>${x[0]}</b><span>${x[1]}</span></button>`).join('')}</div><div class="section-head"><div><div class="kicker">ROUTE</div><h2>Motorcycle route parts</h2></div></div><div class="card" style="padding:12px"><div class="alert" style="margin-top:0">Route buttons use Google Maps two-wheeler mode where available. Long routes are deliberately split so Google does not drop or reinterpret too many anchors.</div>${d.segments.map((s,i)=>routeCard(s,i,false)).join('')}${d.backup?d.backup.map((s,i)=>routeCard(s,i,true)).join(''):''}</div>`;renderWeather();renderCountdown()}
function routeCard(s,i,b){return`<div class="routecard"><div class="row between"><strong>${b?'Wet-weather · ':''}${s.label}</strong><button class="secondary" onclick="openRoute(${i},${b})">Open route</button></div><p>${[s.origin,...s.waypoints,s.destination].map((x,j)=>`${j+1}. ${esc(x)}`).join('<br>')}</p></div>`}
function mapsUrl(s){const q=new URLSearchParams({api:'1',origin:s.origin,destination:s.destination,travelmode:'two-wheeler',dir_action:'navigate'});if(s.waypoints?.length)q.set('waypoints',s.waypoints.join('|'));return'https://www.google.com/maps/dir/?'+q.toString()}
function openRoute(i=0,b=false){const d=currentDay(),s=b?d.backup?.[i]:d.segments[i];if(!s)return;window.open(mapsUrl(s),'_blank','noopener')}
function openHotelMap(){window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(HOTEL),'_blank','noopener')}
function selectDay(i){snapshot('selected ride day');state.ride.selectedDay=i;save();toast('Day '+days[i].day+' selected')}
function taskRow(t,i){const s=status(i);return`<div class="task ${s}"><time>${t[0]}</time><div><strong>${esc(t[1])}</strong><p>${esc(t[2])}${state.ride.tasks[taskKey(i)+'_delay']?` · delayed ${state.ride.tasks[taskKey(i)+'_delay']} min`:''}</p></div><button onclick="openTaskActions(${i})">${s.toUpperCase()}</button></div>`}
function openTaskActions(i){const t=currentDay().tasks[i];openModal(`<div class="modalhead"><div><div class="kicker">DAY ${currentDay().day} · ${t[0]}</div><h3>${esc(t[1])}</h3><p class="caption">${esc(t[2])}</p></div><button class="round" onclick="closeModal()">×</button></div><div class="action3"><button class="confirm" onclick="setTaskFromModal(${i},'done')">Done</button><button class="secondary" onclick="delayTask(${i})">Delay</button><button class="secondary" onclick="setTaskFromModal(${i},'skipped')">Skip</button></div>`)}
function applyTask(i,s){const d=currentDay();snapshot('ride task');state.ride.tasks[taskKey(i,d)]=s;delete state.ride.tasks[taskKey(i,d)+'_delay'];const complete=d.tasks.every((_,j)=>['done','skipped'].includes(state.ride.tasks[taskKey(j,d)]||'upcoming'));let advanced=false;if(complete&&state.ride.selectedDay<days.length-1){state.ride.selectedDay++;advanced=true}save();return advanced}
function setTaskFromModal(i,s){const advanced=applyTask(i,s);closeModal();toast(advanced?'Day complete · moved to Day '+currentDay().day:'Task '+s)}
function setRideModeTask(i,s){const advanced=applyTask(i,s);renderRideMode();toast(advanced?'Day complete · Day '+currentDay().day+' ready':'Task '+s)}
function delayTask(i){openModal(`<div class="modalhead"><div><div class="kicker">DELAY</div><h3>How long?</h3><p class="caption">This records the delay inside Rider Hub without changing every later hard time.</p></div><button class="round" onclick="closeModal()">×</button></div><div class="field"><label>MINUTES</label><input id="delayMinutes" inputmode="numeric" value="30"></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="confirm" onclick="saveDelay(${i})">✓ Save delay</button></div>`)}
function saveDelay(i){const m=Math.max(0,Math.round(Number($('#delayMinutes').value)||0));snapshot('ride delay');state.ride.tasks[taskKey(i)]='delayed';state.ride.tasks[taskKey(i)+'_delay']=m;save();closeModal();if($('#rideMode').classList.contains('open'))renderRideMode();toast('Delay recorded')}

function openExpenses(){draftExpenses=clone(state.ride.expenses);renderExpenseModal()}
function renderExpenseModal(){const spent=Object.values(draftExpenses).reduce((a,b)=>a+(Number(b)||0),0),remaining=state.ride.budgetMax-spent;openModal(`<div class="modalhead"><div><div class="kicker">TRIP MONEY</div><h3>Expenses</h3><p class="caption">Amounts remain drafts until you press the green check.</p></div><button class="round" onclick="closeModal()">×</button></div><div class="grid3"><div class="tile"><label>ACTUAL SPENT</label><b id="draftSpent">${money(spent)}</b></div><div class="tile"><label>HIGH TARGET</label><b>${money(state.ride.budgetMax)}</b></div><div class="tile"><label>REMAINING</label><b id="draftRemaining">${remaining>=0?money(remaining):money(Math.abs(remaining))+' over'}</b></div></div><div style="margin-top:10px">${Object.entries({hotel:'Hotel',fuel:'Fuel',food:'Food',parking:'Parking / water',misc:'Miscellaneous'}).map(([k,l])=>`<div class="moneyrow"><div><strong>${l}</strong><div class="caption">${k==='hotel'?'Confirmed stay':k==='fuel'?'Fuel logs also update this automatically':'Trip spending'}</div></div><input inputmode="decimal" value="${Number(draftExpenses[k]||0)||''}" placeholder="₹0" oninput="draftExpense('${k}',this.value)"></div>`).join('')}</div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Close</button><button class="confirm" onclick="confirmExpenses()">✓ Confirm</button></div>`)}
function draftExpense(k,v){draftExpenses[k]=Math.max(0,Number(v)||0);const s=Object.values(draftExpenses).reduce((a,b)=>a+(Number(b)||0),0),r=state.ride.budgetMax-s;if($('#draftSpent'))$('#draftSpent').textContent=money(s);if($('#draftRemaining'))$('#draftRemaining').textContent=r>=0?money(r):money(Math.abs(r))+' over'}
function confirmExpenses(){snapshot('expenses');state.ride.expenses=clone(draftExpenses);save();closeModal();toast('Expenses confirmed')}
function openNotes(){openModal(`<div class="modalhead"><div><div class="kicker">RIDE NOTES</div><h3>Notes</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="field"><textarea id="notes">${esc(state.ride.notes)}</textarea></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Close</button><button class="confirm" onclick="saveNotes()">✓ Confirm</button></div>`)}
function saveNotes(){snapshot('ride notes');state.ride.notes=$('#notes').value;save();closeModal();toast('Notes saved')}
function openFuel(){const logs=state.ride.fuelLogs.slice().reverse();openModal(`<div class="modalhead"><div><div class="kicker">FUEL LOG</div><h3>Fuel stops</h3><p class="caption">Every confirmed fuel amount also adds automatically to the Fuel expense total.</p></div><button class="round" onclick="closeModal()">×</button></div><div class="grid2"><div class="tile"><label>FUEL SPEND</label><b>${money(state.ride.expenses.fuel)}</b></div><div class="tile"><label>LOGS</label><b>${logs.length}</b></div></div><div class="grid2"><div class="field"><label>ODOMETER KM</label><input id="fuelOdo" inputmode="numeric" value="${state.bike.odo}"></div><div class="field"><label>LITRES</label><input id="fuelL" inputmode="decimal" placeholder="0.00"></div></div><div class="field"><label>AMOUNT ₹</label><input id="fuelAmt" inputmode="decimal" placeholder="0"></div><button class="confirm full" onclick="addFuelLog()">✓ Add fuel stop</button><div style="margin-top:10px">${logs.length?logs.map(x=>`<div class="routecard"><strong>${esc(x.time)} · ${x.odo} km</strong><p>${x.litres?x.litres+' L · ':''}${money(x.amount)}</p></div>`).join(''):'<div class="caption">No fuel stops recorded.</div>'}</div>`)}
function addFuelLog(){const odo=Math.round(Number($('#fuelOdo').value)),litres=Number($('#fuelL').value)||0,amount=Number($('#fuelAmt').value)||0;if(!Number.isFinite(odo)||odo<0)return toast('Check odometer');snapshot('fuel log');state.ride.fuelLogs.push({odo,litres,amount,time:new Date().toLocaleString()});state.ride.expenses.fuel=Number(state.ride.expenses.fuel||0)+amount;if(odo>state.bike.odo)state.bike.odo=odo;save();openFuel();toast(`${money(amount)} added to Fuel expense`)}
function openIssue(){openModal(`<div class="modalhead"><div><div class="kicker">BIKE LOG</div><h3>Bike issue</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="field"><label>ISSUE</label><input id="issue" placeholder="Noise, loose strap, warning light…"></div><div class="field"><label>SEVERITY</label><select id="severity"><option>Monitor</option><option>Needs attention</option><option>Stop riding</option></select></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Close</button><button class="confirm" onclick="saveIssue()">✓ Confirm</button></div>`)}
function saveIssue(){const n=$('#issue').value.trim();if(!n)return toast('Add issue');snapshot('bike issue');state.ride.issues.push({note:n,severity:$('#severity').value,time:new Date().toLocaleString(),odo:state.bike.odo});save();closeModal();toast('Issue saved')}
function checklistLabels(group){return{packing:{rain:'Rain gear + waterproof bags',firstaid:'First-aid + ORS',puncture:'Puncture kit + inflator',tools:'Basic tools',power:'Power + charging',documents:'DL / RC / insurance / PUC',water:'Water + snacks',socks:'Dry socks / walking shoes'},content:{departure:'Departure shot',mangarh:'Mangarh',chacha:'Chacha Kota',mahi:'Mahi Dam',singhpura:'Singhpura Falls',jagmer:'Jagmer',arthuna:'Arthuna',arrival:'Arrival'},backup:{action5:'Action 5 footage copied',phone:'Phone media backed up',photos:'Favourite photos selected',booking:'Booking saved offline'}}[group]}
function openChecklist(group){const labels=checklistLabels(group);openModal(`<div class="modalhead"><div><div class="kicker">${group.toUpperCase()}</div><h3>${group==='packing'?'Packing':group==='content'?'Content tracker':'Media backup'}</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="card list">${Object.entries(labels).map(([k,l])=>`<div class="listrow"><div class="ico">✓</div><div><strong>${l}</strong></div><button class="checkbtn ${state.ride[group][k]?'on':''}" onclick="toggleCheck('${group}','${k}')">✓</button></div>`).join('')}</div>`)}
function toggleCheck(g,k){snapshot(g+' checklist');state.ride[g][k]=!state.ride[g][k];save();openChecklist(g)}
function openTomorrow(){const n=days[state.ride.selectedDay+1];openModal(`<div class="modalhead"><div><div class="kicker">TOMORROW</div><h3>${n?n.title:'Final day'}</h3></div><button class="round" onclick="closeModal()">×</button></div>${n?`<div class="card" style="padding:12px">${n.tasks.slice(0,5).map(x=>`<div class="routecard"><strong>${x[0]} · ${x[1]}</strong><p>${x[2]}</p></div>`).join('')}</div>`:'<p class="caption">This is the final ride day.</p>'}`)}
function openEmergency(){openModal(`<div class="modalhead"><div><div class="kicker">EMERGENCY</div><h3>Emergency actions</h3><p class="caption">112 and 108 stay immediately available. Add up to 3 custom contacts.</p></div><button class="round" onclick="closeModal()">×</button></div><div class="grid2"><button class="primary" onclick="location.href='tel:112'">Call 112</button><button class="secondary" onclick="location.href='tel:108'">Ambulance 108</button></div><button class="secondary full" style="margin-top:8px" onclick="shareLocation()">Share current location</button>${state.ride.customEmergency.map((x,i)=>`<div class="field"><label>CUSTOM CONTACT ${i+1}</label><input id="ec${i}" value="${esc(x)}" placeholder="Name / number"></div>`).join('')}<div class="modal-actions"><button class="secondary" onclick="closeModal()">Close</button><button class="confirm" onclick="saveEmergency()">✓ Save contacts</button></div>`)}
function saveEmergency(){snapshot('emergency contacts');state.ride.customEmergency=state.ride.customEmergency.map((_,i)=>$('#ec'+i).value.trim());save();closeModal();toast('Emergency contacts saved')}
function shareLocation(){if(!navigator.geolocation)return toast('Geolocation unavailable');navigator.geolocation.getCurrentPosition(async p=>{const url=`https://maps.google.com/?q=${p.coords.latitude},${p.coords.longitude}`;try{if(navigator.share)await navigator.share({title:'My Rider Hub location',url});else{await navigator.clipboard.writeText(url);toast('Location link copied')}}catch{}},e=>toast(e.code===1?'Location permission denied. Allow Location for this site in Chrome permissions.':e.code===2?'Location unavailable. Check GPS/network.':'Location request timed out.'),{enableHighAccuracy:true,timeout:12000,maximumAge:15000})}

function openTraffic(){const key=localStorage.getItem('rh_traffic_key')||'';openModal(`<div class="modalhead"><div><div class="kicker">TRAFFIC</div><h3>Live traffic</h3><p class="caption">Google TrafficLayer stays inside Rider Hub. Your key is stored only on this device.</p></div><button class="round" onclick="closeModal()">×</button></div>${key?`<div id="trafficStatus" class="alert">Connecting live traffic…</div><div id="trafficMap" style="height:330px;border-radius:15px;overflow:hidden;margin-top:10px;background:#0b0d0f"></div><div class="grid2" style="margin-top:10px"><button class="secondary" onclick="estimateTraffic()">Estimate current segment</button><button class="secondary" onclick="showTrafficKeyEditor()">Change API key</button></div><div id="trafficEstimate" class="caption" style="margin-top:9px">Traffic colours: green = flowing, orange = moderate, red/dark red = slower traffic.</div>`:`<div class="alert">To display real traffic, paste a Google Maps JavaScript API key below. Tap the field, long-press, then Paste.</div><div class="field"><label>GOOGLE MAPS JAVASCRIPT API KEY</label><input id="trafficKey" type="password" autocomplete="off" placeholder="Paste key here"></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Close</button><button class="confirm" onclick="saveTrafficKey()">✓ Connect traffic</button></div>`}`);if(key)setTimeout(initTrafficMap,80)}
function showTrafficKeyEditor(){openModal(`<div class="modalhead"><div><div class="kicker">TRAFFIC SETUP</div><h3>Google Maps API key</h3><p class="caption">Tap the field → long-press → Paste. Use a web key restricted to thejayrut.github.io and to the Maps JavaScript API.</p></div><button class="round" onclick="openTraffic()">×</button></div><div class="field"><label>API KEY</label><input id="trafficKey" type="password" autocomplete="off" value="${esc(localStorage.getItem('rh_traffic_key')||'')}"></div><div class="modal-actions"><button class="secondary" onclick="openTraffic()">Cancel</button><button class="confirm" onclick="saveTrafficKey()">✓ Save + reconnect</button></div>`)}
function saveTrafficKey(){const k=$('#trafficKey')?.value.trim();if(!k)return toast('Paste the API key');localStorage.setItem('rh_traffic_key',k);mapsLoader=null;const old=$('#rhGoogleMaps');if(old)old.remove();openTraffic();toast('Traffic key saved on this device')}
function loadGoogleMaps(){if(window.google?.maps)return Promise.resolve();if(mapsLoader)return mapsLoader;const key=localStorage.getItem('rh_traffic_key');if(!key)return Promise.reject(new Error('No API key'));mapsLoader=new Promise((res,rej)=>{window.__rhMapsReady=()=>res();const s=document.createElement('script');s.id='rhGoogleMaps';s.src='https://maps.googleapis.com/maps/api/js?key='+encodeURIComponent(key)+'&callback=__rhMapsReady&v=weekly';s.async=true;s.onerror=()=>rej(new Error('Google Maps failed to load'));document.head.appendChild(s)});return mapsLoader}
async function initTrafficMap(){const el=$('#trafficMap');if(!el)return;try{await loadGoogleMaps();const d=currentDay();const center=d.day===2?{lat:23.55,lng:74.45}:{lat:23.15,lng:73.45};trafficMap=new google.maps.Map(el,{center,zoom:d.day===2?11:8,mapTypeControl:false,streetViewControl:false,fullscreenControl:false});trafficLayer=new google.maps.TrafficLayer();trafficLayer.setMap(trafficMap);if($('#trafficStatus'))$('#trafficStatus').innerHTML='<b>Live traffic connected.</b><br>TrafficLayer is real road-congestion data from Google Maps. Motorcycle navigation remains separate.'}catch(e){if($('#trafficStatus'))$('#trafficStatus').innerHTML='<b>Traffic connection failed.</b><br>Check that billing is active, Maps JavaScript API is enabled, and the key allows this GitHub Pages website.'}}
async function estimateTraffic(){const out=$('#trafficEstimate'),s=currentDay().segments[0];if(!out)return;out.textContent='Calculating current road traffic…';try{await loadGoogleMaps();const ds=new google.maps.DirectionsService();ds.route({origin:s.origin,destination:s.destination,waypoints:(s.waypoints||[]).map(location=>({location,stopover:true})),travelMode:google.maps.TravelMode.DRIVING,drivingOptions:{departureTime:new Date(),trafficModel:google.maps.TrafficModel.BEST_GUESS}},(r,st)=>{if(st!=='OK'||!r?.routes?.[0]){out.textContent='Traffic time estimate unavailable. The live colour layer above still works.';return}const legs=r.routes[0].legs||[];const dist=legs.reduce((a,x)=>a+(x.distance?.value||0),0)/1000;const normal=legs.reduce((a,x)=>a+(x.duration?.value||0),0);const traffic=legs.reduce((a,x)=>a+(x.duration_in_traffic?.value||x.duration?.value||0),0);const mins=Math.round(traffic/60),extra=Math.max(0,Math.round((traffic-normal)/60));out.textContent=`Current Part 1 road estimate: ${dist.toFixed(0)} km · about ${mins} min${extra?` · ~${extra} min traffic delay`:''}. This traffic estimate uses car-road congestion; use the two-wheeler route buttons for motorcycle navigation.`})}catch{out.textContent='Traffic estimate failed. Check the API key and enabled Google Maps services.'}}

function openSummary(){const d=currentDay(),missed=d.tasks.filter((_,i)=>status(i)==='upcoming'&&isPastTask(d.tasks[i][0],d.date)).length;openModal(`<div class="modalhead"><div><div class="kicker">RIDE SUMMARY</div><h3>Day ${d.day}</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="grid3"><div class="tile"><label>PROGRESS</label><b>${dayProgress()}%</b></div><div class="tile"><label>SPENT</label><b>${money(actualSpent())}</b></div><div class="tile"><label>MISSED</label><b>${missed}</b></div></div><div class="routecard"><strong>Fuel logs</strong><p>${state.ride.fuelLogs.length} · ${money(state.ride.fuelLogs.reduce((a,x)=>a+(Number(x.amount)||0),0))}</p></div><div class="routecard"><strong>Bike issues</strong><p>${state.ride.issues.length} recorded</p></div>${missed?'<button class="secondary full" onclick="reviewDayEnd()">Review missed tasks</button>':''}`)}
function openTransfer(){openModal(`<div class="modalhead"><div><div class="kicker">LOCAL BACKUP</div><h3>Export / import</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="grid2"><button class="primary" onclick="exportData()">Export JSON</button><button class="secondary" onclick="$('#importFile').click()">Import JSON</button></div>`)}
function exportData(){const b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='RiderHub_Backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function importData(f){const r=new FileReader();r.onload=()=>{try{snapshot('import');state=merge(clone(base),JSON.parse(r.result));state.gear=restoreGear(state.gear);save();closeModal();toast('Backup imported')}catch{toast('Invalid backup')}};r.readAsText(f)}

function notificationState(){return'Notification'in window?Notification.permission:'unsupported'}
function openNotifications(){const d=currentDay(),missed=d.tasks.map((t,i)=>({t,i})).filter(x=>status(x.i)==='upcoming'&&isPastTask(x.t[0],d.date));const p=notificationState();openModal(`<div class="modalhead"><div><div class="kicker">NOTIFICATIONS</div><h3>Ride + maintenance alerts</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="routecard"><strong>Browser notification status</strong><p>${p==='granted'?'Allowed for Rider Hub.':p==='denied'?'Blocked by Chrome/site permissions. Rider Hub cannot override a browser denial.':p==='default'?'Not decided yet. Tap Enable below and choose Allow.':'Notifications are not supported in this browser.'}</p></div><div class="routecard"><strong>Chain care</strong><p>${chainKm()} km since last chain care · reminder at 400 · due by 500.</p></div>${missed.length?missed.map(x=>`<div class="routecard"><strong>Missed: ${x.t[1]}</strong><p>${x.t[0]} · You can mark it Done now or Did not do in the end-of-day review.</p></div>`).join(''):'<div class="routecard"><strong>No missed ride tasks right now.</strong></div>'}<div class="grid2"><button class="secondary" onclick="requestNotifications()">${p==='denied'?'How to allow':'Enable browser notifications'}</button><button class="secondary" onclick="reviewDayEnd()">Review day</button></div><div class="caption" style="margin-top:10px">Current prototype can alert while Rider Hub is open. True push notifications while the app is closed require the Firebase/Web Push backend in the production phase.</div>`)}
async function requestNotifications(){if(!('Notification'in window))return toast('Notifications unsupported');if(Notification.permission==='granted')return toast('Notifications already allowed');if(Notification.permission==='denied'){openModal(`<div class="modalhead"><div><div class="kicker">CHROME PERMISSION</div><h3>Notifications are blocked</h3></div><button class="round" onclick="openNotifications()">×</button></div><div class="alert">Chrome does not allow a website to grant itself permission after you block it. On Android Chrome: open Rider Hub → tap the icon to the left of the address bar → Permissions → Notifications → Allow. Also make sure Android system notifications are enabled for Chrome.</div><button class="secondary full" onclick="openNotifications()">Back</button>`);return}const p=await Notification.requestPermission();toast(p==='granted'?'Notifications enabled':'Notification permission was not allowed');openNotifications()}
function isPastTask(hm,date){const m=String(hm).match(/(\d{1,2}):(\d{2})/);if(!m)return false;const dt=new Date(`${date}T${m[1].padStart(2,'0')}:${m[2]}:00`);return Date.now()>dt.getTime()}
function reviewDayEnd(){const d=currentDay(),missed=d.tasks.map((t,i)=>({t,i})).filter(x=>!['done','skipped'].includes(status(x.i,d)));openModal(`<div class="modalhead"><div><div class="kicker">DAY ${d.day} REVIEW</div><h3>${missed.length?'Unchecked tasks':'Everything checked'}</h3><p class="caption">Use Done now if you actually completed it, or Did not do if it was intentionally missed.</p></div><button class="round" onclick="closeModal()">×</button></div>${missed.length?missed.map(x=>`<div class="routecard"><strong>${esc(x.t[0])} · ${esc(x.t[1])}</strong><p>${esc(x.t[2])}</p><div class="grid2"><button class="confirm" onclick="reviewTask(${x.i},'done')">Done now</button><button class="secondary" onclick="reviewTask(${x.i},'skipped')">Did not do</button></div></div>`).join(''):'<div class="alert">Day '+d.day+' is fully resolved.</div>'}`)}
function reviewTask(i,s){const advanced=applyTask(i,s);if(advanced){closeModal();if($('#rideMode').classList.contains('open'))renderRideMode();toast('Day complete · Day '+currentDay().day+' ready')}else reviewDayEnd()}
function dayEndAudit(){const d=currentDay(),m=String(d.end).match(/(\d{1,2}):(\d{2})/);if(!m)return;const end=new Date(`${d.date}T${m[1].padStart(2,'0')}:${m[2]}:00`);if(Date.now()<end.getTime())return;const missed=d.tasks.map((t,i)=>({t,i})).filter(x=>!['done','skipped'].includes(status(x.i,d)));if(!missed.length)return;const sig='audit_'+d.day+'_'+d.date;if(sessionStorage.getItem(sig))return;sessionStorage.setItem(sig,'1');if(Notification.permission==='granted')new Notification('Rider Hub · Day '+d.day+' review',{body:`${missed.length} task${missed.length>1?'s':''} still unchecked. Open Rider Hub and review them.`});if(!$('#modalWrap').classList.contains('open'))reviewDayEnd();else toast(`${missed.length} end-of-day tasks still unchecked`)}
function scheduleAudit(){clearInterval(timerHandle);timerHandle=setInterval(()=>{renderCountdown();dayEndAudit()},30000)}
function nextOpenTask(){const d=currentDay();let i=d.tasks.findIndex((_,j)=>!['done','skipped'].includes(status(j,d)));return i<0?null:{i,t:d.tasks[i]}}
function taskDate(t,d=currentDay()){const m=String(t[0]).match(/(\d{1,2}):(\d{2})/);if(!m)return null;return new Date(`${d.date}T${m[1].padStart(2,'0')}:${m[2]}:00`)}
function renderCountdown(){const el=$('#nextTaskTime');if(!el)return;const n=nextOpenTask();if(!n){el.textContent='DONE';return}const dt=taskDate(n.t),ms=dt?dt-Date.now():0;if(!dt||ms<=0){el.textContent='NOW';return}const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000);el.textContent=h>24?`${Math.floor(h/24)}d ${h%24}h`:`${h}h ${m}m`}
function addNextTaskToCalendar(){const n=nextOpenTask();if(!n)return toast('No next task');const d=currentDay(),start=taskDate(n.t,d);if(!start)return toast('This task has no fixed clock time');const end=new Date(start.getTime()+45*60000),fmt=x=>x.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');const q=new URLSearchParams({action:'TEMPLATE',text:`Rider Hub · ${n.t[1]}`,dates:`${fmt(start)}/${fmt(end)}`,details:`Day ${d.day}: ${n.t[2]}\nRider Hub Banswara ride`,location:d.to});window.open('https://calendar.google.com/calendar/render?'+q.toString(),'_blank','noopener')}

function openRideMode(){renderRideMode();$('#rideMode').classList.add('open');document.body.style.overflow='hidden';history.pushState({page:'rides',rideMode:true},'',location.pathname+'#ride-mode')}
function closeRideMode(){if(history.state?.rideMode)history.back();else hideRideModeOnly()}
function renderRideMode(){const d=currentDay(),n=nextOpenTask(),t=n?n.t:['—','Day complete','All tasks done.'];$('#rideModeInner').innerHTML=`<div class="header" style="position:sticky"><div><div class="kicker">RIDE MODE · DAY ${d.day}</div><div class="sub">${d.from} → ${d.to}</div></div><div class="header-actions"><button class="round" onclick="undo()" ${undoStack.length?'':'disabled'}>↶</button><button class="round" onclick="closeRideMode()">×</button></div></div><div class="now"><div class="kicker">${t[0]} · CURRENT</div><h2>${esc(t[1])}</h2><p class="caption">${esc(t[2])}</p><div class="progress" style="margin-top:12px"><i style="width:${dayProgress()}%"></i></div></div>${n?`<div class="action3"><button class="confirm" onclick="setRideModeTask(${n.i},'done')">Done</button><button class="secondary" onclick="delayTask(${n.i})">Delay</button><button class="secondary" onclick="setRideModeTask(${n.i},'skipped')">Skip</button></div>`:''}<div class="toolgrid" style="margin-top:10px"><button class="tool" onclick="openRideModeMapMenu()"><b>⌖</b><span>Map</span></button><button class="tool" onclick="openExpenses()"><b>₹</b><span>Expenses</span></button><button class="tool" onclick="openEmergency()"><b>SOS</b><span>Emergency</span></button><button class="tool" onclick="openSummary()"><b>Σ</b><span>Ride Summary</span></button></div><div class="section-head"><div><div class="kicker">CHECKS</div><h2>Pre-ride checks</h2></div></div><div class="card" style="padding:12px">${[['tyres','Tyres','Pressure, condition, puncture kit'],['luggage','Luggage','Straps, balance, exhaust clearance'],['electronics','Electronics','Phone, maps, intercom, Action 5'],['pillion','Pillion essentials','Water, gear fit and rest plan']].map(x=>`<div class="checkrow"><div><strong>${x[1]}</strong><small>${x[2]}</small></div><button class="checkbtn ${state.ride.preflight[d.day+'_'+x[0]]?'on':''}" onclick="togglePreflight('${x[0]}')">✓</button></div>`).join('')}</div><div class="section-head"><div><div class="kicker">DAY TIMELINE</div><h2>Schedule</h2></div></div><div class="card" style="padding:14px"><div class="timeline">${d.tasks.map((x,i)=>taskRow(x,i)).join('')}</div></div>`}
function togglePreflight(k){snapshot('pre-ride check');const key=currentDay().day+'_'+k;state.ride.preflight[key]=!state.ride.preflight[key];save();renderRideMode()}
function openRideModeMapMenu(){const d=currentDay();openModal(`<div class="modalhead"><div><div class="kicker">DAY ${d.day} MAP</div><h3>Route parts</h3><p class="caption">Open each part in sequence so Maps keeps the intended anchors.</p></div><button class="round" onclick="closeModal()">×</button></div>${d.segments.map((s,i)=>`<div class="routecard"><div class="row between"><strong>${esc(s.label)}</strong><button class="secondary" onclick="openRoute(${i},false)">Open</button></div><p>${esc(s.origin)} → ${esc(s.destination)}</p></div>`).join('')}`)}

function weatherLabel(code){const c=Number(code);if(c===0)return'Clear';if([1,2,3].includes(c))return'Cloudy';if([45,48].includes(c))return'Fog';if([51,53,55,56,57].includes(c))return'Drizzle';if([61,63,65,66,67].includes(c))return'Rain';if([71,73,75,77].includes(c))return'Snow';if([80,81,82].includes(c))return'Showers';if([95,96,99].includes(c))return'Thunderstorm';return'Weather'}
async function renderWeather(force=false){const el=$('#weatherCard');if(!el)return;const cached=state.ride.weather&&state.ride.weatherUpdated;try{if(!force&&cached&&Date.now()-new Date(state.ride.weatherUpdated).getTime()<30*60*1000){paintWeather(el,state.ride.weather);return}if(force)el.innerHTML='<div class="weather-top"><div><div class="kicker">RIDE CONDITIONS</div><strong>Refreshing live weather…</strong></div><button class="secondary" disabled>Refreshing…</button></div>';const url='https://api.open-meteo.com/v1/forecast?latitude=23.55&longitude=74.45&current=temperature_2m,precipitation,rain,weather_code&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum&timezone=Asia%2FKolkata&forecast_days=16';const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error();const j=await r.json();state.ride.weather=j;state.ride.weatherUpdated=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));paintWeather(el,j);if(force)toast('Weather refreshed')}catch{if(cached){paintWeather(el,state.ride.weather,true);toast('Using cached weather')}else el.innerHTML='<div class="weather-top"><div><div class="kicker">RIDE CONDITIONS</div><strong>Weather unavailable</strong><div class="caption">Check internet and retry. Rider Hub will not invent live weather.</div></div><button class="secondary" onclick="renderWeather(true)">Retry</button></div>'}}
function paintWeather(el,j,stale=false){const cur=j.current||{},d=currentDay(),idx=(j.daily?.time||[]).indexOf(d.date),rain=idx>=0?j.daily.precipitation_probability_max[idx]:null,max=idx>=0?j.daily.temperature_2m_max[idx]:null,min=idx>=0?j.daily.temperature_2m_min[idx]:null;el.innerHTML=`<div class="weather-top"><div><div class="kicker">RIDE CONDITIONS · OPEN-METEO${stale?' · CACHED':''}</div><div class="weather-big">${Math.round(cur.temperature_2m??0)}°C</div><div class="weather-status">${weatherLabel(cur.weather_code)} · Banswara · updated ${new Date(state.ride.weatherUpdated).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</div></div><button class="secondary" onclick="renderWeather(true)">Refresh</button></div><div class="grid3" style="margin-top:10px"><div class="tile"><label>DAY ${d.day} RAIN RISK</label><b>${rain==null?'—':rain+'%'}</b></div><div class="tile"><label>EXPECTED HIGH</label><b>${max==null?'—':Math.round(max)+'°'}</b></div><div class="tile"><label>EXPECTED LOW</label><b>${min==null?'—':Math.round(min)+'°'}</b></div></div>${rain>=60?'<div class="alert red">High rain probability. Re-check roads before departure and use the wet-weather route if the Santrampur/Mangarh corridor is questionable.</div>':'<div class="alert">Forecasts can change materially. Re-check the evening before and again before departure.</div>'}`}

$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b)setPage(b.dataset.page)});
$('#importFile').addEventListener('change',e=>{if(e.target.files[0])importData(e.target.files[0])});
initHistory();render();scheduleAudit();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});