/* Rider Hub cross-device sync using the user's own Google Drive appDataFolder. No OAuth token or client secret is committed. */
(()=>{
const CFG='riderhub_cloud_sync_v1', MOD='riderhub_cloud_modified_v1', STATE_FILE='riderhub_state_v1.json';
let accessToken='', tokenExpiry=0, gisPromise=null, syncTimer=null, syncing=false;
const escHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function cfg(){try{return JSON.parse(localStorage.getItem(CFG)||'{}')}catch{return{}}}
function setCfg(v){localStorage.setItem(CFG,JSON.stringify({...cfg(),...v}))}
function connected(){return !!accessToken&&Date.now()<tokenExpiry-60000}
function markModified(){localStorage.setItem(MOD,String(Date.now()))}
function localModified(){return Number(localStorage.getItem(MOD)||0)}
function loadGIS(){if(window.google?.accounts?.oauth2)return Promise.resolve();if(gisPromise)return gisPromise;gisPromise=new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.onload=()=>res();s.onerror=()=>rej(new Error('Could not load Google sign-in'));document.head.appendChild(s)});return gisPromise}
async function api(url,opt={}){if(!connected())throw new Error('Cloud sync is not connected');const h=new Headers(opt.headers||{});h.set('Authorization','Bearer '+accessToken);const r=await fetch(url,{...opt,headers:h});if(r.status===401){accessToken='';tokenExpiry=0;throw new Error('Google session expired. Reconnect from My Account.')}if(!r.ok){const text=await r.text().catch(()=>''),msg=(()=>{try{return JSON.parse(text)?.error?.message||text}catch{return text}})();throw new Error(msg||('Google Drive error '+r.status))}return r}
function q(s){return encodeURIComponent(s)}
async function findByName(name){const r=await api(`https://www.googleapis.com/drive/v3/files?spaces=appDataFolder&q=${q(`name='${name}' and trashed=false`)}&orderBy=modifiedTime%20desc&fields=files(id,name,mimeType,modifiedTime,size)&pageSize=10`);const j=await r.json();return j.files?.[0]||null}
async function findDoc(key){const prefix=`riderhub_doc_${key}__`;const r=await api(`https://www.googleapis.com/drive/v3/files?spaces=appDataFolder&q=${q(`name contains '${prefix}' and trashed=false`)}&orderBy=modifiedTime%20desc&fields=files(id,name,mimeType,modifiedTime,size)&pageSize=10`);const j=await r.json();return j.files?.[0]||null}
async function uploadMultipart(name,blob,existingId=''){
 const boundary='rh_'+Math.random().toString(36).slice(2);const meta={name,mimeType:blob.type||'application/octet-stream'};if(!existingId)meta.parents=['appDataFolder'];
 const body=new Blob([`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(meta)}\r\n--${boundary}\r\nContent-Type: ${blob.type||'application/octet-stream'}\r\n\r\n`,blob,`\r\n--${boundary}--`],{type:`multipart/related; boundary=${boundary}`});
 const url=existingId?`https://www.googleapis.com/upload/drive/v3/files/${existingId}?uploadType=multipart&fields=id,name,modifiedTime`:'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,modifiedTime';
 const r=await api(url,{method:existingId?'PATCH':'POST',headers:{'Content-Type':`multipart/related; boundary=${boundary}`},body});return r.json()
}
async function uploadState(){if(!connected()||syncing)return;syncing=true;try{const existing=await findByName(STATE_FILE);const payload={schema:1,updatedAt:Math.max(localModified(),Date.now()),state};const blob=new Blob([JSON.stringify(payload)],{type:'application/json'});await uploadMultipart(STATE_FILE,blob,existing?.id||'');localStorage.setItem(MOD,String(payload.updatedAt));setCfg({lastSync:new Date().toISOString()})}finally{syncing=false}}
async function downloadState(){if(!connected())return false;const f=await findByName(STATE_FILE);if(!f)return false;const r=await api(`https://www.googleapis.com/drive/v3/files/${f.id}?alt=media`);const payload=await r.json();if(!payload?.state)return false;const remote=Number(payload.updatedAt||0),local=localModified();if(remote>local){try{state=merge(clone(base),payload.state);state.gear=restoreGear(state.gear);localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(MOD,String(remote));render();setCfg({lastSync:new Date().toISOString()});return true}catch{}}return false}
async function syncNow(){if(!connected())return requestDriveAccess(true);try{const pulled=await downloadState();if(!pulled)await uploadState();toast(pulled?'Synced newer data from Google Drive':'Rider Hub synced')}catch(e){toast(String(e.message||e).slice(0,90))}}
function schedule(){clearTimeout(syncTimer);if(!connected())return;syncTimer=setTimeout(()=>uploadState().catch(()=>{}),2500)}
async function profile(){try{const r=await api('https://www.googleapis.com/oauth2/v3/userinfo');const j=await r.json();setCfg({name:j.name||j.email||'',email:j.email||'',picture:j.picture||''});return j}catch{return null}}
async function requestDriveAccess(syncAfter=false){const c=cfg();if(!c.clientId){openCloudSetup();return}try{await loadGIS()}catch(e){toast(e.message);return}const client=google.accounts.oauth2.initTokenClient({client_id:c.clientId,scope:'openid email profile https://www.googleapis.com/auth/drive.appdata',prompt:'consent',callback:async r=>{if(r.error){toast('Google connection was not completed');return}accessToken=r.access_token;tokenExpiry=Date.now()+(Number(r.expires_in||3600)*1000);await profile();setCfg({connectedAt:new Date().toISOString()});try{const pulled=await downloadState();if(!pulled)await uploadState();toast('Google Drive sync connected')}catch(e){toast(String(e.message||e).slice(0,90))}if(syncAfter)setTimeout(()=>syncNow(),150);if(typeof renderMore==='function'&&state.ui.page==='more')renderMore()}});client.requestAccessToken()}
function disconnect(){accessToken='';tokenExpiry=0;setCfg({email:'',name:'',picture:'',connectedAt:''});toast('Cloud sync disconnected');if(typeof renderMore==='function'&&state.ui.page==='more')renderMore()}
function cloudLabel(){const c=cfg();return connected()?(c.email||'Connected'):c.clientId?'Reconnect needed':'Not connected'}
function openCloudSetup(){const c=cfg();openModal(`<div class="modalhead"><div><div class="kicker">CLOUD SYNC</div><h3>Google Drive sync</h3><p class="caption">Keep Rider Hub data and private files available on your phone and PC.</p></div><button class="round" onclick="closeModal()">×</button></div><div class="routecard"><strong>Status</strong><p>${escHtml(cloudLabel())}${c.lastSync?` · Last sync ${new Date(c.lastSync).toLocaleString()}`:''}</p></div><div class="field"><label>GOOGLE WEB CLIENT ID</label><input id="rhGoogleClientId" value="${escHtml(c.clientId||'')}" placeholder="xxxxxxxx.apps.googleusercontent.com"></div><div class="modal-actions"><button class="secondary" onclick="saveCloudClientId()">Save ID</button><button class="confirm" onclick="requestDriveAccess(true)">${connected()?'Sync now':'Connect Google'}</button></div>${c.clientId?'<button class="secondary full" style="margin-top:8px" onclick="disconnectRiderHubCloud()">Disconnect</button>':''}`)}
function saveClientId(){const v=document.querySelector('#rhGoogleClientId')?.value.trim();if(!v)return toast('Add the Google Web Client ID');setCfg({clientId:v});toast('Client ID saved');openCloudSetup()}
function docCloudName(key,file){return`riderhub_doc_${String(key).replace(/[^a-z0-9_-]/gi,'_')}__${file.name.replace(/[\\/]/g,'_')}`}
async function uploadDoc(key,file){if(!connected())return false;const existing=await findDoc(key);await uploadMultipart(docCloudName(key,file),file,existing?.id||'');setCfg({lastSync:new Date().toISOString()});return true}
async function downloadDoc(key){if(!connected())return null;const f=await findDoc(key);if(!f)return null;const r=await api(`https://www.googleapis.com/drive/v3/files/${f.id}?alt=media`);const b=await r.blob();const marker='__',name=f.name.includes(marker)?f.name.split(marker).slice(1).join(marker):f.name;return new File([b],name,{type:f.mimeType||b.type||'application/octet-stream',lastModified:Date.now()})}
async function deleteDoc(key){if(!connected())return false;const f=await findDoc(key);if(!f)return false;await api(`https://www.googleapis.com/drive/v3/files/${f.id}`,{method:'DELETE'});return true}
window.cloudSyncConnected=connected;window.cloudSyncLabel=cloudLabel;window.openCloudSetup=openCloudSetup;window.saveCloudClientId=saveClientId;window.requestDriveAccess=requestDriveAccess;window.disconnectRiderHubCloud=disconnect;window.riderHubSyncNow=syncNow;window.riderHubUploadDoc=uploadDoc;window.riderHubDownloadDoc=downloadDoc;window.riderHubDeleteDoc=deleteDoc;window.riderHubCloudConfig=cfg;
const baseSave=window.save;if(typeof baseSave==='function'){window.save=function(){markModified();const out=baseSave.apply(this,arguments);schedule();return out}}
const baseSaveDoc=window.savePrivateDoc;if(typeof baseSaveDoc==='function'){window.savePrivateDoc=async function(key,file){const r=await baseSaveDoc(key,file);if(connected()){try{await uploadDoc(key,file);toast('Saved and synced')}catch(e){toast('Saved on device · cloud sync pending')}}return r}}
const baseGetDoc=window.getPrivateDoc;if(typeof baseGetDoc==='function'){window.getPrivateDoc=async function(key){let f=await baseGetDoc(key);if(f)return f;if(connected()){try{f=await downloadDoc(key);if(f){await baseSaveDoc(key,f);return f}}catch{}}return null}}
const baseDeleteDoc=window.deletePrivateDoc;if(typeof baseDeleteDoc==='function'){window.deletePrivateDoc=async function(key){const r=await baseDeleteDoc(key);if(connected()){try{await deleteDoc(key)}catch{}}return r}}
})();