/* Rider Hub public/multi-user workspace layer.
   Existing legacy Rider Hub data is preserved exactly. New accounts receive a clean workspace. */
(()=>{
const ACTIVE='riderhub_public_active_uid_v1';
const USER_PREFIX='riderhub_public_state_v1_';
const PUBLIC_DOCS=[
 ['vehicle_invoice','Vehicle invoice','Purchase invoice / receipt'],
 ['vehicle_tax','Vehicle tax','Road / lifetime tax record'],
 ['insurance','Insurance','Motor insurance policy'],
 ['licence','Rider licence','Driving / learner licence'],
 ['service_invoice','Service invoice','Workshop or service bill'],
 ['hotelBooking','Trip / hotel booking','Ride booking or travel document']
];
const legacy={home:window.renderHome,bike:window.renderBike,rides:window.renderRides,gear:window.renderGear,addRide:window.openSimpleRideAdd};
const escP=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const userKey=uid=>USER_PREFIX+encodeURIComponent(String(uid||'guest'));
const activeUid=()=>localStorage.getItem(ACTIVE)||'';
const isPublic=()=>!!state?.profile?.publicUser;

function blankRide(){const r=clone(base.ride);r.selectedDay=0;r.budgetMax=0;r.expenses={hotel:0,fuel:0,food:0,parking:0,misc:0};r.fuelLogs=[];r.notes='';r.issues=[];r.tasks={};r.preflight={};r.customEmergency=[];r.packing={};r.content={};r.backup={};return r}
function cleanState(account={}){const s=clone(base);s.profile={publicUser:true,version:1,bikeConfigured:false,account:{uid:account.uid||'',email:account.email||'',name:account.name||'',provider:account.provider||'email'}};s.bike={name:'My Motorcycle',manufacturer:'',model:'',trim:'Set up your motorcycle',variant:'',colour:'',year:new Date().getFullYear(),odo:0,purchase:'Not added',firstService:{odo:0,date:'Not added',cost:0},nextServiceKm:0,nextServiceDate:'Not added',chainLast:0,braking:'Not added',engine:'Not added',fuelTank:'Not added',transmission:'Not added',tyres:'Not added',insurance:'Not added',serviceHistory:[]};s.ride=blankRide();s.gear=[];s.customRides=[];s.ui={page:'home',rideView:'list'};return s}
function persistPublic(){if(!isPublic())return;const uid=state.profile?.account?.uid||activeUid();if(uid)localStorage.setItem(userKey(uid),JSON.stringify(state))}
function activate(account={}){const uid=String(account.uid||account.email||'').trim();if(!uid)return false;const old=activeUid();if(old&&isPublic())persistPublic();let next=null;try{next=JSON.parse(localStorage.getItem(userKey(uid))||'null')}catch{}if(!next?.profile?.publicUser)next=cleanState({...account,uid});next.profile.account={...(next.profile.account||{}),...account,uid};state=merge(clone(base),next);state.gear=Array.isArray(next.gear)?next.gear:[];state.customRides=Array.isArray(next.customRides)?next.customRides:[];localStorage.setItem(ACTIVE,uid);localStorage.setItem(KEY,JSON.stringify(state));try{render()}catch{}return true}
window.riderHubActivatePublicUser=activate;
window.riderHubExportState=()=>clone(state);
window.riderHubImportState=function(remote){if(!remote||typeof remote!=='object')return false;const acct=state?.profile?.account||{};state=merge(clone(base),remote);if(remote.profile?.publicUser){state.profile=remote.profile;state.profile.account={...(remote.profile.account||{}),...acct};state.gear=Array.isArray(remote.gear)?remote.gear:[];state.customRides=Array.isArray(remote.customRides)?remote.customRides:[]}localStorage.setItem(KEY,JSON.stringify(state));persistPublic();render();return true};
window.riderHubPrepareNewCloudUser=function(){const c=typeof riderHubCloudConfig==='function'?riderHubCloudConfig():{};const email=c.email||'';if(!email)return;activate({uid:'google:'+email.toLowerCase(),email,name:c.name||email,provider:'google'});};
window.riderHubPublicBeforeLogout=function(){persistPublic();localStorage.removeItem(ACTIVE)};

const priorSave=window.save;if(typeof priorSave==='function')window.save=function(){const out=priorSave.apply(this,arguments);persistPublic();if(typeof window.riderHubFirebaseQueueSync==='function'&&isPublic())window.riderHubFirebaseQueueSync();return out};

function publicHome(){const p=state.profile||{},b=state.bike||{};$('#home').innerHTML=`<div class="card hero"><div class="kicker">RIDER HUB</div><h1>Your motorcycle OS.<br><span>Built around your bike and rides.</span></h1><div class="bikeplate" onclick="setPage('bike')"><div class="row between"><div><strong>${escP(p.bikeConfigured?b.name:'Set up your motorcycle')}</strong><div class="caption">${escP(p.bikeConfigured?b.trim:'Add your bike details to get started')}</div></div><span class="pill ${p.bikeConfigured?'good':'soon'}">${p.bikeConfigured?'READY':'SETUP'}</span></div>${p.bikeConfigured?`<div class="metrics"><div class="metric"><label>ODOMETER</label><b>${Number(b.odo||0).toLocaleString('en-IN')} km</b></div><div class="metric"><label>NEXT SERVICE</label><b class="ember">${b.nextServiceKm?Number(b.nextServiceKm).toLocaleString('en-IN')+' km':'Not set'}</b></div></div>`:''}</div></div><div class="section-head"><div><div class="kicker">QUICK ACCESS</div><h2>Rider controls</h2></div></div><div class="quickgrid"><button class="quick" onclick="setPage('rides')"><b>↗</b><span>My rides</span></button><button class="quick" onclick="setPage('bike')"><b>◇</b><span>My bike</span></button><button class="quick" onclick="setPage('gear')"><b>▣</b><span>My gear</span></button><button class="quick" onclick="openNotifications()"><b>!</b><span>Alerts</span></button></div><div class="section-head"><div><div class="kicker">ACCOUNT</div><h2>${escP(p.account?.name||p.account?.email||'Rider')}</h2></div></div><div class="card attention"><strong>Private workspace</strong><div class="caption" style="margin-top:5px">Your bike, rides and gear are separate from other Rider Hub accounts on this device.</div></div>`}

window.openPublicBikeSetup=function(){const b=state.bike||{};openModal(`<div class="modalhead"><div><div class="kicker">MY MOTORCYCLE</div><h3>${state.profile?.bikeConfigured?'Edit motorcycle':'Set up motorcycle'}</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="grid2"><div class="field"><label>MANUFACTURER</label><input id="pubBikeMake" value="${escP(b.manufacturer||'')}" placeholder="TVS, Honda, KTM..."></div><div class="field"><label>MODEL</label><input id="pubBikeModel" value="${escP(b.model||'')}" placeholder="Motorcycle model"></div></div><div class="grid2"><div class="field"><label>VARIANT</label><input id="pubBikeVariant" value="${escP(b.variant||'')}"></div><div class="field"><label>COLOUR</label><input id="pubBikeColour" value="${escP(b.colour||'')}"></div></div><div class="grid2"><div class="field"><label>YEAR</label><input id="pubBikeYear" inputmode="numeric" value="${escP(b.year||new Date().getFullYear())}"></div><div class="field"><label>ODOMETER KM</label><input id="pubBikeOdo" inputmode="numeric" value="${Number(b.odo||0)}"></div></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="confirm" onclick="savePublicBikeSetup()">✓ Save bike</button></div>`)};
window.savePublicBikeSetup=function(){const make=$('#pubBikeMake')?.value.trim(),model=$('#pubBikeModel')?.value.trim();if(!make||!model)return toast('Add manufacturer and model');snapshot('bike setup');const year=Math.round(Number($('#pubBikeYear')?.value||new Date().getFullYear())),odo=Math.max(0,Math.round(Number($('#pubBikeOdo')?.value||0)));state.bike={...state.bike,manufacturer:make,model,name:`${make} ${model}`,variant:$('#pubBikeVariant')?.value.trim()||'',colour:$('#pubBikeColour')?.value.trim()||'',year,odo,chainLast:odo,trim:[ $('#pubBikeVariant')?.value.trim(),$('#pubBikeColour')?.value.trim(),year].filter(Boolean).join(' • '),purchase:state.bike.purchase||'Not added'};state.profile.bikeConfigured=true;save();closeModal();renderBike();toast('Motorcycle saved')};

function publicDocsHtml(){return `<div class="section-head"><div><div class="kicker">DOCUMENTS</div><h2>Document vault</h2></div></div><div class="card list">${PUBLIC_DOCS.map(d=>`<div class="listrow" onclick="openPublicDoc('${d[0]}')" style="cursor:pointer"><div class="ico">▤</div><div><strong>${d[1]}</strong><p>${d[2]}</p></div><span class="pill good">PRIVATE</span></div>`).join('')}</div><div class="section-head"><div><div class="kicker">DIGILOCKER</div><h2>Verified documents</h2></div></div><div class="card coming-card"><strong>COMING SOON</strong></div>`}
window.openPublicDoc=function(id){const d=PUBLIC_DOCS.find(x=>x[0]===id);if(!d)return;openModal(`<div class="modalhead"><div><div class="kicker">DOCUMENT</div><h3>${d[1]}</h3><p class="caption">${d[2]}</p></div><button class="round" onclick="closeModal()">×</button></div><div class="grid2"><button class="secondary" onclick="openPrivateDoc('${id}')">Open file</button><button class="primary" onclick="openPrivateDocPicker('${id}')">Attach / replace</button></div><div class="caption" style="margin-top:10px">Files stay local unless this account connects Google Drive sync.</div>`)};
function publicBike(){const b=state.bike,p=state.profile;if(!p.bikeConfigured){$('#bike').innerHTML=`<div class="card bike-hero"><div class="kicker">MY MOTORCYCLE</div><h1>Add your bike</h1><p>Set up the motorcycle this Rider Hub account belongs to.</p><button class="primary" style="margin-top:14px" onclick="openPublicBikeSetup()">Set up motorcycle</button></div>${publicDocsHtml()}`;return}$('#bike').innerHTML=`<div class="card bike-hero"><div class="kicker">MY MOTORCYCLE</div><h1>${escP(b.name)}</h1><p>${escP(b.trim||'')}</p><div class="metrics"><div class="metric"><label>MASTER ODOMETER</label><b>${Number(b.odo||0).toLocaleString('en-IN')} km</b></div><div class="metric"><label>YEAR</label><b>${escP(b.year||'—')}</b></div></div></div><div class="section-head"><div><div class="kicker">OVERVIEW</div><h2>Bike information</h2></div><button class="secondary" onclick="openPublicBikeSetup()">Edit bike</button></div><div class="bike-info-grid">${[['Manufacturer',b.manufacturer],['Model',b.model],['Variant',b.variant||'—'],['Colour',b.colour||'—'],['Year',b.year||'—'],['Engine',b.engine||'Not added'],['Braking',b.braking||'Not added'],['Transmission',b.transmission||'Not added'],['Fuel tank',b.fuelTank||'Not added'],['Tyres',b.tyres||'Not added'],['Insurance',b.insurance||'Not added']].map(x=>`<div class="info"><label>${String(x[0]).toUpperCase()}</label><b>${escP(x[1])}</b></div>`).join('')}</div><div class="section-head"><div><div class="kicker">MAINTENANCE</div><h2>Maintenance</h2></div></div><div class="card list"><div class="listrow"><div class="ico">⛓</div><div><strong>Chain / final drive</strong><p>Add care intervals according to your motorcycle manual.</p></div><span class="pill good">TRACK</span></div><div class="listrow"><div class="ico">🔧</div><div><strong>Service schedule</strong><p>${b.nextServiceKm?`Next target ${Number(b.nextServiceKm).toLocaleString('en-IN')} km`:'Add the next service target when known.'}</p></div><span class="pill soon">SETUP</span></div><div class="listrow"><div class="ico">🛞</div><div><strong>Tyres</strong><p>Check pressure and condition before long rides.</p></div><span class="pill good">CHECK</span></div></div><div class="section-head"><div><div class="kicker">SERVICE HISTORY</div><h2>Completed work</h2></div></div><div class="card list">${(b.serviceHistory||[]).length?(b.serviceHistory||[]).map(x=>`<div class="listrow"><div class="ico">✓</div><div><strong>${escP(x.name)}</strong><p>${escP(x.date)} · ${Number(x.odo||0).toLocaleString('en-IN')} km</p></div></div>`).join(''):'<div class="listrow"><div class="ico">＋</div><div><strong>No service records yet</strong><p>Add them as you maintain the bike.</p></div></div>'}</div>${publicDocsHtml()}`}

window.openSimpleRideAdd=function(){if(!isPublic()&&legacy.addRide)return legacy.addRide();openModal(`<div class="modalhead"><div><div class="kicker">ADD RIDE</div><h3>New ride</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="field"><label>RIDE NAME</label><input id="newRideName" placeholder="Weekend ride"></div><div class="field"><label>ROUTE</label><input id="newRideRoute" placeholder="Start → destination"></div><div class="grid2"><div class="field"><label>START</label><input id="newRideStart" type="date"></div><div class="field"><label>END</label><input id="newRideEnd" type="date"></div></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="confirm" onclick="saveSimpleRide()">✓ Add ride</button></div>`)};
function publicRides(){const custom=state.customRides||[];$('#rides').innerHTML=`<div class="section-head ride-list-head"><div><div class="kicker">MY RIDES</div><h2>Plan. Ride. Remember.</h2></div><button class="add-ride-btn" onclick="openSimpleRideAdd()">+ Add ride</button></div><div class="ride-summary"><div class="card stat"><label>PLANNED</label><b>${custom.length}</b><small>rides</small></div><div class="card stat"><label>COMPLETED</label><b>0</b><small>rides</small></div><div class="card stat"><label>TOURING</label><b>0</b><small>km logged</small></div></div><div style="margin-top:12px">${custom.length?custom.map(r=>`<div class="card ride-card" onclick="openCustomRide('${r.id}')"><div class="ride-card-top"><div><div class="kicker">PLANNED</div><h3>${escP(r.name)}</h3><div class="ride-route">${escP(r.route||'Route not added')}</div></div><span class="ride-status">UPCOMING</span></div><div class="ride-meta"><span>${escP(r.start||'Date TBD')}${r.end&&r.end!==r.start?' → '+escP(r.end):''}</span></div></div>`).join(''):`<div class="card" style="padding:20px"><strong>No rides yet</strong><p class="caption">Add your first ride when you are ready.</p><button class="primary" style="margin-top:12px" onclick="openSimpleRideAdd()">+ Add ride</button></div>`}</div>`}

window.addPublicGear=function(){openModal(`<div class="modalhead"><div><div class="kicker">GEAR</div><h3>Add gear</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="field"><label>ITEM</label><input id="pubGearName" placeholder="Helmet, jacket, luggage..."></div><div class="field"><label>CATEGORY</label><input id="pubGearCategory" placeholder="Riding gear"></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="confirm" onclick="savePublicGear()">✓ Add</button></div>`)};
window.savePublicGear=function(){const name=$('#pubGearName')?.value.trim();if(!name)return toast('Add an item name');snapshot('add gear');state.gear.push({id:'gear_'+Date.now().toString(36),name,category:$('#pubGearCategory')?.value.trim()||'Gear',owner:'Me',status:'owned',amount:null,qty:1,note:''});save();closeModal();renderGear();toast('Gear added')};
function publicGear(){const g=state.gear||[];$('#gear').innerHTML=`<div class="card gear-hero"><div class="kicker">MY GEAR</div><h1>Garage</h1><p>Riding gear, luggage, electronics, bike setup and care items.</p><button class="primary" style="margin-top:12px" onclick="addPublicGear()">+ Add gear</button></div><div class="section-head"><div><div class="kicker">OWNED</div><h2>${g.length} item${g.length===1?'':'s'}</h2></div></div><div class="card list">${g.length?g.map(x=>`<div class="listrow"><div class="ico">◇</div><div><strong>${escP(x.name)}</strong><p>${escP(x.category||'Gear')}</p></div><span class="pill good">OWNED</span></div>`).join(''):'<div class="listrow"><div class="ico">＋</div><div><strong>No gear added yet</strong><p>Build your garage as you go.</p></div></div>'}</div>`}

window.renderHome=function(){return isPublic()?publicHome():legacy.home?.()};
window.renderBike=function(){return isPublic()?publicBike():legacy.bike?.()};
window.renderRides=function(){return isPublic()?publicRides():legacy.rides?.()};
window.renderGear=function(){return isPublic()?publicGear():legacy.gear?.()};

setTimeout(()=>{if(isPublic())try{render()}catch{}},150);
})();
