/* Rider Hub generic Ride Mode v2.
   Manual rides and imported PDF itineraries use the same operational workspace. */
(()=>{
'use strict';
const legacyOpenRideMode=window.openRideMode;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const S=()=>window.state||{};
const rides=()=>{const s=S();s.customRides=Array.isArray(s.customRides)?s.customRides:[];return s.customRides};
const ui=()=>{const s=S();s.ui=s.ui||{};return s.ui};
const save=()=>window.save?.();
const modal=html=>window.openModal?.(html);
const toast=t=>window.toast?.(t);
const nowId=()=>`ride_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,6)}`;
const legacyAvailable=()=>Number(S().ride?.budgetMax||0)>0||!!S().ride?.backup?.booking;
const legacyId='legacy_banswara_preview';
const defaultChecks=['Tyres & brakes','Luggage secure','Phone / navigation','Documents','Water / hydration','Pillion gear'];
const defaultPacking=['Rain layer','First-aid kit','Puncture kit','Tools','Power bank / cables','Documents','Water','Spare layer'];
const defaultContent=['Departure','Road / landscape','Key stop','Food / break','Arrival'];
const defaultMedia=['Action camera','Phone photos','Important clips','Daily backup'];

function normalizeTask(t){return{time:String(t?.time||''),title:String(t?.title||t?.name||'Task'),note:String(t?.note||''),status:['done','skipped','delayed'].includes(t?.status)?t.status:'upcoming',delay:Number(t?.delay||0)}}
function normalizeDay(d,i){return{day:Number(d?.day||i+1),date:String(d?.date||''),title:String(d?.title||`Day ${i+1}`),from:String(d?.from||''),to:String(d?.to||''),route:String(d?.route||''),tasks:Array.isArray(d?.tasks)?d.tasks.map(normalizeTask):[],notes:Array.isArray(d?.notes)?d.notes:[]}}
function normalizeRide(r){
  if(!r)return null;
  r.id=r.id||nowId();r.name=r.name||'Untitled ride';r.route=r.route||'';r.start=r.start||'';r.end=r.end||r.start||'';
  r.days=Array.isArray(r.days)&&r.days.length?r.days.map(normalizeDay):[normalizeDay({date:r.start,title:'Day 1',route:r.route,from:String(r.route).split('→')[0]?.trim()||'',to:String(r.route).split('→').pop()?.trim()||''},0)];
  r.selectedDay=Math.max(0,Math.min(r.days.length-1,Number(r.selectedDay||0)));r.notes=String(r.notes||'');r.issues=Array.isArray(r.issues)?r.issues:[];
  r.expenses=r.expenses&&typeof r.expenses==='object'?r.expenses:{fuel:0,food:0,stay:0,tolls:0,misc:0};r.budgetMax=Number(r.budgetMax||0);r.fuelLogs=Array.isArray(r.fuelLogs)?r.fuelLogs:[];
  r.preflight=r.preflight&&typeof r.preflight==='object'?r.preflight:{};r.packing=r.packing&&typeof r.packing==='object'?r.packing:{};r.content=r.content&&typeof r.content==='object'?r.content:{};r.media=r.media&&typeof r.media==='object'?r.media:{};
  r.lodging=Array.isArray(r.lodging)?r.lodging:[];r.warnings=Array.isArray(r.warnings)?r.warnings:[];r.completed=!!r.completed;return r;
}
function getRide(id=ui().activeRideId){return normalizeRide(rides().find(x=>x.id===id))}
function activeRide(){return getRide()}
function day(r=activeRide()){return r?.days?.[r.selectedDay||0]||null}
function progress(d){if(!d?.tasks?.length)return 0;return Math.round(d.tasks.filter(t=>['done','skipped'].includes(t.status)).length/d.tasks.length*100)}
function totalProgress(r){const all=(r?.days||[]).flatMap(d=>d.tasks||[]);if(!all.length)return 0;return Math.round(all.filter(t=>['done','skipped'].includes(t.status)).length/all.length*100)}
function nextTask(d){return(d?.tasks||[]).find(t=>!['done','skipped'].includes(t.status))||null}
function destination(r,d=day(r)){const route=d?.route||r?.route||'';const parts=route.split(/[→➜➡]|\s+-\s+|\s+to\s+/i).map(x=>x.trim()).filter(Boolean);return d?.to||parts[parts.length-1]||''}
function persistRide(r){const list=rides(),i=list.findIndex(x=>x.id===r.id);if(i>=0)list[i]=r;save()}

function listHtml(){
  const custom=rides().map(normalizeRide),legacy=legacyAvailable(),planned=custom.filter(r=>!r.completed).length+(legacy?1:0),completed=custom.filter(r=>r.completed).length,touring=custom.reduce((a,r)=>a+Number(r.distanceKm||0),0);
  const cards=[];
  if(legacy)cards.push(`<div class="card ride-card rh-ride-v2-card" onclick="rhOpenRide('${legacyId}')"><div class="ride-card-top"><div><div class="kicker">PREVIEW RIDE</div><h3>Banswara 3-Day Ronin Adventure</h3><div class="ride-route">Ahmedabad → Banswara → Ahmedabad</div></div><span class="ride-status">READY</span></div><div class="ride-meta"><span>3 days</span><span>Full Ride Mode</span></div></div>`);
  for(const r of custom)cards.push(`<div class="card ride-card rh-ride-v2-card" onclick="rhOpenRide('${esc(r.id)}')"><div class="ride-card-top"><div><div class="kicker">${r.source==='pdf'?'PDF IMPORT':r.completed?'COMPLETED':'PLANNED'}</div><h3>${esc(r.name)}</h3><div class="ride-route">${esc(r.route||'Route not added')}</div></div><span class="ride-status">${r.completed?'COMPLETED':'UPCOMING'}</span></div><div class="ride-meta"><span>${esc(r.start||'Date TBD')}${r.end&&r.end!==r.start?' → '+esc(r.end):''}</span><span>${r.days.length} day${r.days.length===1?'':'s'}</span><span>${totalProgress(r)}% done</span></div><div class="ride-progress"><i style="width:${totalProgress(r)}%"></i></div></div>`);
  return `<div class="section-head ride-list-head"><div><div class="kicker">MY RIDES</div><h2>Plan. Ride. Remember.</h2></div></div><div class="ride-summary"><div class="card stat"><label>PLANNED</label><b>${planned}</b><small>rides</small></div><div class="card stat"><label>COMPLETED</label><b>${completed}</b><small>rides</small></div><div class="card stat"><label>TOURING</label><b>${touring.toLocaleString('en-IN')}</b><small>km logged</small></div></div><div class="rh-rides-list">${cards.join('')||'<div class="card rh-ride-empty"><strong>No rides yet</strong><p>Build a ride manually or import an itinerary PDF.</p></div>'}</div><button class="primary full rh-add-ride-bottom" onclick="openRideCreateChoice()">+ Add ride</button>`;
}
function legacyDetail(){return `<button class="ride-list-back" onclick="rhBackToRideList()">‹ My rides</button><div class="card ride-hero"><div class="kicker">PREVIEW RIDE</div><h1>Banswara 3-Day Ronin Adventure</h1><p>Ahmedabad → Banswara → Ahmedabad · Full operational Ride Mode</p><button class="primary full" style="margin-top:14px" onclick="rhOpenLegacyRideMode()">Open Ride Mode</button></div><div class="routecard"><strong>Your original preview workflow is preserved.</strong><p>Day timeline, Done / Delay / Skip, packing, expenses, fuel, emergency tools, maps, media backup, tomorrow preparation and ride summary remain available in the original Ride Mode.</p></div>`}
function taskRows(r,d){return(d.tasks||[]).map((t,i)=>`<div class="task ${esc(t.status)}"><time>${esc(t.time||'—')}</time><div><strong>${esc(t.title)}</strong><p>${esc(t.note||'')}${t.delay?` · delayed ${Number(t.delay)} min`:''}</p></div><button onclick="rhRideTaskActions('${esc(r.id)}',${r.selectedDay},${i})">${esc(t.status.toUpperCase())}</button></div>`).join('')||'<div class="caption">No tasks yet. Add the first task for this day.</div>'}
function detailHtml(r){
  const d=day(r),p=progress(d),pdf=!!r.sourceFileKey;
  return `<button class="ride-list-back" onclick="rhBackToRideList()">‹ My rides</button><div class="card ride-hero"><div class="kicker">${r.source==='pdf'?'PDF RIDE PLAN':'MY RIDE'}</div><h1>${esc(r.name)}</h1><p>${esc(r.route||'Route not added')} · ${esc(r.start||'Date TBD')}${r.end&&r.end!==r.start?' → '+esc(r.end):''}</p><div class="ride-mode-cta"><button class="primary" onclick="openRideMode()">Open Ride Mode · Day ${Number(d?.day||1)}</button><div class="countdown"><div class="kicker">PROGRESS</div><b>${p}%</b></div></div>${pdf?`<button class="secondary full" onclick="rhOpenRideSourcePdf('${esc(r.id)}')">Open imported ride PDF</button>`:''}</div><div id="rhRideWeatherCard" class="card weather"><div class="kicker">LIVE WEATHER</div><strong>Loading destination weather…</strong></div>${r.lodging.length?`<div class="card booking" style="margin-top:10px"><div class="kicker">STAY / BOOKING</div>${r.lodging.slice(0,4).map(x=>`<p>${esc(x)}</p>`).join('')}</div>`:''}<div class="section-head"><div><div class="kicker">CHOOSE DAY</div><h2>Ride plan</h2></div><button class="secondary" onclick="rhAddRideTask('${esc(r.id)}')">+ Task</button></div><div class="daytabs">${r.days.map((x,i)=>`<button class="daytab ${i===r.selectedDay?'active':''}" onclick="rhSelectRideDay('${esc(r.id)}',${i})">Day ${Number(x.day||i+1)}${x.date?' · '+esc(x.date):''}</button>`).join('')}</div><div class="card" style="padding:14px;margin-top:8px"><div class="row between"><div><div class="kicker">DAY ${Number(d?.day||1)}</div><strong>${esc(d?.title||'Ride day')}</strong></div><span class="pill soon">${p}% DONE</span></div><div class="progress" style="margin:12px 0"><i style="width:${p}%"></i></div><div class="timeline">${taskRows(r,d)}</div></div><div class="section-head"><div><div class="kicker">TRIP TOOLKIT</div><h2>Ride operations</h2></div></div><div class="toolgrid ride-toolkit">${[['⌖','Map',`rhRideMap('${r.id}')`],['₹','Expenses',`rhRideExpenses('${r.id}')`],['⛽','Fuel',`rhRideFuel('${r.id}')`],['📝','Notes',`rhRideNotes('${r.id}')`],['⚠','Bike issue',`rhRideIssue('${r.id}')`],['▣','Packing',`rhRideChecklist('${r.id}','packing')`],['◉','Content',`rhRideChecklist('${r.id}','content')`],['☁','Media backup',`rhRideChecklist('${r.id}','media')`],['→','Tomorrow',`rhRideTomorrow('${r.id}')`],['SOS','Emergency','openEmergency()'],['↕','Traffic',`rhRideTraffic('${r.id}')`],['Σ','Summary',`rhRideSummary('${r.id}')`]].map(x=>`<button class="tool" onclick="${x[2]}"><b>${x[0]}</b><span>${x[1]}</span></button>`).join('')}</div>`;
}

window.renderRides=function(){const root=document.querySelector('#rides');if(!root)return;const id=ui().activeRideId;if(ui().rideView==='detail'&&id)root.innerHTML=id===legacyId?legacyDetail():detailHtml(getRide(id));else root.innerHTML=listHtml();if(ui().rideView==='detail'&&id!==legacyId)setTimeout(()=>rhLoadRideWeather(id),0)};
window.rhOpenRide=function(id){ui().activeRideId=id;ui().rideView='detail';save();window.renderRides();window.scrollTo(0,0)};
window.rhBackToRideList=function(){ui().rideView='list';ui().activeRideId='';save();window.renderRides();window.scrollTo(0,0)};
window.rhOpenLegacyRideMode=function(){if(typeof legacyOpenRideMode==='function')legacyOpenRideMode()};
window.openSimpleRideAdd=()=>window.openRideCreateChoice();
window.openRideCreateChoice=function(){modal(`<div class="modalhead"><div><div class="kicker">ADD RIDE</div><h3>How do you want to build it?</h3><p class="caption">Both options create the same full Ride Mode.</p></div><button class="round" onclick="closeModal()">×</button></div><div class="rh-ride-create-choice"><button class="rh-choice-card" onclick="openManualRideAdd()"><b>＋</b><strong>Create manually</strong><span>Add dates, route and itinerary yourself.</span></button><button class="rh-choice-card" onclick="openRidePdfImport()"><b>PDF</b><strong>Import ride from PDF</strong><span>Rider Hub reads the itinerary, then you review it before saving.</span></button></div>`)};
window.openManualRideAdd=function(){modal(`<div class="modalhead"><div><div class="kicker">MANUAL RIDE</div><h3>Create ride</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="field"><label>RIDE NAME</label><input id="rhRideName" placeholder="Weekend ride"></div><div class="field"><label>ROUTE</label><input id="rhRideRoute" placeholder="Ahmedabad → Udaipur"></div><div class="grid2"><div class="field"><label>START</label><input id="rhRideStart" type="date"></div><div class="field"><label>END</label><input id="rhRideEnd" type="date"></div></div><div class="field"><label>ITINERARY · OPTIONAL</label><textarea id="rhRideItinerary" placeholder="Day 1\n06:00 Depart home\n08:30 Breakfast stop\nAhmedabad → Udaipur"></textarea></div><button class="primary full" style="margin-top:12px" onclick="rhSaveManualRide()">Create ride</button>`)};
window.rhSaveManualRide=function(){const name=document.querySelector('#rhRideName')?.value.trim();if(!name)return toast('Add a ride name');const route=document.querySelector('#rhRideRoute')?.value.trim()||'',start=document.querySelector('#rhRideStart')?.value||'',end=document.querySelector('#rhRideEnd')?.value||start,it=document.querySelector('#rhRideItinerary')?.value||'';let parsed=typeof window.riderHubParseRideText==='function'?window.riderHubParseRideText(`${name}\n${it}`,{fileName:''}):{days:[]};const r=normalizeRide({id:nowId(),name,route,start,end,days:parsed.days,source:'manual',lodging:parsed.lodging||[],warnings:parsed.warnings||[]});if(route&&!r.days[0].route){r.days[0].route=route;const p=route.split('→');r.days[0].from=p[0]?.trim()||'';r.days[0].to=p[p.length-1]?.trim()||''}rides().push(r);save();window.closeModal?.();window.rhOpenRide(r.id);toast('Ride created')};

window.openRidePdfImport=function(){modal(`<div class="modalhead"><div><div class="kicker">IMPORT RIDE</div><h3>Ride plan PDF</h3><p class="caption">The PDF is read on your device. Rider Hub extracts what it can and shows a review before saving.</p></div><button class="round" onclick="closeModal()">×</button></div><input id="rhRidePdfFile" type="file" accept="application/pdf,.pdf" hidden onchange="document.querySelector('#rhRidePdfName').textContent=this.files?.[0]?.name||'No PDF selected'"><button class="secondary full" onclick="document.querySelector('#rhRidePdfFile').click()">Choose ride-plan PDF</button><div id="rhRidePdfName" class="caption" style="margin-top:8px">No PDF selected</div><div class="routecard"><strong>What Rider Hub looks for</strong><p>Ride title · dates · day headings · times · stops · route lines · hotel / stay details. Missing information stays editable.</p></div><button id="rhRidePdfRead" class="primary full" onclick="rhReadRidePdf()">Read PDF</button>`)};
window.rhReadRidePdf=async function(){const file=document.querySelector('#rhRidePdfFile')?.files?.[0],btn=document.querySelector('#rhRidePdfRead');if(!file)return toast('Choose a ride-plan PDF');if(typeof window.riderHubProcessRidePdf!=='function')return toast('PDF ride importer is not ready');if(btn){btn.disabled=true;btn.textContent='Reading itinerary…'}try{const draft=await window.riderHubProcessRidePdf(file);window.RIDER_HUB_RIDE_PDF_DRAFT={draft,file};window.rhReviewRidePdf()}catch(e){toast(e?.message||'Could not read ride PDF');if(btn){btn.disabled=false;btn.textContent='Read PDF'}}};
window.rhReviewRidePdf=function(){const x=window.RIDER_HUB_RIDE_PDF_DRAFT;if(!x?.draft)return;const d=x.draft,tasks=(d.days||[]).reduce((a,z)=>a+(z.tasks?.length||0),0);modal(`<div class="modalhead"><div><div class="kicker">REVIEW IMPORT</div><h3>Check before saving</h3><p class="caption">Rider Hub never silently invents missing itinerary details.</p></div><button class="round" onclick="closeModal()">×</button></div><div class="field"><label>RIDE NAME</label><input id="rhPdfRideName" value="${esc(d.name)}"></div><div class="field"><label>ROUTE</label><input id="rhPdfRideRoute" value="${esc(d.route)}" placeholder="Start → destination"></div><div class="grid2"><div class="field"><label>START</label><input id="rhPdfRideStart" value="${esc(d.start)}"></div><div class="field"><label>END</label><input id="rhPdfRideEnd" value="${esc(d.end)}"></div></div><div class="rh-import-summary"><div><b>${d.days.length}</b><span>days found</span></div><div><b>${tasks}</b><span>tasks found</span></div><div><b>${d.lodging?.length||0}</b><span>stay lines</span></div></div>${d.warnings?.length?`<div class="alert">${d.warnings.map(esc).join('<br>')}</div>`:''}<div class="card list rh-import-days">${d.days.map(day=>`<div class="listrow"><div class="ico">${Number(day.day)}</div><div><strong>${esc(day.title)}</strong><p>${esc(day.route||day.date||'Review after save')} · ${day.tasks.length} task${day.tasks.length===1?'':'s'}</p></div><span class="pill good">REVIEWED</span></div>`).join('')}</div><button class="primary full" style="margin-top:12px" onclick="rhSaveImportedRide()">Save ride & PDF</button>`)};
window.rhSaveImportedRide=async function(){const x=window.RIDER_HUB_RIDE_PDF_DRAFT;if(!x?.draft)return;const d=x.draft;d.name=document.querySelector('#rhPdfRideName')?.value.trim()||d.name;d.route=document.querySelector('#rhPdfRideRoute')?.value.trim()||d.route;d.start=document.querySelector('#rhPdfRideStart')?.value.trim()||d.start;d.end=document.querySelector('#rhPdfRideEnd')?.value.trim()||d.end;const r=normalizeRide({...d,id:nowId()});r.sourceFileKey=`ride_plan_${r.id}`;rides().push(r);save();try{await window.savePrivateDoc?.(r.sourceFileKey,x.file)}catch(e){console.warn('Ride PDF saved state but file backup failed',e)}window.RIDER_HUB_RIDE_PDF_DRAFT=null;window.closeModal?.();window.rhOpenRide(r.id);toast(window.cloudSyncConnected?.()?'Ride and PDF saved · Drive backup ready':'Ride and PDF saved on this device')};
window.rhOpenRideSourcePdf=async function(id){const r=getRide(id);if(!r?.sourceFileKey)return;const f=await window.getPrivateDoc?.(r.sourceFileKey);if(!f)return toast('Ride PDF is not available on this device');window.open(URL.createObjectURL(f),'_blank','noopener')};

window.rhSelectRideDay=function(id,i){const r=getRide(id);if(!r)return;r.selectedDay=Math.max(0,Math.min(r.days.length-1,Number(i)||0));persistRide(r);window.renderRides()};
window.rhAddRideTask=function(id){const r=getRide(id);if(!r)return;modal(`<div class="modalhead"><div><div class="kicker">DAY ${Number(day(r)?.day||1)}</div><h3>Add task</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="field"><label>TIME · OPTIONAL</label><input id="rhTaskTime" placeholder="07:30"></div><div class="field"><label>TASK</label><input id="rhTaskTitle" placeholder="Depart hotel"></div><div class="field"><label>NOTE · OPTIONAL</label><input id="rhTaskNote" placeholder="Fuel before leaving"></div><button class="primary full" onclick="rhSaveRideTask('${esc(id)}')">Add task</button>`)};
window.rhSaveRideTask=function(id){const r=getRide(id),d=day(r),title=document.querySelector('#rhTaskTitle')?.value.trim();if(!r||!d||!title)return toast('Add a task');d.tasks.push(normalizeTask({time:document.querySelector('#rhTaskTime')?.value.trim()||'',title,note:document.querySelector('#rhTaskNote')?.value.trim()||''}));persistRide(r);window.closeModal?.();window.renderRides();toast('Task added')};
window.rhRideTaskActions=function(id,di,ti){const r=getRide(id),t=r?.days?.[di]?.tasks?.[ti];if(!t)return;modal(`<div class="modalhead"><div><div class="kicker">RIDE TASK</div><h3>${esc(t.title)}</h3><p class="caption">${esc(t.time||'No fixed time')}</p></div><button class="round" onclick="closeModal()">×</button></div><div class="action3"><button class="confirm" onclick="rhSetRideTask('${esc(id)}',${di},${ti},'done')">Done</button><button class="secondary" onclick="rhDelayRideTask('${esc(id)}',${di},${ti})">Delay</button><button class="secondary" onclick="rhSetRideTask('${esc(id)}',${di},${ti},'skipped')">Skip</button></div>`)};
window.rhSetRideTask=function(id,di,ti,status){const r=getRide(id),t=r?.days?.[di]?.tasks?.[ti];if(!t)return;t.status=status;t.delay=0;persistRide(r);window.closeModal?.();window.renderRides();if(document.querySelector('#rideMode')?.classList.contains('open'))window.rhRenderGenericRideMode();toast(`Task ${status}`)};
window.rhDelayRideTask=function(id,di,ti){modal(`<div class="modalhead"><div><div class="kicker">DELAY</div><h3>How long?</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="field"><label>MINUTES</label><input id="rhRideDelay" inputmode="numeric" value="30"></div><button class="primary full" onclick="rhSaveRideDelay('${esc(id)}',${di},${ti})">Save delay</button>`)};
window.rhSaveRideDelay=function(id,di,ti){const r=getRide(id),t=r?.days?.[di]?.tasks?.[ti];if(!t)return;t.status='delayed';t.delay=Math.max(0,Math.round(Number(document.querySelector('#rhRideDelay')?.value||0)));persistRide(r);window.closeModal?.();window.renderRides();if(document.querySelector('#rideMode')?.classList.contains('open'))window.rhRenderGenericRideMode();toast('Delay recorded')};

window.openRideMode=function(){const id=ui().activeRideId;if(id===legacyId)return window.rhOpenLegacyRideMode();const r=getRide(id);if(!r)return toast('Open a ride first');const el=document.querySelector('#rideMode');if(!el)return;el.classList.add('open');document.body.style.overflow='hidden';window.rhRenderGenericRideMode();setTimeout(()=>rhLoadRideWeather(id,true),0)};
window.rhCloseGenericRideMode=function(){document.querySelector('#rideMode')?.classList.remove('open');document.body.style.overflow='';window.renderRides()};
window.rhRenderGenericRideMode=function(){const r=activeRide(),d=day(r);if(!r||!d)return;const n=nextTask(d),p=progress(d),root=document.querySelector('#rideModeInner');if(!root)return;root.innerHTML=`<div class="header ride-mode-header"><div><div class="kicker">RIDE MODE · DAY ${Number(d.day)}</div><div class="sub">${esc(r.name)}</div></div><div class="header-actions"><button class="round" onclick="rhCloseGenericRideMode()">×</button></div></div><div class="now"><div class="kicker">${n?esc(n.time||'NEXT'):'DAY COMPLETE'}</div><h2>${esc(n?.title||'All tasks complete')}</h2><p class="caption">${esc(n?.note||'Ride at your pace. Update the timeline as the day changes.')}</p><div class="progress" style="margin-top:12px"><i style="width:${p}%"></i></div></div>${n?`<div class="action3"><button class="confirm" onclick="rhModeNextTask('done')">Done</button><button class="secondary" onclick="rhModeDelayNext()">Delay</button><button class="secondary" onclick="rhModeNextTask('skipped')">Skip</button></div>`:''}<div id="rhRideModeWeather" class="card weather"><div class="kicker">LIVE WEATHER</div><strong>Loading destination weather…</strong></div><div class="toolgrid ride-mode-tools" style="margin-top:10px">${[['⌖','Map',`rhRideMap('${r.id}')`],['₹','Expenses',`rhRideExpenses('${r.id}')`],['⛽','Fuel log',`rhRideFuel('${r.id}')`],['📝','Notes',`rhRideNotes('${r.id}')`],['⚠','Bike issue',`rhRideIssue('${r.id}')`],['▣','Packing',`rhRideChecklist('${r.id}','packing')`],['◉','Content',`rhRideChecklist('${r.id}','content')`],['☁','Media backup',`rhRideChecklist('${r.id}','media')`],['→','Tomorrow',`rhRideTomorrow('${r.id}')`],['SOS','Emergency','openEmergency()'],['↕','Traffic',`rhRideTraffic('${r.id}')`],['Σ','Summary',`rhRideSummary('${r.id}')`]].map(x=>`<button class="tool" onclick="${x[2]}"><b>${x[0]}</b><span>${x[1]}</span></button>`).join('')}</div><div class="section-head"><div><div class="kicker">CHECKS</div><h2>Pre-ride checks</h2></div></div><div class="card rh-check-list">${defaultChecks.map((x,i)=>{const k=`${r.selectedDay}_${i}`;return`<div class="checkrow"><div><strong>${esc(x)}</strong><small>Tap when checked.</small></div><button class="checkbtn ${r.preflight[k]?'on':''}" onclick="rhToggleRideCheck('${r.id}','${k}')">✓</button></div>`}).join('')}</div><div class="section-head"><div><div class="kicker">DAY TIMELINE</div><h2>Schedule</h2></div><button class="secondary" onclick="rhAddRideTask('${r.id}')">+ Task</button></div><div class="card" style="padding:14px"><div class="timeline">${taskRows(r,d)}</div></div>`;setTimeout(()=>rhLoadRideWeather(r.id,true),0)};
window.rhModeNextTask=function(status){const r=activeRide(),d=day(r),i=d?.tasks?.findIndex(t=>!['done','skipped'].includes(t.status));if(i==null||i<0)return;d.tasks[i].status=status;d.tasks[i].delay=0;persistRide(r);window.rhRenderGenericRideMode();toast(`Task ${status}`)};
window.rhModeDelayNext=function(){const r=activeRide(),d=day(r),i=d?.tasks?.findIndex(t=>!['done','skipped'].includes(t.status));if(i==null||i<0)return;window.rhDelayRideTask(r.id,r.selectedDay,i)};
window.rhToggleRideCheck=function(id,key){const r=getRide(id);if(!r)return;r.preflight[key]=!r.preflight[key];persistRide(r);window.rhRenderGenericRideMode()};

function mapsUrl(r){const d=day(r),route=d?.route||r.route||'',parts=route.split(/[→➜➡]/).map(x=>x.trim()).filter(Boolean);if(parts.length>=2){const p=new URLSearchParams({api:'1',origin:parts[0],destination:parts[parts.length-1],travelmode:'two-wheeler',dir_action:'navigate'});if(parts.length>2)p.set('waypoints',parts.slice(1,-1).join('|'));return'https://www.google.com/maps/dir/?'+p.toString()}return'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(destination(r)||r.name)}
window.rhRideMap=function(id){const r=getRide(id);if(r)window.open(mapsUrl(r),'_blank','noopener')};
window.rhRideTraffic=function(id){const r=getRide(id);if(!r)return;modal(`<div class="modalhead"><div><div class="kicker">TRAFFIC + ROUTE</div><h3>${esc(destination(r)||r.name)}</h3><p class="caption">Open the current route in Google Maps for live traffic and navigation.</p></div><button class="round" onclick="closeModal()">×</button></div><div class="routecard"><strong>${esc(day(r)?.route||r.route||'Route not added')}</strong><p>Google Maps supplies live traffic and navigation when available.</p></div><button class="primary full" onclick="rhRideMap('${esc(id)}')">Open live route</button>`)};

window.rhRideExpenses=function(id){const r=getRide(id);if(!r)return;const e=r.expenses;modal(`<div class="modalhead"><div><div class="kicker">TRIP MONEY</div><h3>Expenses</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="field"><label>BUDGET ₹</label><input id="rhBudget" inputmode="decimal" value="${Number(r.budgetMax||0)||''}"></div>${[['fuel','Fuel'],['food','Food'],['stay','Stay'],['tolls','Tolls / parking'],['misc','Misc']].map(([k,l])=>`<div class="moneyrow"><span>${l}</span><input id="rhExp_${k}" inputmode="decimal" value="${Number(e[k]||0)||''}"></div>`).join('')}<button class="primary full" onclick="rhSaveRideExpenses('${esc(id)}')">Save expenses</button>`)};
window.rhSaveRideExpenses=function(id){const r=getRide(id);if(!r)return;r.budgetMax=Number(document.querySelector('#rhBudget')?.value||0);for(const k of ['fuel','food','stay','tolls','misc'])r.expenses[k]=Math.max(0,Number(document.querySelector(`#rhExp_${k}`)?.value||0));persistRide(r);window.closeModal?.();toast('Expenses saved')};
window.rhRideFuel=function(id){const r=getRide(id);if(!r)return;modal(`<div class="modalhead"><div><div class="kicker">FUEL LOG</div><h3>Fuel stops</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="card list">${r.fuelLogs.map((x,i)=>`<div class="listrow"><div class="ico">⛽</div><div><strong>${esc(x.place||'Fuel stop')}</strong><p>${Number(x.litres||0)} L · ₹${Number(x.cost||0).toLocaleString('en-IN')}${x.odo?` · ${Number(x.odo).toLocaleString('en-IN')} km`:''}</p></div><button class="secondary" onclick="rhDeleteFuel('${esc(id)}',${i})">×</button></div>`).join('')||'<div class="listrow"><div class="ico">⛽</div><div><strong>No fuel stops yet</strong><p>Add one when you refuel.</p></div></div>'}</div><div class="grid2"><div class="field"><label>LITRES</label><input id="rhFuelL" inputmode="decimal"></div><div class="field"><label>COST ₹</label><input id="rhFuelC" inputmode="decimal"></div></div><div class="field"><label>PLACE</label><input id="rhFuelP" placeholder="Fuel station / town"></div><button class="primary full" onclick="rhAddFuel('${esc(id)}')">Add fuel stop</button>`)};
window.rhAddFuel=function(id){const r=getRide(id);if(!r)return;r.fuelLogs.push({litres:Number(document.querySelector('#rhFuelL')?.value||0),cost:Number(document.querySelector('#rhFuelC')?.value||0),place:document.querySelector('#rhFuelP')?.value.trim()||'',at:new Date().toISOString()});persistRide(r);window.rhRideFuel(id);toast('Fuel stop added')};
window.rhDeleteFuel=function(id,i){const r=getRide(id);if(!r)return;r.fuelLogs.splice(i,1);persistRide(r);window.rhRideFuel(id)};
window.rhRideNotes=function(id){const r=getRide(id);if(!r)return;modal(`<div class="modalhead"><div><div class="kicker">RIDE NOTES</div><h3>${esc(r.name)}</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="field"><label>NOTES</label><textarea id="rhRideNotesText">${esc(r.notes)}</textarea></div><button class="primary full" onclick="rhSaveRideNotes('${esc(id)}')">Save notes</button>`)};
window.rhSaveRideNotes=function(id){const r=getRide(id);if(!r)return;r.notes=document.querySelector('#rhRideNotesText')?.value||'';persistRide(r);window.closeModal?.();toast('Notes saved')};
window.rhRideIssue=function(id){const r=getRide(id);if(!r)return;modal(`<div class="modalhead"><div><div class="kicker">BIKE ISSUE</div><h3>Ride issue log</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="card list">${r.issues.map((x,i)=>`<div class="listrow"><div class="ico">⚠</div><div><strong>${esc(x.text)}</strong><p>${esc(new Date(x.at).toLocaleString())}</p></div></div>`).join('')||'<div class="listrow"><div class="ico">✓</div><div><strong>No issues logged</strong></div></div>'}</div><div class="field"><label>NEW ISSUE</label><textarea id="rhIssueText" placeholder="Describe what happened"></textarea></div><button class="primary full" onclick="rhSaveRideIssue('${esc(id)}')">Log issue</button>`)};
window.rhSaveRideIssue=function(id){const r=getRide(id),text=document.querySelector('#rhIssueText')?.value.trim();if(!r||!text)return toast('Describe the issue');r.issues.push({text,at:new Date().toISOString(),day:Number(day(r)?.day||1)});persistRide(r);window.rhRideIssue(id);toast('Issue logged')};

function checklistData(type){return type==='packing'?defaultPacking:type==='content'?defaultContent:defaultMedia}
window.rhRideChecklist=function(id,type){const r=getRide(id);if(!r)return;const store=r[type]||(r[type]={}),items=checklistData(type),title=type==='packing'?'Packing':type==='content'?'Content checklist':'Media backup';modal(`<div class="modalhead"><div><div class="kicker">RIDE MODE</div><h3>${title}</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="card">${items.map((x,i)=>`<div class="checkrow"><div><strong>${esc(x)}</strong></div><button class="checkbtn ${store[i]?'on':''}" onclick="rhToggleRideChecklist('${esc(id)}','${esc(type)}',${i})">✓</button></div>`).join('')}</div>`)};
window.rhToggleRideChecklist=function(id,type,i){const r=getRide(id);if(!r)return;r[type]=r[type]||{};r[type][i]=!r[type][i];persistRide(r);window.rhRideChecklist(id,type)};
window.rhRideTomorrow=function(id){const r=getRide(id);if(!r)return;const n=r.days[r.selectedDay+1];modal(`<div class="modalhead"><div><div class="kicker">TOMORROW</div><h3>${esc(n?.title||'Trip complete')}</h3></div><button class="round" onclick="closeModal()">×</button></div>${n?`<div class="routecard"><strong>${esc(n.route||[n.from,n.to].filter(Boolean).join(' → ')||'Route not added')}</strong><p>${esc(n.date||'Date not added')} · ${n.tasks.length} planned task${n.tasks.length===1?'':'s'}</p></div><div class="card list">${n.tasks.slice(0,6).map(t=>`<div class="listrow"><div class="ico">→</div><div><strong>${esc(t.title)}</strong><p>${esc(t.time||'No fixed time')}</p></div></div>`).join('')}</div>`:'<div class="alert">No next ride day.</div>'}`)};
window.rhRideSummary=function(id){const r=getRide(id);if(!r)return;const spent=Object.values(r.expenses||{}).reduce((a,b)=>a+Number(b||0),0),all=r.days.flatMap(d=>d.tasks),done=all.filter(t=>t.status==='done').length,skipped=all.filter(t=>t.status==='skipped').length;modal(`<div class="modalhead"><div><div class="kicker">RIDE SUMMARY</div><h3>${esc(r.name)}</h3></div><button class="round" onclick="closeModal()">×</button></div><div class="grid3"><div class="tile"><label>PROGRESS</label><b>${totalProgress(r)}%</b></div><div class="tile"><label>DONE</label><b>${done}</b></div><div class="tile"><label>SKIPPED</label><b>${skipped}</b></div></div><div class="grid2" style="margin-top:8px"><div class="tile"><label>SPEND</label><b>₹${Math.round(spent).toLocaleString('en-IN')}</b></div><div class="tile"><label>FUEL STOPS</label><b>${r.fuelLogs.length}</b></div></div><div class="routecard"><strong>Issues logged</strong><p>${r.issues.length}</p></div><button class="primary full" onclick="rhMarkRideComplete('${esc(id)}')">${r.completed?'Mark as planned again':'Mark ride completed'}</button>`)};
window.rhMarkRideComplete=function(id){const r=getRide(id);if(!r)return;r.completed=!r.completed;persistRide(r);window.closeModal?.();if(document.querySelector('#rideMode')?.classList.contains('open'))window.rhCloseGenericRideMode();else window.renderRides();toast(r.completed?'Ride completed':'Ride moved back to planned')};

window.rhLoadRideWeather=async function(id,inMode=false){const r=getRide(id);if(!r)return;const target=destination(r);const el=document.querySelector(inMode?'#rhRideModeWeather':'#rhRideWeatherCard');if(!el)return;if(!target){el.innerHTML='<div class="kicker">LIVE WEATHER</div><strong>Add a destination to load weather.</strong>';return}try{const geo=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(target)}&count=1&language=en&format=json`).then(x=>x.json()),g=geo.results?.[0];if(!g)throw new Error('Destination not found');const w=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${g.latitude}&longitude=${g.longitude}&current=temperature_2m,weather_code,wind_speed_10m&timezone=auto`).then(x=>x.json()),c=w.current;if(!c)throw new Error('Weather unavailable');el.innerHTML=`<div class="weather-top"><div><div class="kicker">LIVE WEATHER · ${esc(g.name)}</div><strong class="weather-big">${Math.round(Number(c.temperature_2m))}°C</strong><div class="caption">Wind ${Math.round(Number(c.wind_speed_10m||0))} km/h · updated now</div></div><span class="pill good">LIVE</span></div>`}catch{el.innerHTML=`<div class="weather-top"><div><div class="kicker">LIVE WEATHER</div><strong>${esc(target)}</strong><div class="caption">Weather could not be loaded right now.</div></div><button class="secondary" onclick="rhLoadRideWeather('${esc(id)}',${inMode?'true':'false'})">Retry</button></div>`}};

/* Existing simple custom ride links now open the full generic detail. */
window.openCustomRide=id=>window.rhOpenRide(id);
})();
