(()=>{
'use strict';
const ALLOWED_EMAIL='jayrut2006@gmail.com';
const APP_KEY='riderhub_stable_v1';
const DB_NAME='riderhub_private_docs';
const DEFAULT_ACCENT='#f0a12b';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const clone=x=>JSON.parse(JSON.stringify(x));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n==null||n===''?'—':'₹'+Math.round(Number(n)||0).toLocaleString('en-IN');
const today=()=>new Date().toISOString().slice(0,10);
const addDays=(date,n)=>{const d=new Date((date||today())+'T00:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const fmtDate=s=>{if(!s)return'Date TBD';try{return new Date(s+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}catch{return s}};
const HOME='3G7X+FJ2, Gaurav Path, Shastrinagar, Naranpura, Ahmedabad, Gujarat 380063';
const HOTEL='Hotel Landmark, College Road, Opp. COCO Petrol Pump, Banswara, Rajasthan 327001';
const BANSWARA_DAYS=[
 {date:'2026-08-28',title:'Ahmedabad → Banswara',from:'Ahmedabad',to:'Banswara',segments:[
  {label:'Home → Balasinor',origin:HOME,destination:'Balasinor, Gujarat',waypoints:['Odhav Circle, Ahmedabad','BPCL R B Patel Sons, Kuha, Gujarat','Haldharvas Chokdi, Gujarat','Ladvel Chokdi, Gujarat']},
  {label:'Balasinor → Mangarh',origin:'Balasinor, Gujarat',destination:'Mangarh Dham, Anandpuri, Rajasthan',waypoints:['Lunawada, Gujarat','Santrampur, Gujarat','Khedapada, Santrampur, Mahisagar, Gujarat']},
  {label:'Mangarh → Hotel',origin:'Mangarh Dham, Anandpuri, Rajasthan',destination:HOTEL,waypoints:['Anandpuri Bus Stand, Rajasthan','New Bus Stand, Banswara, Rajasthan']}],tasks:[['04:15','Wake / light food','Final tyre, chain, brakes, rain gear, straps and documents.'],['05:00','Leave Home','Start before traffic builds.'],['07:00','Breakfast + break','20–30 min, water and stretch.'],['09:15','Mangarh Dham','Quiet morning target.'],['12:00','Hotel check-in','Lunch and remove wet gear.'],['12:30','Rest','Recovery + charge electronics.'],['15:15','Anand Sagar + Kalpavriksha','Short quiet stop.'],['16:15','Kagdi Pick Up Weir','Leave if crowded.'],['17:10','Dialab Lake · optional','Only if both riders are fresh.'],['18:30','Dinner','Simple meal.'],['20:00','Fuel + prep','Fill bike and prep Saturday bag.'],['21:15','Sleep','Saturday starts early.']]},
 {date:'2026-08-29',title:'Banswara Adventure Loop',from:'Banswara',to:'Banswara',segments:[
  {label:'Hotel → Chacha Kota → Mahi',origin:HOTEL,destination:'Mahi Bajaj Sagar Dam, Banswara, Rajasthan',waypoints:['Chacha Kota, Banswara, Rajasthan']},
  {label:'Mahi → Singhpura → Hotel',origin:'Mahi Bajaj Sagar Dam, Banswara, Rajasthan',destination:HOTEL,waypoints:['Ghatol, Rajasthan','Singhpura, Ghatol, Banswara, Rajasthan','Singhpura Falls, Rajasthan']}],tasks:[['04:45','Wake','Tea / banana / biscuits.'],['05:10','Leave hotel','Be rolling before normal visitors.'],['05:35','Chacha Kota','Normal access + safe firm dirt/grass only.'],['07:00','Mahi Dam','Visitor road only; obey barricades.'],['08:00','Breakfast','Proper breakfast + short rest.'],['09:00','Leave for Singhpura','Navigate to Singhpura/Ghatol first.'],['09:45','Singhpura Falls','Park, walk; do not ride through pedestrian water crossing.'],['13:15','Back Banswara','Lunch.'],['14:15','Rest','Dry boots/socks/rain gear.'],['18:00','Flexible evening','Nothing compulsory.'],['21:15','Sleep','Sunday starts early.']]},
 {date:'2026-08-30',title:'Banswara → Ahmedabad',from:'Banswara',to:'Ahmedabad',segments:[
  {label:'Hotel → Jagmer → Hotel',origin:HOTEL,destination:HOTEL,waypoints:['Jagmer Hills, Banswara, Rajasthan']},
  {label:'Hotel → Lunawada via Arthuna',origin:HOTEL,destination:'Lunawada, Gujarat',waypoints:['Arthuna Group of Temples, Rajasthan','Khedapada, Santrampur, Mahisagar, Gujarat','Santrampur Bus Station, Gujarat']},
  {label:'Lunawada → Home',origin:'Lunawada, Gujarat',destination:HOME,waypoints:['Balasinor, Gujarat','Ladvel Chokdi, Gujarat','BPCL R B Patel Sons, Kuha, Gujarat','Odhav Circle, Ahmedabad']}],tasks:[['04:45','Wake + pack','Keep only a light Jagmer bag if hotel can hold luggage.'],['05:10','Leave hotel','Light bike for dirt riding.'],['05:30','Jagmer / Jagmeru','Paved approach → firm red dirt/grass; rough parts solo only.'],['07:15','Return hotel','Collect luggage.'],['07:30','Breakfast + checkout','Final tyre, chain and luggage check.'],['08:15','Leave for Arthuna','Normal public road.'],['09:15','Arthuna','Explore archaeological complex properly.'],['10:45','Leave for Ahmedabad','No more sightseeing.'],['12:30','Lunch + rest','30–45 min.'],['16:30','Ahmedabad target','Rain/traffic buffer until 18:00.']]}
];
function taskObj(t){return{time:t[0]||'',title:t[1]||'Task',note:t[2]||'',status:'upcoming',delay:0}}
function banswaraRide(oldRide={}){const r={id:'ride_banswara_2026',name:'Banswara 3-Day Ronin Adventure',start:'2026-08-28',end:'2026-08-30',status:'planned',selectedDay:Math.max(0,Math.min(2,Number(oldRide.selectedDay||0))),days:BANSWARA_DAYS.map((d,di)=>({...d,day:di+1,tasks:d.tasks.map((t,ti)=>{const o=taskObj(t),s=oldRide.tasks?.[`${di+1}_${ti}`];if(s)o.status=s;const delay=oldRide.tasks?.[`${di+1}_${ti}_delay`];if(delay)o.delay=Number(delay)||0;return o})})),expenses:clone(oldRide.expenses||{fuel:0,food:0,stay:2470,parking:0,misc:0}),notes:oldRide.notes||'',fuelLogs:clone(oldRide.fuelLogs||[]),packing:clone(oldRide.packing||{})};return r}
function blankState(){return{schema:1,profile:{email:'',name:'',bikeConfigured:false},bike:{name:'My Motorcycle',manufacturer:'',model:'',variant:'',colour:'',year:new Date().getFullYear(),odo:0,engine:'',braking:'',transmission:'',fuelTank:'',tyres:'',manual:{status:'none',name:'',analysis:null},serviceMilestones:[],serviceHistory:[],nextServiceKm:0},rides:[],gear:[],documents:{custom:[]},ui:{page:'home',rideId:'',gearStatus:'all',gearOwner:'all',gearQuery:''}}}
function migrate(raw){const s=blankState();if(!raw||typeof raw!=='object')return s;
 s.profile={...s.profile,...(raw.profile||{})};s.profile.email=raw.profile?.account?.email||raw.profile?.email||s.profile.email;s.profile.name=raw.profile?.account?.name||raw.profile?.name||s.profile.name;s.profile.bikeConfigured=raw.profile?.bikeConfigured!==false&&!!(raw.bike?.manufacturer||raw.bike?.model);
 s.bike={...s.bike,...(raw.bike||{})};s.bike.manual=raw.bike?.manual||s.bike.manual;s.bike.serviceMilestones=Array.isArray(raw.bike?.serviceMilestones)?raw.bike.serviceMilestones:[];s.bike.serviceHistory=Array.isArray(raw.bike?.serviceHistory)?raw.bike.serviceHistory:[];
 s.gear=Array.isArray(raw.gear)?raw.gear:[];s.documents={custom:Array.isArray(raw.documents?.custom)?raw.documents.custom:[]};
 if(Array.isArray(raw.rides)&&raw.rides.length)s.rides=raw.rides.map(normalizeRide);else{s.rides=[banswaraRide(raw.ride||{})];for(const cr of raw.customRides||[])s.rides.push(normalizeRide({id:cr.id,name:cr.name,start:cr.start,end:cr.end,status:'planned',days:[{date:cr.start||'',title:cr.route||cr.name,from:'',to:'',segments:[],tasks:[]}]}))}
 s.ui={...s.ui,...(raw.ui||{})};return s}
function normalizeRide(r){const x={id:r.id||'ride_'+Date.now().toString(36)+Math.random().toString(36).slice(2,5),name:r.name||'Ride',start:r.start||'',end:r.end||r.start||'',status:r.status||'planned',selectedDay:Number(r.selectedDay||0),days:Array.isArray(r.days)?r.days:[],expenses:{fuel:0,food:0,stay:0,parking:0,misc:0,...(r.expenses||{})},notes:r.notes||'',fuelLogs:Array.isArray(r.fuelLogs)?r.fuelLogs:[],packing:r.packing||{}};x.days=x.days.map((d,i)=>({day:i+1,date:d.date||addDays(x.start,i),title:d.title||`Day ${i+1}`,from:d.from||'',to:d.to||'',segments:Array.isArray(d.segments)?d.segments:[],tasks:(d.tasks||[]).map(t=>Array.isArray(t)?taskObj(t):{time:t.time||'',title:t.title||'Task',note:t.note||'',status:t.status||'upcoming',delay:Number(t.delay||0)})}));if(!x.days.length)x.days=[{day:1,date:x.start||today(),title:'Day 1',from:'',to:'',segments:[],tasks:[]}];x.selectedDay=Math.max(0,Math.min(x.days.length-1,x.selectedDay));return x}
let state=migrate(readLocal());let user=null;let saveTimer=null;let installPrompt=null;let modalLocked=false;
function readLocal(){try{const stable=JSON.parse(localStorage.getItem(APP_KEY)||'null');if(stable)return stable;return JSON.parse(localStorage.getItem('riderhub_v6')||'null')}catch{return null}}
function persistLocal(){localStorage.setItem(APP_KEY,JSON.stringify(state))}
function save(){persistLocal();clearTimeout(saveTimer);saveTimer=setTimeout(()=>window.riderHubCloudSave?.(clone(state)),450);renderHeader();renderCurrent()}
window.save=save;window.state=state;
window.riderHubExportState=()=>clone(state);
window.riderHubImportState=raw=>{state=migrate(raw);window.state=state;persistLocal();applyAccent();render();return true};
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2300)}window.toast=toast;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});
function openModal(html,{locked=false}={}){modalLocked=locked;$('#modal').innerHTML=html;$('#modalWrap').classList.add('open')}window.openModal=openModal;
function closeModal(){if(modalLocked)return;$('#modalWrap').classList.remove('open');$('#modal').innerHTML=''}window.closeModal=closeModal;
$('#modalWrap')?.addEventListener('click',e=>{if(e.target.id==='modalWrap')closeModal()});
function accentFor(colour=''){const c=String(colour).toLowerCase();if(/purple|violet|lavender/.test(c))return'#9b6cff';if(/red|crimson|maroon/.test(c))return'#ef5b5b';if(/blue|navy|indigo/.test(c))return'#5f8fff';if(/green|olive/.test(c))return'#63c785';if(/yellow|gold/.test(c))return'#f3bd38';if(/orange|ember|copper|bronze/.test(c))return'#f0a12b';if(/pink|magenta/.test(c))return'#ef6fb4';if(/white|silver|grey|gray|black/.test(c))return'#d0a24a';return DEFAULT_ACCENT}
function rgb(hex){const h=hex.replace('#','');return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)].join(',')}
function applyAccent(){const a=accentFor(state.bike?.colour);document.documentElement.style.setProperty('--accent',a);document.documentElement.style.setProperty('--accent-rgb',rgb(a))}
function renderHeader(){const b=state.bike||{},configured=state.profile?.bikeConfigured;$('.brand-title').textContent=configured?(b.name||`${b.manufacturer} ${b.model}`.trim()):'RIDER HUB';$('.brand-sub').textContent=configured?[b.variant,b.colour].filter(Boolean).join(' · ')||'MY MOTORCYCLE':'MOTORCYCLE OS';applyAccent()}
function setPage(page){state.ui.page=page;persistLocal();$$('.page').forEach(p=>p.classList.toggle('active',p.id===page));$$('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.page===page));renderCurrent();window.scrollTo(0,0)}window.setPage=setPage;
function renderCurrent(){const p=state.ui.page||'home';if(p==='home')renderHome();if(p==='bike')renderBike();if(p==='rides')renderRides();if(p==='gear')renderGear();if(p==='more')renderMore()}
function render(){renderHeader();setPage(state.ui.page||'home')}window.render=render;
function nextService(){const odo=Number(state.bike.odo||0),m=(state.bike.serviceMilestones||[]).find(x=>Number(x)>odo);return Number(m||state.bike.nextServiceKm||0)}
function renderHome(){const b=state.bike,n=nextService(),nextRide=state.rides.find(r=>r.status!=='completed')||state.rides[0];$('#home').innerHTML=`<div class="home-layout"><div class="card hero"><div class="kicker">RIDER HUB</div><h1>Your motorcycle OS.<br><span>Ready when you are.</span></h1><div class="bikeplate" onclick="setPage('bike')"><div class="between"><div><strong>${esc(state.profile.bikeConfigured?b.name:'Set up your motorcycle')}</strong><div class="caption">${esc(state.profile.bikeConfigured?[b.variant,b.colour,b.year].filter(Boolean).join(' · '):'Add your bike details to get started')}</div></div><span class="pill ${state.profile.bikeConfigured?'good':'warn'}">${state.profile.bikeConfigured?'READY':'SETUP'}</span></div>${state.profile.bikeConfigured?`<div class="metrics"><div class="metric"><label>ODOMETER</label><b>${Number(b.odo||0).toLocaleString('en-IN')} km</b></div><div class="metric"><label>NEXT SERVICE</label><b class="accent">${n?n.toLocaleString('en-IN')+' km':'Manual / schedule needed'}</b></div></div>`:''}</div></div><div><div class="section-head"><div><div class="kicker">NEXT RIDE</div><h2>${esc(nextRide?.name||'No ride planned')}</h2></div></div><div class="card notice">${nextRide?`<div class="between"><div><strong>${nextRide.days.length} day${nextRide.days.length===1?'':'s'}</strong><div class="caption">${fmtDate(nextRide.start)}${nextRide.end&&nextRide.end!==nextRide.start?' → '+fmtDate(nextRide.end):''}</div></div><button class="ghost" onclick="openRide('${nextRide.id}')">Open</button></div>`:'<div class="caption">Create a ride when you are ready.</div>'}</div><div class="section-head"><div><div class="kicker">QUICK ACCESS</div><h2>Rider controls</h2></div></div><div class="quickgrid"><button class="quick" onclick="setPage('rides')"><b>↗</b><span>My rides</span></button><button class="quick" onclick="editOdo()"><b>◉</b><span>Odometer</span></button><button class="quick" onclick="setPage('gear')"><b>▣</b><span>Gear</span></button><button class="quick" onclick="openEmergency()"><b>SOS</b><span>Emergency</span></button></div></div></div>`}
function editOdo(){openModal(`<div class="modalhead"><div><div class="kicker">ODOMETER</div><h3>Update reading</h3></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="field"><label>KILOMETRES</label><input id="odoInput" inputmode="numeric" value="${Number(state.bike.odo||0)}"></div><div class="modal-actions"><button class="ghost" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveOdo()">Save</button></div>`)}window.editOdo=editOdo;
window.saveOdo=()=>{const v=Math.max(0,Math.round(Number($('#odoInput')?.value||0)));state.bike.odo=v;save();closeModal();toast('Odometer updated')};
function specValue(field){const v=state.bike?.[field];return v&&v!=='Not added'&&v!=='—'?v:`<button class="ghost" onclick="openOwnerManual()">Add Owner's Manual</button>`}
function renderBike(){const b=state.bike||{},manual=b.manual||{status:'none'},milestones=b.serviceMilestones||[];$('#bike').innerHTML=`<div class="card hero"><div class="kicker">MY MOTORCYCLE</div><h1>${esc(b.name||'My Motorcycle')}</h1><div class="caption">${esc([b.variant,b.colour,b.year].filter(Boolean).join(' · '))}</div><div class="metrics"><div class="metric"><label>ODOMETER</label><b>${Number(b.odo||0).toLocaleString('en-IN')} km</b></div><div class="metric"><label>OWNER MANUAL</label><b class="accent">${manual.status==='processed'?'PROCESSED':manual.status==='scanned'?'SAVED':'NOT ADDED'}</b></div></div></div><div class="section-head"><div><div class="kicker">OVERVIEW</div><h2>Bike information</h2></div><div style="display:flex;gap:7px"><button class="ghost" onclick="openBikeSetup(false)">Edit bike</button><button class="primary" onclick="openOwnerManual()">${manual.status==='none'?'Add manual':'Owner manual'}</button></div></div><div class="info-grid">${[['Manufacturer',esc(b.manufacturer||'—')],['Model',esc(b.model||'—')],['Variant',esc(b.variant||'—')],['Colour',esc(b.colour||'—')],['Year',esc(b.year||'—')],['Engine',specValue('engine')],['Braking',specValue('braking')],['Transmission',specValue('transmission')],['Fuel tank',specValue('fuelTank')],['Tyres',specValue('tyres')]].map(([k,v])=>`<div class="info"><label>${k.toUpperCase()}</label><b>${v}</b></div>`).join('')}</div><div class="section-head"><div><div class="kicker">MAINTENANCE</div><h2>Service schedule</h2></div></div><div class="card list">${milestones.length?milestones.slice(0,12).map((m,i)=>`<div class="listrow"><div class="ico">${i+1}</div><div><strong>${Number(m).toLocaleString('en-IN')} km</strong><p>${Number(m)>Number(b.odo||0)?'Upcoming manufacturer/manual milestone':'Passed milestone'}</p></div><span class="pill ${Number(m)>Number(b.odo||0)?'warn':'good'}">${Number(m)>Number(b.odo||0)?'UPCOMING':'DONE/PASSED'}</span></div>`).join(''):`<div class="listrow"><div class="ico">↥</div><div><strong>Add Owner's Manual</strong><p>Rider Hub can look for service milestones and maintenance information without guessing.</p></div><button class="ghost" onclick="openOwnerManual()">Add</button></div>`}</div><div class="section-head"><div><div class="kicker">SERVICE HISTORY</div><h2>Completed work</h2></div><button class="ghost" onclick="addServiceRecord()">+ Add</button></div><div class="card list">${(b.serviceHistory||[]).length?b.serviceHistory.map((x,i)=>`<div class="listrow"><div class="ico">✓</div><div><strong>${esc(x.name||'Service')}</strong><p>${esc(x.date||'')} · ${Number(x.odo||0).toLocaleString('en-IN')} km · ${esc(x.work||'')}</p></div><b>${money(x.cost)}</b></div>`).join(''):'<div class="listrow"><div class="ico">＋</div><div><strong>No service records yet</strong><p>Add work as you maintain the bike.</p></div></div>'}</div><div class="section-head"><div><div class="kicker">PRIVATE FILES</div><h2>Document vault</h2></div></div>${documentsHtml()}`}
window.renderBike=renderBike;
window.addServiceRecord=()=>openModal(`<div class="modalhead"><div><div class="kicker">SERVICE</div><h3>Add service record</h3></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="field"><label>NAME</label><input id="svcName" placeholder="Periodic service"></div><div class="grid2"><div class="field"><label>DATE</label><input id="svcDate" type="date" value="${today()}"></div><div class="field"><label>ODOMETER KM</label><input id="svcOdo" inputmode="numeric" value="${Number(state.bike.odo||0)}"></div></div><div class="field"><label>WORK / NOTES</label><textarea id="svcWork"></textarea></div><div class="field"><label>COST ₹</label><input id="svcCost" inputmode="decimal"></div><div class="modal-actions"><button class="ghost" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveServiceRecord()">Save</button></div>`);
window.saveServiceRecord=()=>{state.bike.serviceHistory=state.bike.serviceHistory||[];state.bike.serviceHistory.push({name:$('#svcName')?.value.trim()||'Service',date:$('#svcDate')?.value||'',odo:Number($('#svcOdo')?.value||0),work:$('#svcWork')?.value.trim()||'',cost:Number($('#svcCost')?.value||0)});save();closeModal();toast('Service record saved')};
const MAJORS=['Royal Enfield','Honda','Yamaha','TVS','Bajaj','Hero','KTM','Kawasaki','Suzuki','BMW Motorrad','Triumph','Harley-Davidson','Ducati','Aprilia','Benelli'];
async function allOtherMakes(){try{const all=await window.riderHubMotorcycleMakes?.();return(all||[]).filter(x=>!MAJORS.includes(x))}catch{return[]}}
async function openBikeSetup(gate=true){const b=state.bike||{};openModal(`<div class="modalhead"><div><div class="kicker">MY MOTORCYCLE</div><h3>${gate?'Set up your motorcycle':'Edit motorcycle'}</h3></div>${gate?'':'<button class="iconbtn" onclick="closeModal()">×</button>'}</div><div class="field"><label>MANUFACTURER</label><select id="bikeMake" onchange="bikeMakeChanged()"><option value="">Choose manufacturer</option>${MAJORS.map(m=>`<option ${b.manufacturer===m?'selected':''}>${esc(m)}</option>`).join('')}<option value="__other__">Other manufacturers…</option></select></div><div id="otherMakeWrap"></div><div class="field"><label>MODEL</label><select id="bikeModel" onchange="bikeModelChanged()"><option value="">Choose model</option></select></div><div class="grid2"><div class="field"><label>VARIANT</label><select id="bikeVariant" onchange="bikeVariantChanged()"><option value="">Choose / not listed</option></select></div><div class="field"><label>COLOUR</label><select id="bikeColour" onchange="bikeColourChanged()"><option value="">Choose / not listed</option></select></div></div><div class="grid2"><div class="field"><label>YEAR</label><input id="bikeYear" inputmode="numeric" value="${Number(b.year||new Date().getFullYear())}"></div><div class="field"><label>ODOMETER KM</label><input id="bikeOdo" inputmode="numeric" value="${Number(b.odo||0)}"></div></div><div class="modal-actions">${gate?'':'<button class="ghost" onclick="closeModal()">Cancel</button>'}<button class="primary" onclick="saveBikeSetup(${gate?'true':'false'})">Continue</button></div>`,{locked:gate});setTimeout(async()=>{if(b.manufacturer&&MAJORS.includes(b.manufacturer)){await loadModels(b.manufacturer,b.model);await loadVariantColour(b.manufacturer,b.model,b.variant,b.colour)}},0)}window.openBikeSetup=openBikeSetup;
async function loadModels(make,selected=''){const el=$('#bikeModel');if(!el)return;el.innerHTML='<option value="">Loading…</option>';const models=await window.riderHubMotorcycleModels?.(make)||[];el.innerHTML='<option value="">Choose model</option>'+models.map(m=>`<option ${m===selected?'selected':''}>${esc(m)}</option>`).join('')+'<option value="__custom__">Other / enter manually</option>';if(selected&&!models.includes(selected))el.insertAdjacentHTML('afterbegin',`<option selected>${esc(selected)}</option>`)}
window.bikeMakeChanged=async()=>{const el=$('#bikeMake'),wrap=$('#otherMakeWrap');if(!el)return;if(el.value==='__other__'){const other=await allOtherMakes();wrap.innerHTML=`<div class="field"><label>OTHER MANUFACTURER</label><select id="bikeOtherMake" onchange="otherMakeChanged()"><option value="">Choose manufacturer</option>${other.map(m=>`<option>${esc(m)}</option>`).join('')}<option value="__custom__">Not listed / enter manually</option></select><input id="bikeCustomMake" placeholder="Manufacturer" style="display:none;margin-top:8px"></div>`;$('#bikeModel').innerHTML='<option value="">Choose manufacturer first</option>';return}wrap.innerHTML='';await loadModels(el.value)};
window.otherMakeChanged=async()=>{const el=$('#bikeOtherMake'),custom=$('#bikeCustomMake');if(el.value==='__custom__'){custom.style.display='block';$('#bikeModel').innerHTML='<option value="__custom__">Enter model manually</option>';return}custom.style.display='none';await loadModels(el.value)};
window.bikeModelChanged=async()=>{const model=$('#bikeModel');if(model?.value==='__custom__'){model.insertAdjacentHTML('afterend','<input id="bikeCustomModel" placeholder="Motorcycle model" style="margin-top:8px">');return}$('#bikeCustomModel')?.remove();await loadVariantColour(selectedMake(),model?.value||'')};
function selectedMake(){const main=$('#bikeMake')?.value;if(main==='__other__'){const o=$('#bikeOtherMake')?.value;return o==='__custom__'?$('#bikeCustomMake')?.value.trim():o||''}return main||''}
async function loadVariantColour(make,model,variant='',colour=''){const p=window.riderHubMotorcycleProfile?.(make,model),v=$('#bikeVariant'),c=$('#bikeColour');if(!v||!c)return;const variants=Object.keys(p?.variants||{});v.innerHTML='<option value="">Choose / not listed</option>'+variants.map(x=>`<option ${x===variant?'selected':''}>${esc(x)}</option>`).join('')+'<option value="__custom__">Other / enter manually</option>';if(variant&&!variants.includes(variant))v.insertAdjacentHTML('afterbegin',`<option selected>${esc(variant)}</option>`);const colours=p?.variants?.[variant]||[];c.innerHTML='<option value="">Choose / not listed</option>'+colours.map(x=>`<option ${x===colour?'selected':''}>${esc(x)}</option>`).join('')+'<option value="__custom__">Other / enter manually</option>';if(colour&&!colours.includes(colour))c.insertAdjacentHTML('afterbegin',`<option selected>${esc(colour)}</option>`)}
window.bikeVariantChanged=()=>{const v=$('#bikeVariant');if(v?.value==='__custom__'){v.insertAdjacentHTML('afterend','<input id="bikeCustomVariant" placeholder="Variant" style="margin-top:8px">')}else $('#bikeCustomVariant')?.remove();const make=selectedMake(),model=selectedModel(),p=window.riderHubMotorcycleProfile?.(make,model),colours=p?.variants?.[v?.value]||[],c=$('#bikeColour');if(c)c.innerHTML='<option value="">Choose / not listed</option>'+colours.map(x=>`<option>${esc(x)}</option>`).join('')+'<option value="__custom__">Other / enter manually</option>'};
function selectedModel(){const m=$('#bikeModel')?.value;return m==='__custom__'?$('#bikeCustomModel')?.value.trim():m||''}
function selectedVariant(){const v=$('#bikeVariant')?.value;return v==='__custom__'?$('#bikeCustomVariant')?.value.trim():v||''}
window.bikeColourChanged=()=>{const c=$('#bikeColour');if(c?.value==='__custom__'){if(!$('#bikeCustomColour'))c.insertAdjacentHTML('afterend','<input id="bikeCustomColour" placeholder="Bike colour" style="margin-top:8px">')}else $('#bikeCustomColour')?.remove()};
function selectedColour(){const c=$('#bikeColour')?.value;if(c==='__custom__')return $('#bikeCustomColour')?.value.trim()||'';return c||''}
window.saveBikeSetup=(gate=false)=>{const make=selectedMake(),model=selectedModel();if(!make||!model)return toast('Choose manufacturer and model');const variant=selectedVariant(),colour=selectedColour(),year=Math.round(Number($('#bikeYear')?.value||new Date().getFullYear())),odo=Math.max(0,Math.round(Number($('#bikeOdo')?.value||0))),p=window.riderHubMotorcycleProfile?.(make,model);const changed=state.bike.manufacturer&&state.bike.model&&(state.bike.manufacturer!==make||state.bike.model!==model);state.bike={...state.bike,manufacturer:make,model,variant,colour,year,odo,name:`${make} ${model}`,engine:p?.specs?.engine||state.bike.engine,transmission:p?.specs?.transmission||state.bike.transmission,fuelTank:p?.specs?.fuelTank||state.bike.fuelTank,tyres:p?.tyresByVariant?.[variant]||p?.specs?.tyres||state.bike.tyres,braking:p?.brakingByVariant?.[variant]||state.bike.braking,serviceMilestones:p?.serviceMilestones||state.bike.serviceMilestones,nextServiceKm:window.riderHubNextServiceKm?.(p,odo)||state.bike.nextServiceKm};if(changed){state.bike.serviceHistory=[];state.bike.manual={status:'none',name:'',analysis:null}}state.profile.bikeConfigured=true;save();modalLocked=false;if(gate)openManualGate();else{closeModal();toast('Motorcycle updated')}};
function openManualGate(){openModal(`<div class="modalhead"><div><div class="kicker">OWNER'S MANUAL</div><h3>Add your motorcycle manual</h3></div></div><div class="card notice"><strong>Why Rider Hub asks for it</strong><p class="caption">The owner's manual lets Rider Hub look for model-specific specifications, maintenance intervals and service milestones instead of guessing. Your original file can be backed up to your own Google Drive after you connect Drive.</p></div><div class="modal-actions"><button class="ghost" onclick="finishBikeSetup()">Skip / do later</button><button class="primary" onclick="chooseOwnerManual(true)">Upload Owner's Manual</button></div>`,{locked:true})}
window.finishBikeSetup=()=>{modalLocked=false;closeModal();setPage('home');window.riderHubCloudSave?.(clone(state));toast('Rider Hub is ready')};
function openOwnerManual(){const m=state.bike.manual||{status:'none'};openModal(`<div class="modalhead"><div><div class="kicker">OWNER'S MANUAL</div><h3>${m.name?esc(m.name):'Add Owner\'s Manual'}</h3><p class="caption">Rider Hub uses searchable manual text only for high-confidence motorcycle data. It never guesses values from unreadable pages.</p></div><button class="iconbtn" onclick="closeModal()">×</button></div>${m.analysis?manualAnalysisHtml(m.analysis):''}<div class="modal-actions"><button class="ghost" onclick="openStoredManual()">${m.name?'Open saved manual':'Choose later'}</button><button class="primary" onclick="chooseOwnerManual(false)">${m.name?'Replace manual':'Upload manual'}</button></div>`)}window.openOwnerManual=openOwnerManual;
function manualAnalysisHtml(a){const fields=Object.entries(a.fields||{});return`<div class="card list" style="margin-top:10px">${fields.map(([k,v])=>`<div class="listrow"><div class="ico">✓</div><div><strong>${esc(k)}</strong><p>${esc(v.value)}${v.page?' · page '+v.page:''}</p></div><span class="pill good">MANUAL</span></div>`).join('')||'<div class="listrow"><div class="ico">i</div><div><strong>Manual saved</strong><p>No high-confidence specifications were extracted automatically.</p></div></div>'}</div>`}
window.chooseOwnerManual=gate=>{let input=$('#ownerManualInput');if(!input){input=document.createElement('input');input.type='file';input.accept='application/pdf';input.id='ownerManualInput';input.hidden=true;document.body.appendChild(input)}input.onchange=async()=>{const f=input.files?.[0];if(!f)return;await processOwnerManual(f,gate)};input.value='';input.click()};
async function processOwnerManual(file,gate){try{toast('Reading owner manual…');await window.savePrivateDoc?.('owner_manual',file);const a=await window.riderHubProcessOwnerManual?.(file);state.bike.manual={status:a?.status||'saved',name:file.name,analysis:a||null};for(const [k,v] of Object.entries(a?.fields||{})){if(['engine','braking','transmission','fuelTank','tyres'].includes(k)&&v?.value)state.bike[k]=v.value;if(k==='chainIntervalKm'&&v?.value)state.bike.chainIntervalKm=Number(v.value)}if(a?.serviceMilestones?.length)state.bike.serviceMilestones=a.serviceMilestones;save();if(gate)finishBikeSetup();else{closeModal();toast(a?.status==='scanned'?'Manual saved · scanned PDF not auto-read':'Owner manual processed')}}catch(e){toast(e?.message||'Could not process manual')}}
window.openStoredManual=async()=>{const f=await window.getPrivateDoc?.('owner_manual');if(!f)return toast('No saved manual on this device');window.open(URL.createObjectURL(f),'_blank','noopener')};
function docsList(){return[{id:'licence',name:'Rider licence',desc:'Driving or learner licence'},{id:'insurance',name:'Insurance',desc:'Motorcycle insurance policy'}]}
function documentsHtml(){return`<div class="card list">${docsList().map(d=>docRow(d)).join('')}<div class="listrow" onclick="openMoreDocuments()" style="cursor:pointer"><div class="ico">•••</div><div><strong>More documents</strong><p>Registration / RC, PUC, invoice, warranty and service invoices</p></div><span>›</span></div><div class="listrow" onclick="addCustomDocument()" style="cursor:pointer"><div class="ico">＋</div><div><strong>Add custom document</strong><p>Name and store any other private document.</p></div><span>›</span></div>${(state.documents.custom||[]).map(d=>docRow(d,true)).join('')}</div>`}
function docRow(d,custom=false){return`<div class="listrow" onclick="openDoc('${esc(d.id)}','${custom?'1':'0'}')" style="cursor:pointer"><div class="ico">▤</div><div><strong>${esc(d.name)}</strong><p>${esc(d.desc||'Private document')}</p></div><span class="pill good">PRIVATE</span></div>`}
window.openMoreDocuments=()=>openModal(`<div class="modalhead"><div><div class="kicker">DOCUMENTS</div><h3>More documents</h3></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="card list">${[{id:'registration_rc',name:'Registration / RC',desc:'Registration certificate'},{id:'puc',name:'PUC / emissions',desc:'Pollution under control certificate'},{id:'vehicle_invoice',name:'Purchase invoice',desc:'Vehicle purchase invoice or receipt'},{id:'warranty',name:'Warranty',desc:'Manufacturer or extended warranty'},{id:'service_invoice',name:'Service invoices',desc:'Workshop and service bills'}].map(d=>docRow(d)).join('')}</div>`);
window.addCustomDocument=()=>openModal(`<div class="modalhead"><div><div class="kicker">CUSTOM DOCUMENT</div><h3>Add document</h3></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="field"><label>DOCUMENT NAME</label><input id="customDocName" placeholder="Roadside assistance card"></div><div class="field"><label>DESCRIPTION · OPTIONAL</label><input id="customDocDesc"></div><div class="modal-actions"><button class="ghost" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveCustomDocument()">Continue</button></div>`);
window.saveCustomDocument=()=>{const name=$('#customDocName')?.value.trim();if(!name)return toast('Add a document name');const d={id:'custom_'+Date.now().toString(36),name,desc:$('#customDocDesc')?.value.trim()||'Custom private document'};state.documents.custom.push(d);save();closeModal();setTimeout(()=>openDoc(d.id,'1'),30)};
window.openDoc=(id,customFlag='0')=>{const standard=[...docsList(),{id:'registration_rc',name:'Registration / RC',desc:'Registration certificate'},{id:'puc',name:'PUC / emissions',desc:'Pollution under control certificate'},{id:'vehicle_invoice',name:'Purchase invoice',desc:'Vehicle purchase invoice or receipt'},{id:'warranty',name:'Warranty',desc:'Manufacturer or extended warranty'},{id:'service_invoice',name:'Service invoices',desc:'Workshop and service bills'}],d=customFlag==='1'?state.documents.custom.find(x=>x.id===id):standard.find(x=>x.id===id);if(!d)return;openModal(`<div class="modalhead"><div><div class="kicker">PRIVATE DOCUMENT</div><h3>${esc(d.name)}</h3><p class="caption">${esc(d.desc||'')}</p></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="card notice"><strong>Storage</strong><p class="caption">Saved on this device. After Google Drive is connected, Rider Hub backs the file up to My Drive / Rider Hub / Documents.</p></div><div class="modal-actions"><button class="ghost" onclick="openPrivateDocument('${esc(id)}')">Open</button><button class="primary" onclick="pickPrivateDocument('${esc(id)}')">Attach / replace</button></div>`)};
window.pickPrivateDocument=id=>{let input=$('#privateDocInput');if(!input){input=document.createElement('input');input.type='file';input.id='privateDocInput';input.hidden=true;document.body.appendChild(input)}input.onchange=async()=>{const f=input.files?.[0];if(!f)return;await window.savePrivateDoc?.(id,f);toast(window.cloudSyncConnected?.()?'Saved and backed up to Drive':'Saved on this device')};input.value='';input.click()};
window.openPrivateDocument=async id=>{const f=await window.getPrivateDoc?.(id);if(!f)return toast('No file attached yet');window.open(URL.createObjectURL(f),'_blank','noopener')};
function openDb(){return new Promise((res,rej)=>{const q=indexedDB.open(DB_NAME,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains('docs'))q.result.createObjectStore('docs')};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
window.savePrivateDoc=async(key,file)=>{const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction('docs','readwrite');tx.objectStore('docs').put(file,key);tx.oncomplete=()=>{db.close();res(true)};tx.onerror=()=>rej(tx.error)})};
window.getPrivateDoc=async key=>{const db=await openDb();return new Promise((res,rej)=>{const q=db.transaction('docs').objectStore('docs').get(key);q.onsuccess=()=>{db.close();res(q.result||null)};q.onerror=()=>rej(q.error)})};
window.deletePrivateDoc=async key=>{const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction('docs','readwrite');tx.objectStore('docs').delete(key);tx.oncomplete=()=>{db.close();res(true)};tx.onerror=()=>rej(tx.error)})};
function rideProgress(r){let total=0,done=0;for(const d of r.days)for(const t of d.tasks){total++;if(['done','skipped'].includes(t.status))done++}return total?Math.round(done/total*100):0}
function renderRides(){const current=state.ui.rideId&&state.rides.find(r=>r.id===state.ui.rideId);if(current)return renderRideDetail(current);const planned=state.rides.filter(r=>r.status!=='completed'),completed=state.rides.filter(r=>r.status==='completed');$('#rides').innerHTML=`<div class="section-head"><div><div class="kicker">MY RIDES</div><h2>Plan. Ride. Remember.</h2></div><button class="primary" onclick="addRide()">+ Add ride</button></div><div class="grid3"><div class="card notice"><div class="kicker">PLANNED</div><h2>${planned.length}</h2><div class="caption">rides</div></div><div class="card notice"><div class="kicker">COMPLETED</div><h2>${completed.length}</h2><div class="caption">rides</div></div><div class="card notice"><div class="kicker">DAYS PLANNED</div><h2>${state.rides.reduce((a,r)=>a+r.days.length,0)}</h2><div class="caption">across all rides</div></div></div><div class="rides-layout" style="margin-top:12px">${state.rides.map(r=>`<div class="card ride-card" onclick="openRide('${r.id}')"><div class="between"><div><div class="kicker">${r.status==='completed'?'COMPLETED':'PLANNED'}</div><h3>${esc(r.name)}</h3><div class="caption">${r.days.length} day${r.days.length===1?'':'s'} · ${fmtDate(r.start)}${r.end&&r.end!==r.start?' → '+fmtDate(r.end):''}</div></div><span class="pill ${r.status==='completed'?'good':'warn'}">${rideProgress(r)}%</span></div><div class="progress" style="margin-top:13px"><i style="width:${rideProgress(r)}%"></i></div></div>`).join('')||'<div class="card notice"><strong>No rides yet</strong><p class="caption">Create a 1-day ride, a 20-day tour, or anything in between.</p></div>'}</div>`}
window.openRide=id=>{state.ui.rideId=id;const r=state.rides.find(x=>x.id===id);if(r)r.selectedDay=Math.max(0,Math.min(r.days.length-1,r.selectedDay||0));persistLocal();renderRides();window.scrollTo(0,0)};
window.closeRide=()=>{state.ui.rideId='';persistLocal();renderRides()};
function renderRideDetail(r){const d=r.days[r.selectedDay]||r.days[0];$('#rides').innerHTML=`<button class="ghost" onclick="closeRide()">‹ My rides</button><div class="card ride-detail-top" style="margin-top:10px"><div class="kicker">${r.days.length} DAY${r.days.length===1?'':'S'}</div><h1>${esc(r.name)}</h1><div class="caption">${fmtDate(r.start)}${r.end&&r.end!==r.start?' → '+fmtDate(r.end):''}</div><div class="progress" style="margin-top:13px"><i style="width:${rideProgress(r)}%"></i></div></div><div class="section-head"><div><div class="kicker">CHOOSE DAY</div><h2>Ride plan</h2></div><button class="primary" onclick="openRideMode('${r.id}')">Start Ride Mode</button></div><div class="daytabs">${r.days.map((x,i)=>`<button class="daytab ${i===r.selectedDay?'active':''}" onclick="selectRideDay('${r.id}',${i})">Day ${i+1}${x.date?' · '+fmtDate(x.date).replace(/, \d{4}$/,''):''}</button>`).join('')}</div><div class="rides-layout detail" style="margin-top:12px"><div><div class="card notice"><div class="between"><div><div class="kicker">DAY ${r.selectedDay+1}</div><h2 style="margin:5px 0">${esc(d.title||`Day ${r.selectedDay+1}`)}</h2><div class="caption">${esc([d.from,d.to].filter(Boolean).join(' → '))}</div></div><button class="ghost" onclick="editRideDay('${r.id}',${r.selectedDay})">Edit day</button></div></div><div class="section-head"><div><div class="kicker">SCHEDULE</div><h2>Timeline</h2></div><button class="ghost" onclick="addRideTask('${r.id}',${r.selectedDay})">+ Task</button></div><div class="card" style="padding:14px"><div class="timeline">${d.tasks.length?d.tasks.map((t,i)=>taskHtml(r,d,t,i)).join(''):'<div class="caption">No tasks yet. Add the first stop or task for this day.</div>'}</div></div></div><div><div class="section-head"><div><div class="kicker">MAP</div><h2>Route parts</h2></div><button class="ghost" onclick="addRoutePart('${r.id}',${r.selectedDay})">+ Route</button></div><div class="map-list">${d.segments.length?d.segments.map((s,i)=>mapRow(r,d,s,i)).join(''):'<div class="card notice"><strong>No route parts yet</strong><p class="caption">Add origin, destination and optional waypoints. Maps opens in motorcycle/two-wheeler mode where Google supports it.</p></div>'}</div></div></div>`}
function taskHtml(r,d,t,i){return`<div class="task ${esc(t.status)}"><time>${esc(t.time||'—')}</time><div><strong>${esc(t.title)}</strong><p>${esc(t.note||'')}${t.delay?` · delayed ${t.delay} min`:''}</p></div><button onclick="taskMenu('${r.id}',${d.day-1},${i})">${esc((t.status||'upcoming').toUpperCase())}</button></div>`}
function mapsUrl(s){const q=new URLSearchParams({api:'1',origin:s.origin||'',destination:s.destination||'',travelmode:'two-wheeler',dir_action:'navigate'});if(s.waypoints?.length)q.set('waypoints',s.waypoints.join('|'));return'https://www.google.com/maps/dir/?'+q.toString()}
function mapRow(r,d,s,i){return`<div class="map-row"><div class="between"><strong>${esc(s.label||`Route ${i+1}`)}</strong><button class="primary" onclick="openMap('${r.id}',${d.day-1},${i})">Navigate</button></div><p>${esc([s.origin,...(s.waypoints||[]),s.destination].filter(Boolean).join(' → '))}</p></div>`}
window.openMap=(rideId,dayIndex,segIndex)=>{const r=state.rides.find(x=>x.id===rideId),s=r?.days?.[dayIndex]?.segments?.[segIndex];if(s)window.open(mapsUrl(s),'_blank','noopener')};
window.selectRideDay=(id,i)=>{const r=state.rides.find(x=>x.id===id);if(!r)return;r.selectedDay=Math.max(0,Math.min(r.days.length-1,i));save()};
window.addRide=()=>openModal(`<div class="modalhead"><div><div class="kicker">NEW RIDE</div><h3>Create ride</h3><p class="caption">Any length works — one day, a weekend, or a long tour.</p></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="field"><label>RIDE NAME</label><input id="rideName" placeholder="Weekend ride"></div><div class="grid2"><div class="field"><label>START DATE</label><input id="rideStart" type="date" value="${today()}"></div><div class="field"><label>NUMBER OF DAYS</label><input id="rideDays" inputmode="numeric" value="1"></div></div><div class="field"><label>START / HOME</label><input id="rideFrom" placeholder="Ahmedabad"></div><div class="field"><label>FINAL DESTINATION</label><input id="rideTo" placeholder="Destination"></div><div class="modal-actions"><button class="ghost" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveNewRide()">Create ride</button></div>`);
window.saveNewRide=()=>{const name=$('#rideName')?.value.trim();if(!name)return toast('Add a ride name');const start=$('#rideStart')?.value||today(),count=Math.max(1,Math.min(60,Math.round(Number($('#rideDays')?.value||1)))),from=$('#rideFrom')?.value.trim()||'',to=$('#rideTo')?.value.trim()||'',days=Array.from({length:count},(_,i)=>({day:i+1,date:addDays(start,i),title:count===1?`${from||'Start'} → ${to||'Destination'}`:`Day ${i+1}`,from:i===0?from:'',to:i===count-1?to:'',segments:[],tasks:[]}));const r=normalizeRide({id:'ride_'+Date.now().toString(36),name,start,end:addDays(start,count-1),days});state.rides.unshift(r);state.ui.rideId=r.id;save();closeModal();renderRides();toast('Ride created')};
window.editRideDay=(rideId,di)=>{const r=state.rides.find(x=>x.id===rideId),d=r?.days?.[di];if(!d)return;openModal(`<div class="modalhead"><div><div class="kicker">DAY ${di+1}</div><h3>Edit ride day</h3></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="field"><label>TITLE</label><input id="dayTitle" value="${esc(d.title)}"></div><div class="field"><label>DATE</label><input id="dayDate" type="date" value="${esc(d.date)}"></div><div class="grid2"><div class="field"><label>FROM</label><input id="dayFrom" value="${esc(d.from)}"></div><div class="field"><label>TO</label><input id="dayTo" value="${esc(d.to)}"></div></div><div class="modal-actions"><button class="ghost" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveRideDay('${rideId}',${di})">Save day</button></div>`)};
window.saveRideDay=(rideId,di)=>{const d=state.rides.find(x=>x.id===rideId)?.days?.[di];if(!d)return;d.title=$('#dayTitle')?.value.trim()||`Day ${di+1}`;d.date=$('#dayDate')?.value||d.date;d.from=$('#dayFrom')?.value.trim()||'';d.to=$('#dayTo')?.value.trim()||'';save();closeModal()};
window.addRideTask=(rideId,di)=>openModal(`<div class="modalhead"><div><div class="kicker">SCHEDULE</div><h3>Add task</h3></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="grid2"><div class="field"><label>TIME</label><input id="taskTime" type="time"></div><div class="field"><label>TITLE</label><input id="taskTitle" placeholder="Fuel stop"></div></div><div class="field"><label>NOTE</label><input id="taskNote"></div><div class="modal-actions"><button class="ghost" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveRideTask('${rideId}',${di})">Add task</button></div>`);
window.saveRideTask=(rideId,di)=>{const d=state.rides.find(x=>x.id===rideId)?.days?.[di],title=$('#taskTitle')?.value.trim();if(!d||!title)return toast('Add a task title');d.tasks.push({time:$('#taskTime')?.value||'',title,note:$('#taskNote')?.value.trim()||'',status:'upcoming',delay:0});d.tasks.sort((a,b)=>String(a.time).localeCompare(String(b.time)));save();closeModal()};
window.addRoutePart=(rideId,di)=>openModal(`<div class="modalhead"><div><div class="kicker">MAP</div><h3>Add route part</h3></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="field"><label>LABEL</label><input id="segLabel" placeholder="Morning route"></div><div class="field"><label>ORIGIN</label><input id="segOrigin"></div><div class="field"><label>DESTINATION</label><input id="segDest"></div><div class="field"><label>WAYPOINTS · one per line</label><textarea id="segWaypoints"></textarea></div><div class="modal-actions"><button class="ghost" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveRoutePart('${rideId}',${di})">Add route</button></div>`);
window.saveRoutePart=(rideId,di)=>{const d=state.rides.find(x=>x.id===rideId)?.days?.[di],origin=$('#segOrigin')?.value.trim(),destination=$('#segDest')?.value.trim();if(!d||!origin||!destination)return toast('Add origin and destination');d.segments.push({label:$('#segLabel')?.value.trim()||`Route ${d.segments.length+1}`,origin,destination,waypoints:($('#segWaypoints')?.value||'').split('\n').map(x=>x.trim()).filter(Boolean)});save();closeModal()};
window.taskMenu=(rideId,di,ti)=>{const t=state.rides.find(x=>x.id===rideId)?.days?.[di]?.tasks?.[ti];if(!t)return;openModal(`<div class="modalhead"><div><div class="kicker">TASK</div><h3>${esc(t.title)}</h3><p class="caption">${esc(t.time)} · ${esc(t.note)}</p></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="grid3"><button class="primary" onclick="setTaskStatus('${rideId}',${di},${ti},'done')">Done</button><button class="ghost" onclick="delayTask('${rideId}',${di},${ti})">Delay</button><button class="ghost" onclick="setTaskStatus('${rideId}',${di},${ti},'skipped')">Skip</button></div>`)};
window.setTaskStatus=(rideId,di,ti,status)=>{const r=state.rides.find(x=>x.id===rideId),t=r?.days?.[di]?.tasks?.[ti];if(!t)return;t.status=status;t.delay=0;autoAdvance(r,di);save();closeModal();if($('#rideMode').classList.contains('open'))renderRideMode(r)};
window.delayTask=(rideId,di,ti)=>openModal(`<div class="modalhead"><div><div class="kicker">DELAY</div><h3>Delay task</h3></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="field"><label>MINUTES</label><input id="delayMinutes" inputmode="numeric" value="30"></div><div class="modal-actions"><button class="ghost" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveTaskDelay('${rideId}',${di},${ti})">Save delay</button></div>`);
window.saveTaskDelay=(rideId,di,ti)=>{const t=state.rides.find(x=>x.id===rideId)?.days?.[di]?.tasks?.[ti];if(!t)return;t.status='delayed';t.delay=Math.max(0,Math.round(Number($('#delayMinutes')?.value||0)));save();closeModal();const r=state.rides.find(x=>x.id===rideId);if($('#rideMode').classList.contains('open'))renderRideMode(r)};
function dayDone(d){return d.tasks.length>0&&d.tasks.every(t=>['done','skipped'].includes(t.status))}
function autoAdvance(r,di){if(!dayDone(r.days[di]))return;if(di<r.days.length-1){r.selectedDay=di+1;toast(`Day ${di+1} complete · Day ${di+2} ready`)}else{r.status='completed';toast('Ride complete')}}
function nextTask(d){return d.tasks.find(t=>!['done','skipped'].includes(t.status))||null}
window.openRideMode=id=>{const r=state.rides.find(x=>x.id===id);if(!r)return;state.ui.rideId=id;$('#rideMode').classList.add('open');renderRideMode(r)};
window.closeRideMode=()=>{$('#rideMode').classList.remove('open');renderRides()};
function renderRideMode(r){const di=r.selectedDay||0,d=r.days[di],n=nextTask(d),done=d.tasks.filter(t=>['done','skipped'].includes(t.status)).length,pct=d.tasks.length?Math.round(done/d.tasks.length*100):0;$('#rideModeInner').innerHTML=`<div class="between"><div><div class="kicker">RIDE MODE · DAY ${di+1} OF ${r.days.length}</div><div class="caption">${esc(d.title)}</div></div><button class="iconbtn" onclick="closeRideMode()">×</button></div><div class="daytabs" style="margin:15px 0">${r.days.map((x,i)=>`<button class="daytab ${i===di?'active':''}" onclick="rideModeDay('${r.id}',${i})">Day ${i+1}</button>`).join('')}</div><div class="ride-now"><div class="kicker">${n?esc(n.time||'NEXT'):'DAY COMPLETE'}</div><h2>${esc(n?.title||'All tasks complete')}</h2><p class="caption">${esc(n?.note||'Move to another day or close Ride Mode.')}</p><div class="progress" style="margin-top:12px"><i style="width:${pct}%"></i></div></div>${n?`<div class="ride-actions"><button class="primary" onclick="rideModeTask('${r.id}',${di},${d.tasks.indexOf(n)},'done')">Done</button><button class="ghost" onclick="delayTask('${r.id}',${di},${d.tasks.indexOf(n)})">Delay</button><button class="ghost" onclick="rideModeTask('${r.id}',${di},${d.tasks.indexOf(n)},'skipped')">Skip</button></div>`:''}<div class="section-head"><div><div class="kicker">TOOLS</div><h2>Ride controls</h2></div></div><div class="toolgrid"><button class="tool" onclick="rideMapMenu('${r.id}')"><b>⌖</b><span>Map</span></button><button class="tool" onclick="openExpenses('${r.id}')"><b>₹</b><span>Expenses</span></button><button class="tool" onclick="openFuel('${r.id}')"><b>⛽</b><span>Fuel log</span></button><button class="tool" onclick="openRideNotes('${r.id}')"><b>✎</b><span>Notes</span></button><button class="tool" onclick="openPacking('${r.id}')"><b>▣</b><span>Packing</span></button><button class="tool" onclick="openEmergency()"><b>SOS</b><span>Emergency</span></button><button class="tool" onclick="rideSummary('${r.id}')"><b>Σ</b><span>Summary</span></button><button class="tool" onclick="tomorrowPreview('${r.id}')"><b>→</b><span>Tomorrow</span></button><button class="tool" onclick="editRideDay('${r.id}',${di})"><b>✎</b><span>Edit day</span></button><button class="tool" onclick="addRideTask('${r.id}',${di})"><b>＋</b><span>Add task</span></button></div><div class="section-head"><div><div class="kicker">DAY ${di+1}</div><h2>Schedule</h2></div></div><div class="card" style="padding:14px"><div class="timeline">${d.tasks.length?d.tasks.map((t,i)=>taskHtml(r,d,t,i)).join(''):'<div class="caption">No tasks for this day yet.</div>'}</div></div>`}
window.rideModeDay=(id,i)=>{const r=state.rides.find(x=>x.id===id);if(!r)return;r.selectedDay=Math.max(0,Math.min(r.days.length-1,i));save();renderRideMode(r)};
window.rideModeTask=(id,di,ti,status)=>{const r=state.rides.find(x=>x.id===id),t=r?.days?.[di]?.tasks?.[ti];if(!t)return;t.status=status;t.delay=0;autoAdvance(r,di);save();renderRideMode(r)};
window.rideMapMenu=id=>{const r=state.rides.find(x=>x.id===id),d=r?.days?.[r.selectedDay];if(!d)return;openModal(`<div class="modalhead"><div><div class="kicker">MAP · DAY ${r.selectedDay+1}</div><h3>Route parts</h3></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="map-list">${d.segments.length?d.segments.map((s,i)=>mapRow(r,d,s,i)).join(''):'<div class="caption">No route parts yet.</div>'}</div>`)};
window.openExpenses=id=>{const r=state.rides.find(x=>x.id===id);if(!r)return;openModal(`<div class="modalhead"><div><div class="kicker">EXPENSES</div><h3>${esc(r.name)}</h3></div><button class="iconbtn" onclick="closeModal()">×</button></div>${['fuel','food','stay','parking','misc'].map(k=>`<div class="field"><label>${k.toUpperCase()} ₹</label><input id="exp_${k}" inputmode="decimal" value="${Number(r.expenses?.[k]||0)}"></div>`).join('')}<div class="modal-actions"><button class="ghost" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveExpenses('${id}')">Save</button></div>`)};
window.saveExpenses=id=>{const r=state.rides.find(x=>x.id===id);if(!r)return;for(const k of['fuel','food','stay','parking','misc'])r.expenses[k]=Number($('#exp_'+k)?.value||0);save();closeModal()};
window.openFuel=id=>{const r=state.rides.find(x=>x.id===id);if(!r)return;openModal(`<div class="modalhead"><div><div class="kicker">FUEL LOG</div><h3>${esc(r.name)}</h3></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="card list">${(r.fuelLogs||[]).map(x=>`<div class="listrow"><div class="ico">⛽</div><div><strong>${Number(x.litres||0).toFixed(2)} L</strong><p>${Number(x.odo||0).toLocaleString('en-IN')} km · ₹${Number(x.cost||0).toFixed(0)}</p></div></div>`).join('')||'<div class="listrow"><div class="ico">＋</div><div><strong>No fuel logs</strong></div></div>'}</div><div class="grid3"><div class="field"><label>LITRES</label><input id="fuelL"></div><div class="field"><label>COST ₹</label><input id="fuelC"></div><div class="field"><label>ODOMETER</label><input id="fuelO" value="${Number(state.bike.odo||0)}"></div></div><button class="primary full" onclick="saveFuel('${id}')">Add fuel log</button>`)};
window.saveFuel=id=>{const r=state.rides.find(x=>x.id===id);if(!r)return;r.fuelLogs=r.fuelLogs||[];r.fuelLogs.push({litres:Number($('#fuelL')?.value||0),cost:Number($('#fuelC')?.value||0),odo:Number($('#fuelO')?.value||0),at:new Date().toISOString()});save();openFuel(id)};
window.openRideNotes=id=>{const r=state.rides.find(x=>x.id===id);if(!r)return;openModal(`<div class="modalhead"><div><div class="kicker">RIDE NOTES</div><h3>${esc(r.name)}</h3></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="field"><textarea id="rideNotes">${esc(r.notes||'')}</textarea></div><button class="primary full" onclick="saveRideNotes('${id}')">Save notes</button>`)};
window.saveRideNotes=id=>{const r=state.rides.find(x=>x.id===id);if(r){r.notes=$('#rideNotes')?.value||'';save();closeModal()}};
window.openPacking=id=>{const r=state.rides.find(x=>x.id===id);if(!r)return;const items=['Documents','Rain gear','First aid','Puncture kit','Tools','Water','Chargers','Spare layer'];r.packing=r.packing||{};openModal(`<div class="modalhead"><div><div class="kicker">PACKING</div><h3>Ride checklist</h3></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="card list">${items.map(x=>`<div class="listrow"><div class="ico">${r.packing[x]?'✓':'○'}</div><div><strong>${x}</strong></div><button class="ghost" onclick="togglePacking('${id}','${x}')">${r.packing[x]?'Packed':'Pack'}</button></div>`).join('')}</div>`)};
window.togglePacking=(id,item)=>{const r=state.rides.find(x=>x.id===id);if(!r)return;r.packing[item]=!r.packing[item];save();openPacking(id)};
window.rideSummary=id=>{const r=state.rides.find(x=>x.id===id);if(!r)return;const spent=Object.values(r.expenses||{}).reduce((a,b)=>a+Number(b||0),0);openModal(`<div class="modalhead"><div><div class="kicker">RIDE SUMMARY</div><h3>${esc(r.name)}</h3></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="grid3"><div class="card notice"><div class="kicker">DAYS</div><h2>${r.days.length}</h2></div><div class="card notice"><div class="kicker">PROGRESS</div><h2>${rideProgress(r)}%</h2></div><div class="card notice"><div class="kicker">SPEND</div><h2>${money(spent)}</h2></div></div>`)};
window.tomorrowPreview=id=>{const r=state.rides.find(x=>x.id===id),n=r?.days?.[(r.selectedDay||0)+1];if(!n)return toast('This is the last ride day');openModal(`<div class="modalhead"><div><div class="kicker">TOMORROW · DAY ${(r.selectedDay||0)+2}</div><h3>${esc(n.title)}</h3><p class="caption">${esc([n.from,n.to].filter(Boolean).join(' → '))}</p></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="card list">${n.tasks.slice(0,6).map(t=>`<div class="listrow"><div class="ico">${esc(t.time||'—')}</div><div><strong>${esc(t.title)}</strong><p>${esc(t.note)}</p></div></div>`).join('')||'<div class="caption">No tasks planned yet.</div>'}</div>`)};
function renderGear(){const q=(state.ui.gearQuery||'').toLowerCase(),status=state.ui.gearStatus||'all',owner=state.ui.gearOwner||'all',items=(state.gear||[]).filter(x=>(status==='all'||x.status===status)&&(owner==='all'||x.owner===owner)&&(!q||`${x.name} ${x.category} ${x.owner} ${x.note||''}`.toLowerCase().includes(q))),owned=(state.gear||[]).filter(x=>x.status==='owned'),planned=(state.gear||[]).filter(x=>x.status==='planned'),owners=[...new Set((state.gear||[]).map(x=>x.owner).filter(Boolean))];$('#gear').innerHTML=`<div class="card hero"><div class="kicker">GEAR GARAGE</div><h1>Your riding inventory</h1><div class="grid2" style="margin-top:20px"><div class="info"><label>OWNED</label><b>${owned.length}</b></div><div class="info"><label>WILL BUY</label><b>${planned.length}</b></div><div class="info"><label>KNOWN SPEND</label><b>${money(owned.reduce((a,x)=>a+Number(x.amount||0),0))}</b></div><div class="info"><label>PLANNED BUDGET</label><b>${money(planned.reduce((a,x)=>a+Number(x.amount||0),0))}</b></div></div></div><div class="section-head"><div><div class="kicker">INVENTORY</div><h2>Gear + accessories</h2></div><button class="primary" onclick="editGear()">+ Add</button></div><div class="gear-toolbar"><div class="field" style="margin:0"><input placeholder="Search gear…" value="${esc(state.ui.gearQuery||'')}" oninput="state.ui.gearQuery=this.value;renderGear()"></div><div class="chips">${[['all','All'],['owned','Bought'],['planned','Will buy']].map(([v,l])=>`<button class="chip ${status===v?'active':''}" onclick="setGearFilter('status','${v}')">${l}</button>`).join('')}</div><div class="chips"><button class="chip ${owner==='all'?'active':''}" onclick="setGearFilter('owner','all')">Everything</button>${owners.map(o=>`<button class="chip ${owner===o?'active':''}" onclick="setGearFilter('owner','${esc(o)}')">${esc(o)}</button>`).join('')}</div></div><div class="card list" style="margin-top:12px">${items.map(x=>`<div class="listrow" onclick="editGear('${x.id}')" style="cursor:pointer"><div class="ico">◇</div><div><strong>${esc(x.name)}</strong><p>${esc(x.owner||'Me')} · ${esc(x.category||'Gear')}</p></div><div style="text-align:right"><b>${money(x.amount)}</b><div><span class="pill ${x.status==='owned'?'good':'warn'}">${x.status==='owned'?'BOUGHT':'WILL BUY'}</span></div></div></div>`).join('')||'<div class="listrow"><div class="ico">＋</div><div><strong>No gear matches</strong></div></div>'}</div>`}window.renderGear=renderGear;
window.setGearFilter=(type,v)=>{state.ui[type==='status'?'gearStatus':'gearOwner']=v;persistLocal();renderGear()};
window.editGear=id=>{const x=(state.gear||[]).find(g=>g.id===id),name=state.profile.name||'Me';openModal(`<div class="modalhead"><div><div class="kicker">GEAR GARAGE</div><h3>${x?'Edit item':'Add item'}</h3></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="field"><label>NAME</label><input id="gearName" value="${esc(x?.name||'')}"></div><div class="grid2"><div class="field"><label>CATEGORY</label><input id="gearCat" value="${esc(x?.category||'Riding Gear')}"></div><div class="field"><label>OWNER</label><input id="gearOwner" value="${esc(x?.owner||name)}"></div></div><div class="grid2"><div class="field"><label>STATUS</label><select id="gearStatus"><option value="owned" ${x?.status==='owned'?'selected':''}>Bought</option><option value="planned" ${x?.status!=='owned'?'selected':''}>Will buy</option></select></div><div class="field"><label>PRICE ₹ · optional</label><input id="gearPrice" value="${x?.amount??''}"></div></div><div class="field"><label>NOTE</label><textarea id="gearNote">${esc(x?.note||'')}</textarea></div><div class="modal-actions">${x?`<button class="danger" onclick="deleteGear('${x.id}')">Delete</button>`:'<button class="ghost" onclick="closeModal()">Cancel</button>'}<button class="primary" onclick="saveGearItem('${x?.id||''}')">Save</button></div>`)};
window.saveGearItem=id=>{const name=$('#gearName')?.value.trim();if(!name)return toast('Add a gear name');const item={id:id||'gear_'+Date.now().toString(36),name,category:$('#gearCat')?.value.trim()||'Gear',owner:$('#gearOwner')?.value.trim()||state.profile.name||'Me',status:$('#gearStatus')?.value||'planned',amount:$('#gearPrice')?.value.trim()===''?null:Number($('#gearPrice')?.value||0),note:$('#gearNote')?.value.trim()||''};if(id){const i=state.gear.findIndex(x=>x.id===id);state.gear[i]={...state.gear[i],...item}}else state.gear.push(item);save();closeModal();toast('Gear saved')};
window.deleteGear=id=>{state.gear=state.gear.filter(x=>x.id!==id);save();closeModal();toast('Gear removed')};
function renderMore(){const drive=window.cloudSyncLabel?.()||'Google Drive · not connected';$('#more').innerHTML=`<div class="card hero"><div class="kicker">MORE</div><h1>Rider Hub</h1><p class="caption">Account, private files and rider utilities.</p><button class="primary" style="margin-top:18px" onclick="installApp()">Install as App</button></div><div class="more-grid" style="margin-top:12px"><button class="more-card" onclick="openAccount()"><b>◉</b><span>My Account</span></button><button class="more-card" onclick="openCloudSetupSafe()"><b>☁</b><span>Files & Drive</span></button><button class="more-card" onclick="openEmergency()"><b>SOS</b><span>Emergency</span></button><button class="more-card" onclick="openBackup()"><b>⇄</b><span>Backup / Import</span></button><button class="more-card" onclick="openAbout()"><b>RH</b><span>About Rider Hub</span></button></div><div class="card notice" style="margin-top:12px"><strong>Private files</strong><p class="caption">${esc(drive)}. When connected, manuals and documents are backed up to your own Google Drive in a visible Rider Hub folder.</p></div>`}
window.renderMore=renderMore;
window.installApp=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else toast('Use your browser menu → Install app / Add to Home screen')};
window.openCloudSetupSafe=()=>typeof window.openCloudSetup==='function'?window.openCloudSetup():toast('Drive connection is still loading');
window.openAccount=()=>openModal(`<div class="modalhead"><div><div class="kicker">MY ACCOUNT</div><h3>${esc(user?.displayName||state.profile.name||'Jayrut')}</h3><p class="caption">${esc(user?.email||state.profile.email||ALLOWED_EMAIL)}</p></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="card notice"><strong>Private beta</strong><p class="caption">This build currently allows only ${ALLOWED_EMAIL} while Rider Hub is being stabilized.</p></div><button class="ghost full" onclick="logoutRiderHub()" style="margin-top:10px">Log out</button><button class="danger full" onclick="confirmDeleteAccount()" style="margin-top:8px">Delete Rider Hub account</button>`);
window.confirmDeleteAccount=()=>openModal(`<div class="modalhead"><div><div class="kicker">DELETE ACCOUNT</div><h3>Permanently delete Rider Hub?</h3></div></div><div class="card notice"><strong>This deletes</strong><p class="caption">Your Rider Hub Firestore state and Firebase account. If Google Drive is connected, Rider Hub will also try to remove its Rider Hub folder. This cannot be undone.</p></div><div class="field"><label>TYPE DELETE</label><input id="deleteConfirm"></div><div class="modal-actions"><button class="ghost" onclick="closeModal()">Cancel</button><button class="danger" onclick="deleteRiderHubAccount()">Delete permanently</button></div>`);
window.deleteRiderHubAccount=()=>{if($('#deleteConfirm')?.value.trim()!=='DELETE')return toast('Type DELETE to confirm');window.riderHubDeleteAccount?.()};
window.logoutRiderHub=()=>window.riderHubLogout?.();
window.openEmergency=()=>openModal(`<div class="modalhead"><div><div class="kicker">EMERGENCY</div><h3>Emergency actions</h3></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="grid2"><button class="danger" onclick="location.href='tel:112'">Call 112</button><button class="ghost" onclick="location.href='tel:108'">Ambulance 108</button></div><button class="primary full" style="margin-top:9px" onclick="shareLocation()">Share current location</button>`);
window.shareLocation=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>{const text=`My current location: https://maps.google.com/?q=${p.coords.latitude},${p.coords.longitude}`;navigator.share?.({text}).catch(()=>{});navigator.clipboard?.writeText(text).then(()=>toast('Location copied'))},()=>toast('Location permission unavailable')):toast('Location is unavailable');
window.openBackup=()=>openModal(`<div class="modalhead"><div><div class="kicker">BACKUP / IMPORT</div><h3>Rider Hub data</h3></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="grid2"><button class="primary" onclick="exportData()">Export JSON</button><button class="ghost" onclick="importData()">Import JSON</button></div><p class="caption" style="margin-top:10px">This backup contains app data, not private document file contents.</p>`);
window.exportData=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='rider-hub-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)};
window.importData=()=>{let input=$('#importStable');if(!input){input=document.createElement('input');input.type='file';input.accept='application/json';input.id='importStable';input.hidden=true;document.body.appendChild(input)}input.onchange=async()=>{try{const raw=JSON.parse(await input.files[0].text());state=migrate(raw);window.state=state;save();closeModal();toast('Backup imported')}catch{toast('Invalid backup file')}};input.value='';input.click()};
window.openAbout=()=>openModal(`<div class="modalhead"><div><div class="kicker">RIDER HUB</div><h3>Your motorcycle companion</h3></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="card notice"><strong>Built to stay simple</strong><p class="caption">Bike ownership, rides, gear, maps and private files in one consistent interface. Private files can be backed up to your own Google Drive.</p></div>`);
function showAuth(){const sh=$('#authShell');sh.classList.add('active');let slide=0;const slides=[{k:'YOUR MOTORCYCLE OS',h:'Everything around your motorcycle, in one place.',p:'Bike information, maintenance, gear and rides stay together without turning the app into a dashboard maze.'},{k:'PRIVATE FILES STAY YOURS',h:'Your documents can live in your own Google Drive.',p:'After you connect Google Drive, Rider Hub can back up manuals, licence, insurance and custom documents to My Drive / Rider Hub. App data stays tied to your Rider Hub account.',highlight:true},{k:'RIDE YOUR WAY',h:'One day or twenty days — Rider Hub adapts to the ride.',p:'Plan any number of days, keep maps and Ride Mode close, and let the app move you forward when a day is complete.'}];function draw(){const s=slides[slide];$('#authStage').innerHTML=`<div class="kicker">${s.k}</div><h1>${s.h}</h1><p>${s.p}</p><div class="auth-features"><div class="auth-feature ${s.highlight?'highlight':''}"><b>${slide===1?'Google Drive backup':'Simple by design'}</b><span>${slide===1?'Drive permission is separate and optional. Rider Hub only asks when you connect Drive.':'Manual steps stay under your control; ride progression stays predictable.'}</span></div><div class="auth-feature"><b>${slide===2?'Any ride length':'Your account'}</b><span>${slide===2?'1 day, 3 days, 20 days — the same ride model works for all of them.':'This private beta is currently limited to your test account.'}</span></div></div><div class="auth-actions">${slide?'<button class="ghost" id="authBack">Back</button>':''}<button class="primary" id="authNext">${slide===2?'Continue with Google':'Next'}</button></div>`;$('#authBack')?.addEventListener('click',()=>{slide--;draw()});$('#authNext').addEventListener('click',()=>{if(slide<2){slide++;draw()}else window.riderHubLogin?.()})}draw()}
function hideAuth(){$('#authShell').classList.remove('active')}
window.riderHubSetUser=(u,cloudState)=>{user=u;state=migrate(cloudState||readLocal()||state);state.profile.email=u?.email||state.profile.email;state.profile.name=u?.displayName||state.profile.name||'Jayrut';window.state=state;persistLocal();hideAuth();render();if(!state.profile.bikeConfigured)setTimeout(()=>openBikeSetup(true),60)};
window.riderHubSignedOut=()=>{user=null;showAuth()};
window.riderHubAuthBlocked=email=>{user=null;showAuth();setTimeout(()=>toast(`Private beta currently allows only ${ALLOWED_EMAIL}`),100)};
window.riderHubAllowedEmail=()=>ALLOWED_EMAIL;
function init(){applyAccent();render();if(!localStorage.getItem(APP_KEY))persistLocal();setTimeout(()=>{if(!window.riderHubFirebaseUser?.())showAuth()},150)}
init();
})();
