import { useState } from 'react'
import { useRiderHub } from '../store/RiderHubProvider'
import { deletePrivateDoc, openPrivateDoc, savePrivateDoc } from '../services/privateDocs'
import { Modal, ModalHead } from './Modal'
import type { DocumentRecord } from '../types'

const money=(n:number)=>`₹${Math.round(n).toLocaleString('en-IN')}`
const FILE_ACCEPT='.pdf,.jpg,.jpeg,.png,.webp,.heic,.heif,.tif,.tiff,.gif,.bmp,.doc,.docx,.odt,.rtf,.txt,application/pdf,image/*,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.oasis.opendocument.text,text/plain'
const MAINTENANCE:Array<[string,string]>=[
 ['Service intervals','1st: 750–1,000 km / 30–45 days · 2nd: 5,500–6,000 km / 6 months · 3rd: 11,500–12,000 km / 12 months · then every 6,000 km / 6 months.'],
 ['Engine + transmission oil','Replace at every scheduled service.'],['Oil filter strainer','Clean at every scheduled service.'],['Oil filter element','Replace at every scheduled service.'],['Spark plug','Replace every 12,000 km.'],['Air cleaner element','Replace every 12,000 km; earlier in dusty conditions.'],['Tappet clearance','Inspect at every scheduled service.'],['Clutch + throttle play','Inspect and adjust at every scheduled service.'],['Steering','Inspect at every service; adjust if required and lubricate every 24,000 km.'],['Front fork oil','Replace every 36,000 km if required for poor function or oil leakage.'],['Front + rear suspension','Inspect for proper functioning at every service.'],['Fasteners','Inspect and tighten at every service.'],['Drive chain','Clean, lubricate and adjust at every service; rider care every 500 km.'],['Chain guide bottom','Inspect and replace if required.'],['Bulbs, horn + switches','Inspect at every service.'],['Battery voltage + terminals','Inspect at every service.'],['Brake effectiveness / leaks','Inspect at every service.'],['Brake pedal shaft','Lubricate at every service.'],['Brake pads, hoses, WSS clamps + brake fluid','Inspect at every service. Replace brake fluid every 21,000 km or 2 years, whichever is earlier.'],['MIL / diagnostics','Scan if the malfunction indicator lamp remains on.'],['Wheel freeness','Inspect at every service and check weekly.'],['Tyre pressure','Inspect at every service; rider check weekly.'],['Centre + side stand pivots','Lubricate at every service.'],['Swing-arm bearings','Clean and lubricate every 24,000 km.'],['Wheel balancing','Inspect and adjust every 12,000 km.']
]

export function BikePage(){
  const {state,updateOdometer}=useRiderHub();const b=state.bike
  const [edit,setEdit]=useState(false),[maintenance,setMaintenance]=useState(false),[doc,setDoc]=useState<DocumentRecord|null>(null),[odo,setOdo]=useState(String(b.currentOdometer)),[armed,setArmed]=useState(false),[fileName,setFileName]=useState('')
  const chainKm=Math.max(0,b.currentOdometer-b.chainLastOdometer)
  const saveOdo=()=>{const v=Math.round(Number(odo));if(!Number.isFinite(v)||v<0)return;if(v<b.currentOdometer&&!armed){setArmed(true);return}updateOdometer(v);setEdit(false);setArmed(false)}
  const openDoc=async()=>{if(!doc)return;if(!await openPrivateDoc(doc.id))setFileName('No file attached yet')}
  const attach=async(file:File|null)=>{if(!doc||!file)return;await savePrivateDoc(doc.id,file);setFileName(file.name)}
  const remove=async()=>{if(!doc)return;await deletePrivateDoc(doc.id);setFileName('Attachment removed')}
  return <>
    <section className="card rideHero"><div className="kicker">MY MOTORCYCLE</div><h1>{b.manufacturer} {b.model}</h1><p>{b.variant} • {b.colour} • {b.year}</p><div className="metrics"><div><label>MASTER ODOMETER</label><div className="odoInline"><b>{b.currentOdometer.toLocaleString('en-IN')} km</b><button className="odoEdit" aria-label="Edit odometer" onClick={()=>{setOdo(String(b.currentOdometer));setEdit(true)}}>✎</button></div></div><div><label>OWNED SINCE</label><b>{b.purchaseDate}</b></div></div></section>
    <div className="sectionHead"><div><div className="kicker">OVERVIEW</div><h2>Bike information</h2></div></div>
    <div className="infoGrid">{[['Manufacturer',b.manufacturer],['Model',b.model],['Variant',b.variant],['Colour',b.colour],['Year',String(b.year)],['Engine',b.engine],['Braking',b.braking],['Transmission',b.transmission],['Fuel tank',b.fuelTank],['Tyres',b.tyres],['Insurance',b.insurance],['Next service',`${b.nextServiceKm.toLocaleString('en-IN')} km or ${b.nextServiceDate}`]].map(([k,v])=><div key={k}><label>{k.toUpperCase()}</label><b>{v}</b></div>)}</div>
    <div className="sectionHead"><div><div className="kicker">MAINTENANCE</div><h2>Maintenance engine</h2></div></div>
    <section className="card list"><div className="listRow"><div className="ico">⛓</div><div><strong>Chain clean + lube</strong><p>{chainKm} km since last care. Reminder begins at 400 km; due by 500 km.</p></div><span className={`pill ${chainKm>500?'due':chainKm>=400?'soon':'good'}`}>{chainKm>500?'OVERDUE':chainKm>=400?'SOON':'GOOD'}</span></div><div className="listRow"><div className="ico">🔧</div><div><strong>Second service</strong><p>5,500–6,000 km or 6 months, whichever comes first.</p></div><span className="pill soon">UPCOMING</span></div><div className="listRow"><div className="ico">🛞</div><div><strong>Tyre pressure</strong><p>Check weekly and before long rides.</p></div><span className="pill good">WEEKLY</span></div></section>
    <button className="maintenanceMore" onClick={()=>setMaintenance(true)}>More maintenance <span>›</span></button>
    <div className="sectionHead"><div><div className="kicker">SERVICE HISTORY</div><h2>Completed work</h2></div></div><section className="card list">{b.serviceHistory.map(x=><div className="listRow" key={x.id}><div className="ico">✓</div><div><strong>{x.name}</strong><p>{x.date} · {x.odometer} km · {x.work}</p></div><b>{money(x.cost)}</b></div>)}</section>
    <div className="sectionHead"><div><div className="kicker">DOCUMENTS</div><h2>Document vault</h2></div></div><section className="card list">{state.documents.map(x=><button className="listRow docRow" key={x.id} onClick={()=>{setDoc(x);setFileName('')}}><div className="ico">▤</div><div><strong>{x.name}</strong><p>{x.summary}</p></div><span className="pill good">SAVED</span></button>)}</section>
    <div className="sectionHead"><div><div className="kicker">DIGILOCKER</div><h2>Verified documents</h2></div></div><section className="card comingSoon">COMING SOON</section>

    <Modal open={edit} onClose={()=>setEdit(false)} title="Update odometer"><ModalHead kicker="MASTER ODOMETER" title="Update reading" onClose={()=>setEdit(false)}/><div className="field"><label>ODOMETER KM</label><input inputMode="numeric" value={odo} onChange={e=>{setOdo(e.target.value);setArmed(false)}}/></div>{armed&&<div className="alert red">This is lower than the current master odometer. Tap Confirm again only if this is a correction.</div>}<div className="modalActions"><button className="secondary" onClick={()=>setEdit(false)}>Close</button><button className="confirm" onClick={saveOdo}>✓ Confirm</button></div></Modal>
    <Modal open={maintenance} onClose={()=>setMaintenance(false)} title="Maintenance"><ModalHead kicker="TVS RONIN" title="Full maintenance schedule" onClose={()=>setMaintenance(false)} desc="Kilometres or time — whichever comes first."/><div className="maintenanceFull">{MAINTENANCE.map(([title,desc],i)=><div className="maintenanceItem" key={title}><div className="maintenanceIndex">{String(i+1).padStart(2,'0')}</div><div><strong>{title}</strong><p>{desc}</p></div></div>)}</div></Modal>
    <Modal open={!!doc} onClose={()=>setDoc(null)} title="Document"><ModalHead kicker="DOCUMENT" title={doc?.name??''} onClose={()=>setDoc(null)} desc={doc?.summary}/>{doc&&<><div className="alert">{doc.detail}</div><div className="docActions"><button className="secondary" onClick={openDoc}>Open file</button><label className="secondary fileButton">Attach / replace<input type="file" accept={FILE_ACCEPT} onChange={e=>void attach(e.target.files?.[0]??null)}/></label><button className="danger" onClick={remove}>Remove attachment</button></div>{fileName&&<div className="caption fileStatus">{fileName}</div>}</>}</Modal>
  </>
}
