import { useCallback, useEffect, useMemo, useState } from 'react'
import { useRiderHub } from '../store/RiderHubProvider'
import type { ExpenseState, Ride, RideDay, RideTask, RideTaskStatus, RouteSegment } from '../types'
import { computeRouteIntel, fetchCurrentWeather, fetchDailyWeather, getMapsDemoKey, googleMapsUrl, saveMapsDemoKey, validateMapsDemoKey, type DailyWeather, type RouteIntel, type WeatherSnapshot } from '../services/googleMaps'
import { openPrivateDoc, savePrivateDoc } from '../services/privateDocs'
import { Modal, ModalHead } from './Modal'

const FILE_ACCEPT='.pdf,.jpg,.jpeg,.png,.webp,.heic,.heif,.tif,.tiff,.gif,.bmp,.doc,.docx,.odt,.rtf,.txt,application/pdf,image/*,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.oasis.opendocument.text,text/plain'
const money=(n:number)=>`₹${Math.round(n).toLocaleString('en-IN')}`
const taskStatus=(r:Ride,t:RideTask)=>r.operations.tasks[t.id]??t.status
const dayProgress=(r:Ride,d:RideDay)=>Math.round(d.tasks.filter(t=>['done','skipped'].includes(taskStatus(r,t))).length/Math.max(1,d.tasks.length)*100)
const spent=(e:ExpenseState)=>Object.values(e).reduce((a,b)=>a+Number(b||0),0)
type Tool='map'|'expenses'|'fuel'|'notes'|'issue'|'packing'|'content'|'backup'|'tomorrow'|'emergency'|'traffic'|'summary'|'dayAudit'|null

type Contact={name:string;number:string}
function parseContacts(values:string[]):Contact[]{return (values||[]).map(raw=>{const [name,number]=String(raw).split('|||');if(number)return{name:name||'Emergency contact',number};const digits=String(raw).match(/\+?[0-9][0-9\s-]{6,}/)?.[0]?.replace(/[^+\d]/g,'')||'';return{name:String(raw).replace(digits,'').replace(/[-–:]/g,'').trim()||'Emergency contact',number:digits}}).filter(x=>x.number).slice(0,3)}
const encodeContacts=(x:Contact[])=>x.slice(0,3).map(c=>`${c.name}|||${c.number}`)

export function RideDetailV2({rideId,onBack}:{rideId:string;onBack:()=>void}){
  const store=useRiderHub();const ride=store.state.rides.find(x=>x.id===rideId)
  const [rideMode,setRideMode]=useState(false),[tool,setTool]=useState<Tool>(null),[mapsSetup,setMapsSetup]=useState(false),[delayTaskId,setDelayTaskId]=useState<string|null>(null)
  if(!ride)return <div className="emptyState">Ride not found.</div>
  const dayIndex=Math.min(ride.operations.selectedDay,ride.days.length-1),day=ride.days[dayIndex]
  const openMode=()=>{setRideMode(true);history.pushState({...history.state,rideMode:true},'',location.href)}
  const closeMode=()=>{if(history.state?.rideMode)history.back();else setRideMode(false)}
  useEffect(()=>{if(!rideMode)return;const pop=()=>setRideMode(false);window.addEventListener('popstate',pop,{once:true});return()=>window.removeEventListener('popstate',pop)},[rideMode])
  useDayEndReminder(ride,day)
  return <>
    <button className="backLink" onClick={onBack}>‹ My rides</button>
    <section className="card rideHero"><div className="kicker">UPCOMING RIDE</div><h1>{ride.name}</h1><p>{ride.startDate} → {ride.endDate} · {ride.riders} riders · TVS Ronin</p><div className="rideModeCta"><button className="primary" onClick={openMode}>Open Ride Mode · Day {day.day}</button><NextTask ride={ride} day={day}/></div><button className="secondary full" onClick={()=>addNextTaskToCalendar(ride,day)}>Add next task to Google Calendar</button></section>
    <WeatherCard day={day} onConnect={()=>setMapsSetup(true)}/>
    <HotelCard ride={ride}/>
    <div className="sectionHead"><div><div className="kicker">CHOOSE DAY</div><h2>Ride plan</h2></div></div>
    <div className="dayTabs">{ride.days.map((x,i)=><button className={i===dayIndex?'active':''} onClick={()=>store.selectRideDay(ride.id,i)} key={x.day}>Day {x.day} · {x.from} → {x.to}</button>)}</div>
    <section className="card dayCard"><div className="row between"><div><div className="kicker">DAY {day.day}</div><h3>{day.title}</h3></div><span className="pill soon">{dayProgress(ride,day)}% DONE</span></div><div className="progress"><i style={{width:`${dayProgress(ride,day)}%`}}/></div><div className="timeline">{day.tasks.map(t=><TaskRow key={t.id} ride={ride} task={t} onDelay={()=>setDelayTaskId(t.id)} onStatus={s=>store.setTask(ride.id,dayIndex,t.id,s)}/>)}</div></section>
    <div className="sectionHead"><div><div className="kicker">TRIP TOOLKIT</div><h2>Ride operations</h2></div></div><ToolGrid onTool={setTool}/>
    {rideMode&&<RideMode ride={ride} dayIndex={dayIndex} onClose={closeMode} onTool={setTool} onDelay={setDelayTaskId}/>} 
    <ToolModal tool={tool} onClose={()=>setTool(null)} ride={ride} dayIndex={dayIndex} onConnectMaps={()=>{setTool(null);setMapsSetup(true)}}/>
    <MapsSetup open={mapsSetup} onClose={()=>setMapsSetup(false)}/>
    <DelayModal open={!!delayTaskId} onClose={()=>setDelayTaskId(null)} onSave={m=>{if(delayTaskId)store.delayTask(ride.id,dayIndex,delayTaskId,m);setDelayTaskId(null)}}/>
  </>
}

function useDayEndReminder(ride:Ride,day:RideDay){useEffect(()=>{const check=()=>{const match=day.endTime.match(/(\d{1,2}):(\d{2})/);if(!match)return;const end=new Date(`${day.date}T${match[1].padStart(2,'0')}:${match[2]}:00`);if(Date.now()<end.getTime())return;const pending=day.tasks.filter(t=>!['done','skipped'].includes(taskStatus(ride,t)));if(!pending.length)return;const key=`rh_day_end_${ride.id}_${day.day}_${day.date}`;if(localStorage.getItem(key))return;localStorage.setItem(key,'1');if(typeof Notification!=='undefined'&&Notification.permission==='granted')new Notification(`Rider Hub · Day ${day.day} review`,{body:`${pending.length} task${pending.length===1?'':'s'} still need a decision.`})};check();const id=window.setInterval(check,60_000);return()=>clearInterval(id)},[ride,day])}
function NextTask({ride,day}:{ride:Ride;day:RideDay}){const next=day.tasks.find(t=>!['done','skipped'].includes(taskStatus(ride,t)));return <div className="countdown"><div className="kicker">NEXT</div><b>{next?.time??'DONE'}</b></div>}
function TaskRow({ride,task,onDelay,onStatus}:{ride:Ride;task:RideTask;onDelay:()=>void;onStatus:(s:RideTaskStatus)=>void}){const s=taskStatus(ride,task),delay=ride.operations.delays[task.id];return <div className={`task ${s}`}><time>{task.time}</time><div><strong>{task.title}</strong><p>{task.desc}{delay?` · delayed ${delay} min`:''}</p></div><button onClick={onDelay}>{s.toUpperCase()}</button><div className="taskQuick"><button onClick={()=>onStatus('done')}>Done</button><button onClick={onDelay}>Delay</button><button onClick={()=>onStatus('skipped')}>Skip</button></div></div>}

function addNextTaskToCalendar(ride:Ride,day:RideDay){const next=day.tasks.find(t=>!['done','skipped'].includes(taskStatus(ride,t)));if(!next)return;const m=next.time.match(/(\d{1,2}):(\d{2})/);if(!m)return;const start=new Date(`${day.date}T${m[1].padStart(2,'0')}:${m[2]}:00`),end=new Date(start.getTime()+45*60_000),fmt=(d:Date)=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');const q=new URLSearchParams({action:'TEMPLATE',text:`Rider Hub · ${next.title}`,dates:`${fmt(start)}/${fmt(end)}`,details:`Day ${day.day}: ${next.desc}`,location:day.to});window.open(`https://calendar.google.com/calendar/render?${q}`,'_blank','noopener')}

function WeatherCard({day,onConnect}:{day:RideDay;onConnect:()=>void}){const [current,setCurrent]=useState<WeatherSnapshot|null>(null),[daily,setDaily]=useState<DailyWeather[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');const connected=!!getMapsDemoKey();const refresh=useCallback(async()=>{if(!getMapsDemoKey())return onConnect();setLoading(true);setError('');try{const [c,d]=await Promise.all([fetchCurrentWeather(),fetchDailyWeather()]);setCurrent(c);setDaily(d)}catch(e){setError(e instanceof Error?e.message:'Weather unavailable')}finally{setLoading(false)}},[onConnect]);useEffect(()=>{if(getMapsDemoKey())void refresh()},[refresh]);const f=daily.find(x=>x.date===day.date);return <section className="card weatherCard"><div className="weatherTop"><div><div className="kicker">LIVE WEATHER</div>{current?<><div className="weatherBig">{Math.round(current.temperature??0)}°C</div><div className="weatherStatus">Banswara · {current.description} · updated {new Date(current.updatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</div></>:<><strong>{connected?'Weather loading…':'Weather not connected'}</strong>{!connected&&<div className="caption">Connect once to load live Banswara weather.</div>}</>}</div><button className="secondary" onClick={refresh} disabled={loading}>{connected?(loading?'Refreshing…':'Refresh'):'Connect'}</button></div>{f&&<div className="grid3 weatherGrid"><div className="tile"><label>DAY {day.day} RAIN RISK</label><b>{f.rainChance==null?'—':`${f.rainChance}%`}</b></div><div className="tile"><label>EXPECTED HIGH</label><b>{f.max==null?'—':`${Math.round(f.max)}°`}</b></div><div className="tile"><label>EXPECTED LOW</label><b>{f.min==null?'—':`${Math.round(f.min)}°`}</b></div></div>}{current&&<div className="weatherFacts"><span>Feels {current.feelsLike==null?'—':`${Math.round(current.feelsLike)}°`}</span><span>Humidity {current.humidity??'—'}%</span><span>Wind {current.windKph==null?'—':`${Math.round(current.windKph)} km/h`}</span><span>Thunder {current.thunderChance??'—'}%</span></div>}{f?.rainChance!=null&&f.rainChance>=60&&<div className="alert red">High rain probability. Re-check road conditions before departure and use the wet-weather route if needed.</div>}{error&&<div className="alert red">Weather could not refresh. {error}</div>}</section>}

function HotelCard({ride}:{ride:Ride}){const [attach,setAttach]=useState(false),[name,setName]=useState('');if(!ride.hotel)return null;const h=ride.hotel;const open=async()=>{if(!await openPrivateDoc('hotelBooking'))setAttach(true)};return <><section className="card booking"><div className="row between"><div><div className="kicker">STAY CONFIRMED</div><h3>{h.name}</h3><div className="caption">28–30 Aug · {h.nights} nights · {h.room} · {money(h.paid)} paid</div></div><span className="pill good">PAID</span></div><div className="bookingActions"><button className="secondary" onClick={open}>Open booking</button><button className="secondary" onClick={()=>window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(h.address)}`,'_blank','noopener')}>Map hotel</button></div></section><Modal open={attach} onClose={()=>setAttach(false)} title="Attach booking"><ModalHead kicker="HOTEL BOOKING" title="Attach booking file" onClose={()=>setAttach(false)}/><label className="filePicker"><span>Choose file</span><input type="file" accept={FILE_ACCEPT} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setName(f.name);await savePrivateDoc('hotelBooking',f)}}/></label><div className="caption">{name||'No file selected'}</div><div className="modalActions"><button className="secondary" onClick={()=>setAttach(false)}>Close</button><button className="confirm" onClick={()=>setAttach(false)}>✓ Done</button></div></Modal></>}

function ToolGrid({onTool}:{onTool:(t:Tool)=>void}){const tools:Array<[string,string,Tool]>=[['📝','Notes','notes'],['⚠','Bike issue','issue'],['◉','Content','content'],['☁','Media backup','backup'],['▣','Packing','packing'],['→','Tomorrow','tomorrow'],['SOS','Emergency','emergency'],['↕','Traffic','traffic'],['✓','Day review','dayAudit'],['Σ','Ride Summary','summary']];return <div className="toolGrid rideToolkit">{tools.map(([i,l,t])=><button className="tool" key={l} onClick={()=>onTool(t)}><b>{i}</b><span>{l}</span></button>)}</div>}

function RideMode({ride,dayIndex,onClose,onTool,onDelay}:{ride:Ride;dayIndex:number;onClose:()=>void;onTool:(t:Tool)=>void;onDelay:(id:string)=>void}){const store=useRiderHub();const day=ride.days[dayIndex],cur=day.tasks.find(t=>!['done','skipped'].includes(taskStatus(ride,t)))??null;return <div className="rideMode"><div className="rideModeInner"><header className="rideModeHeader"><div><div className="kicker">RIDE MODE · DAY {day.day}</div><div className="caption">{day.from} → {day.to}</div></div><div className="row"><button className="round" disabled={!store.canUndo} onClick={store.undo}>↶</button><button className="round" onClick={onClose}>×</button></div></header><section className="nowCard"><div className="kicker">{cur?.time??'COMPLETE'} · CURRENT</div><h2>{cur?.title??'Day complete'}</h2><p>{cur?.desc??'All tasks are accounted for.'}</p><div className="progress"><i style={{width:`${dayProgress(ride,day)}%`}}/></div></section>{cur&&<div className="action3"><button className="confirm" onClick={()=>store.setTask(ride.id,dayIndex,cur.id,'done')}>Done</button><button className="secondary" onClick={()=>onDelay(cur.id)}>Delay</button><button className="secondary" onClick={()=>store.setTask(ride.id,dayIndex,cur.id,'skipped')}>Skip</button></div>}<div className="modeTools modeToolsFive"><button onClick={()=>onTool('map')}>⌖<span>Map</span></button><button onClick={()=>onTool('expenses')}>₹<span>Expenses</span></button><button onClick={()=>onTool('fuel')}>⛽<span>Fuel log</span></button><button onClick={()=>onTool('emergency')}>SOS<span>Emergency</span></button><button onClick={()=>onTool('summary')}>Σ<span>Ride Summary</span></button></div><div className="sectionHead"><div><div className="kicker">CHECKS</div><h2>Pre-ride checks</h2></div></div><section className="card preflight">{[['tyres','Tyres','Pressure, condition, puncture kit'],['luggage','Luggage','Straps, balance, exhaust clearance'],['electronics','Electronics','Phone, maps, intercom, Action 5'],['hydration','Rider essentials','Water, gear fit and rest plan']].map(([k,t,s])=>{const key=`${dayIndex}_${k}`,on=!!ride.operations.preflight[key];return <div className="checkRow" key={k}><div><strong>{t}</strong><small>{s}</small></div><button className={on?'on':''} onClick={()=>store.togglePreflight(ride.id,dayIndex,k)}>✓</button></div>})}</section><div className="sectionHead"><div><div className="kicker">DAY TIMELINE</div><h2>Schedule</h2></div></div><section className="card dayCard"><div className="timeline">{day.tasks.map(t=><TaskRow key={t.id} ride={ride} task={t} onDelay={()=>onDelay(t.id)} onStatus={s=>store.setTask(ride.id,dayIndex,t.id,s)}/>)}</div></section></div></div>}

function ToolModal({tool,onClose,ride,dayIndex,onConnectMaps}:{tool:Tool;onClose:()=>void;ride:Ride;dayIndex:number;onConnectMaps:()=>void}){return <Modal open={tool!==null} onClose={onClose} title="Ride tool">{tool==='map'&&<MapTool ride={ride} dayIndex={dayIndex} onClose={onClose}/>} {tool==='expenses'&&<ExpensesTool ride={ride} onClose={onClose}/>} {tool==='fuel'&&<FuelTool ride={ride} onClose={onClose}/>} {tool==='notes'&&<NotesTool ride={ride} onClose={onClose}/>} {tool==='issue'&&<IssueTool ride={ride} onClose={onClose}/>} {tool==='packing'&&<ChecklistTool ride={ride} group="packing" onClose={onClose}/>} {tool==='content'&&<ChecklistTool ride={ride} group="content" onClose={onClose}/>} {tool==='backup'&&<ChecklistTool ride={ride} group="backup" onClose={onClose}/>} {tool==='tomorrow'&&<TomorrowTool ride={ride} dayIndex={dayIndex} onClose={onClose}/>} {tool==='emergency'&&<EmergencyTool ride={ride} onClose={onClose}/>} {tool==='traffic'&&<TrafficTool ride={ride} dayIndex={dayIndex} onClose={onClose} onConnect={onConnectMaps}/>} {tool==='summary'&&<SummaryTool ride={ride} dayIndex={dayIndex} onClose={onClose}/>} {tool==='dayAudit'&&<DayReview ride={ride} dayIndex={dayIndex} onClose={onClose}/>}</Modal>}
function MapTool({ride,dayIndex,onClose}:{ride:Ride;dayIndex:number;onClose:()=>void}){const day=ride.days[dayIndex],normal=day.segments.filter(s=>!s.backup),backup=day.segments.filter(s=>s.backup);return <><ModalHead kicker={`DAY ${day.day} MAP`} title="Route parts" onClose={onClose}/>{normal.map(s=><RouteCard key={s.id} segment={s}/>)}{backup.length>0&&<><div className="sectionHead compact"><div><div className="kicker">WET WEATHER</div><h2>Backup route</h2></div></div>{backup.map(s=><RouteCard key={s.id} segment={s}/>)}</>}</>}
function RouteCard({segment}:{segment:RouteSegment}){return <div className="routeCard"><div className="row between"><strong>{segment.label}</strong><button className="secondary" onClick={()=>window.open(googleMapsUrl(segment),'_blank','noopener')}>Open</button></div><p>{[segment.origin,...segment.waypoints,segment.destination].join(' → ')}</p></div>}
function ExpensesTool({ride,onClose}:{ride:Ride;onClose:()=>void}){const store=useRiderHub();const [draft,setDraft]=useState<ExpenseState>({...ride.operations.expenses}),actual=spent(draft),remaining=Math.max(0,ride.budgetMax-actual);return <><ModalHead kicker="EXPENSES" title="Ride spending" onClose={onClose}/><div className="grid3"><div className="tile"><label>ACTUAL SPENT</label><b>{money(actual)}</b></div><div className="tile"><label>HIGH TARGET</label><b>{money(ride.budgetMax)}</b></div><div className="tile"><label>REMAINING</label><b>{money(remaining)}</b></div></div><div className="expenseDraft">{(Object.keys(draft) as Array<keyof ExpenseState>).map(k=><label className="moneyRow" key={k}><span>{k[0].toUpperCase()+k.slice(1)}</span><input inputMode="decimal" value={draft[k]} onChange={e=>setDraft({...draft,[k]:Math.max(0,Number(e.target.value)||0)})}/></label>)}</div><div className="modalActions"><button className="secondary" onClick={onClose}>Close</button><button className="confirm" onClick={()=>{store.commitExpenses(ride.id,draft);onClose()}}>✓ Confirm</button></div></>}
function FuelTool({ride,onClose}:{ride:Ride;onClose:()=>void}){const store=useRiderHub();const [odo,setOdo]=useState(String(store.state.bike.currentOdometer)),[litres,setLitres]=useState(''),[amount,setAmount]=useState('');return <><ModalHead kicker="FUEL" title="Fuel log" onClose={onClose}/><div className="grid2"><div className="field"><label>ODOMETER</label><input inputMode="numeric" value={odo} onChange={e=>setOdo(e.target.value)}/></div><div className="field"><label>LITRES</label><input inputMode="decimal" value={litres} onChange={e=>setLitres(e.target.value)}/></div></div><div className="field"><label>AMOUNT · ₹</label><input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></div><div className="caption">Fuel amount is added automatically to the Fuel expense category.</div><div className="modalActions"><button className="secondary" onClick={onClose}>Close</button><button className="confirm" onClick={()=>{const a=Math.max(0,Number(amount)||0);if(!a)return;store.addFuel(ride.id,Number(odo)||store.state.bike.currentOdometer,Number(litres)||0,a);onClose()}}>✓ Save fuel</button></div><div className="toolList">{ride.operations.fuelLogs.slice().reverse().map(x=><div className="toolRow" key={x.id}><div><strong>{money(x.amount)}</strong><small>{x.odometer} km · {x.litres||'—'} L</small></div></div>)}</div></>}
function NotesTool({ride,onClose}:{ride:Ride;onClose:()=>void}){const store=useRiderHub();const [text,setText]=useState(ride.operations.notes);return <><ModalHead kicker="NOTES" title="Ride notes" onClose={onClose}/><div className="field"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Write a ride note…"/></div><div className="modalActions"><button className="secondary" onClick={onClose}>Close</button><button className="confirm" onClick={()=>{store.setNotes(ride.id,text);onClose()}}>✓ Save</button></div></>}
function IssueTool({ride,onClose}:{ride:Ride;onClose:()=>void}){const store=useRiderHub();const [note,setNote]=useState(''),[severity,setSeverity]=useState<'Monitor'|'Needs attention'|'Stop riding'>('Monitor');return <><ModalHead kicker="BIKE ISSUE" title="Log an issue" onClose={onClose}/><div className="field"><label>ISSUE</label><textarea value={note} onChange={e=>setNote(e.target.value)}/></div><div className="field"><label>SEVERITY</label><select value={severity} onChange={e=>setSeverity(e.target.value as typeof severity)}><option>Monitor</option><option>Needs attention</option><option>Stop riding</option></select></div><button className="confirm full" onClick={()=>{if(!note.trim())return;store.addIssue(ride.id,{note:note.trim(),severity});setNote('')}}>✓ Add issue</button><div className="toolList">{ride.operations.issues.slice().reverse().map(x=><div className="toolRow" key={x.id}><div><strong>{x.severity}</strong><small>{x.note} · {x.odometer} km</small></div></div>)}</div></>}
const CHECKS={packing:{rain:'Rain gear + waterproof bags',firstaid:'First-aid + ORS',puncture:'Puncture kit + inflator',tools:'Basic tools',power:'Power + charging',documents:'DL / RC / insurance / PUC',water:'Water + snacks',socks:'Dry socks / walking shoes'},content:{departure:'Departure shot',mangarh:'Mangarh',chacha:'Chacha Kota',mahi:'Mahi Dam',singhpura:'Singhpura Falls',jagmer:'Jagmer',arthuna:'Arthuna',arrival:'Arrival'},backup:{action5:'Action 5 footage copied',phone:'Phone media backed up',photos:'Favourite photos selected',booking:'Booking available'}} as const
function ChecklistTool({ride,group,onClose}:{ride:Ride;group:'packing'|'content'|'backup';onClose:()=>void}){const store=useRiderHub();return <><ModalHead kicker={group.toUpperCase()} title={group==='packing'?'Packing':group==='content'?'Content tracker':'Media backup'} onClose={onClose}/><div className="toolList">{Object.entries(CHECKS[group]).map(([k,l])=><div className="toolRow" key={k}><strong>{l}</strong><button className={`checkButton ${ride.operations[group][k]?'on':''}`} onClick={()=>store.toggleChecklist(ride.id,group,k)}>✓</button></div>)}</div></>}
function TomorrowTool({ride,dayIndex,onClose}:{ride:Ride;dayIndex:number;onClose:()=>void}){const next=ride.days[dayIndex+1];if(!next)return <><ModalHead kicker="TOMORROW" title="Trip complete" onClose={onClose}/><div className="alert">No next ride day.</div></>;const majors=next.tasks.filter(x=>/Chacha|Mahi|Singhpura|Jagmer|Arthuna|Hotel|Ahmedabad|Mangarh/i.test(x.title)).slice(0,5);return <><ModalHead kicker="TOMORROW" title={next.title} onClose={onClose} desc={`Day ${next.day} · ${next.from} → ${next.to}`}/><div className="grid2"><div className="tile"><label>START</label><b>{next.tasks[0]?.time||'—'}</b></div><div className="tile"><label>DAY END</label><b>{next.endTime}</b></div></div><div className="routeCard"><strong>Key stops</strong><p>{majors.length?majors.map(x=>x.title).join(' → '):'Ride plan ready.'}</p></div><div className="routeCard"><strong>Prepare tonight</strong><p>Fuel · rain layer · charged phone/intercom/camera · documents · water · tyre/chain check.</p></div></>}
function EmergencyTool({ride,onClose}:{ride:Ride;onClose:()=>void}){const store=useRiderHub(),initial=parseContacts(ride.operations.customEmergency),[contacts,setContacts]=useState<Contact[]>(initial),[editing,setEditing]=useState<number|null>(null),[name,setName]=useState(''),[number,setNumber]=useState('');const persist=(next:Contact[])=>{setContacts(next);store.setEmergencyContacts(ride.id,encodeContacts(next))};const edit=(i:number)=>{const x=i>=0?contacts[i]:{name:'',number:''};setEditing(i);setName(x?.name||'');setNumber(x?.number||'')};const save=()=>{const n=number.replace(/[^+\d]/g,'');if(!name.trim()||n.replace(/\D/g,'').length<7)return;const next=[...contacts];if(editing!=null&&editing>=0)next[editing]={name:name.trim(),number:n};else if(next.length<3)next.push({name:name.trim(),number:n});persist(next);setEditing(null)};return <><ModalHead kicker="EMERGENCY" title="Emergency actions" onClose={onClose}/><div className="grid2"><button className="primary" onClick={()=>location.href='tel:112'}>Call 112</button><button className="secondary" onClick={()=>location.href='tel:108'}>Ambulance 108</button></div><button className="secondary full" onClick={shareLocation}>Share current location</button>{editing!==null?<div className="contactEditor"><div className="field"><label>NAME</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Name"/></div><div className="field"><label>PHONE NUMBER</label><input inputMode="tel" value={number} onChange={e=>setNumber(e.target.value)} placeholder="+91…"/></div><div className="grid2"><button className="secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="confirm" onClick={save}>✓ Save</button></div></div>:<><div className="contactList">{contacts.map((x,i)=><div className="contactCard" key={`${x.number}-${i}`}><button className="contactCall" onClick={()=>location.href=`tel:${x.number}`}><span><strong>{x.name}</strong><small>{x.number}</small></span><b>Call</b></button><div className="contactActions"><button onClick={()=>edit(i)}>Edit</button><button onClick={()=>persist(contacts.filter((_,j)=>j!==i))}>Delete</button></div></div>)}</div>{contacts.length<3&&<button className="secondary full" onClick={()=>edit(-1)}>+ Add contact</button>}</>}</>}
function shareLocation(){if(!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(async p=>{const url=`https://maps.google.com/?q=${p.coords.latitude},${p.coords.longitude}`;if(navigator.share)await navigator.share({title:'My Rider Hub location',url});else await navigator.clipboard.writeText(url)},()=>{}, {enableHighAccuracy:true,timeout:12000,maximumAge:15000})}
function TrafficTool({ride,dayIndex,onClose,onConnect}:{ride:Ride;dayIndex:number;onClose:()=>void;onConnect:()=>void}){const parts=ride.days[dayIndex].segments.filter(s=>!s.backup),[index,setIndex]=useState(0),[result,setResult]=useState<RouteIntel|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');const check=async()=>{if(!getMapsDemoKey())return onConnect();setLoading(true);setError('');try{setResult(await computeRouteIntel(parts[index]))}catch(e){setError(e instanceof Error?e.message:'Route check unavailable')}finally{setLoading(false)}};return <><ModalHead kicker="TRAFFIC + ETA" title="Current route" onClose={onClose}/><div className="field"><label>ROUTE PART</label><select value={index} onChange={e=>setIndex(Number(e.target.value))}>{parts.map((x,i)=><option value={i} key={x.id}>{x.label}</option>)}</select></div><button className="primary full" onClick={check}>{loading?'Checking…':'Check route now'}</button>{result&&<div className="alert"><strong>{result.distanceKm.toFixed(0)} km · {Math.round(result.durationMin)} min</strong><br/>{result.notice}</div>}{error&&<div className="alert red">{error}</div>}</>}
function SummaryTool({ride,dayIndex,onClose}:{ride:Ride;dayIndex:number;onClose:()=>void}){const d=ride.days[dayIndex],actual=spent(ride.operations.expenses),pending=d.tasks.filter(t=>!['done','skipped'].includes(taskStatus(ride,t))).length;return <><ModalHead kicker="RIDE SUMMARY" title={`Day ${d.day}`} onClose={onClose}/><div className="grid3"><div className="tile"><label>PROGRESS</label><b>{dayProgress(ride,d)}%</b></div><div className="tile"><label>SPENT</label><b>{money(actual)}</b></div><div className="tile"><label>PENDING</label><b>{pending}</b></div></div><div className="routeCard"><strong>{d.title}</strong><p>{d.from} → {d.to} · {ride.operations.fuelLogs.length} fuel log(s) · {ride.operations.issues.length} bike issue(s)</p></div></>}
function DayReview({ride,dayIndex,onClose}:{ride:Ride;dayIndex:number;onClose:()=>void}){const store=useRiderHub(),d=ride.days[dayIndex],pending=d.tasks.filter(t=>!['done','skipped'].includes(taskStatus(ride,t)));return <><ModalHead kicker={`DAY ${d.day} REVIEW`} title={pending.length?'Unchecked tasks':'Everything checked'} onClose={onClose}/>{pending.length?pending.map(t=><div className="routeCard" key={t.id}><strong>{t.time} · {t.title}</strong><p>{t.desc}</p><div className="grid2"><button className="confirm" onClick={()=>store.setTask(ride.id,dayIndex,t.id,'done')}>Done now</button><button className="secondary" onClick={()=>store.setTask(ride.id,dayIndex,t.id,'skipped')}>Did not do</button></div></div>):<div className="alert">Day {d.day} is fully resolved.</div>}</>}

function MapsSetup({open,onClose}:{open:boolean;onClose:()=>void}){const [key,setKey]=useState(getMapsDemoKey()),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);const connect=async()=>{if(!key.trim())return setStatus('Paste your connection key.');setBusy(true);setStatus('Checking…');try{await validateMapsDemoKey(key.trim());saveMapsDemoKey(key.trim());setStatus('Connected. Live weather and route estimates are ready.')}catch{setStatus('Could not connect. Check the key and try again.')}finally{setBusy(false)}};return <Modal open={open} onClose={onClose} title="Weather & Maps"><ModalHead kicker="WEATHER + MAPS" title="Connect live services" onClose={onClose} desc="Connect once to load live Banswara weather and route estimates."/><div className="field"><label>CONNECTION KEY</label><input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="Paste connection key"/></div>{status&&<div className="inlineNote">{status}</div>}<button className="confirm full" disabled={busy} onClick={connect}>✓ Connect</button></Modal>}
function DelayModal({open,onClose,onSave}:{open:boolean;onClose:()=>void;onSave:(m:number)=>void}){const [m,setM]=useState('30');return <Modal open={open} onClose={onClose} title="Delay"><ModalHead kicker="DELAY" title="How long?" onClose={onClose}/><div className="field"><label>MINUTES</label><input inputMode="numeric" value={m} onChange={e=>setM(e.target.value)}/></div><div className="modalActions"><button className="secondary" onClick={onClose}>Cancel</button><button className="confirm" onClick={()=>onSave(Math.max(0,Math.round(Number(m)||0)))}>✓ Save delay</button></div></Modal>}
