import { useCallback, useEffect, useMemo, useState } from 'react'
import { useRiderHub } from '../store/RiderHubProvider'
import type { ExpenseState, Ride, RideDay, RideTaskStatus, RouteSegment } from '../types'
import { clearMapsDemoKey, computeRouteIntel, fetchCurrentWeather, fetchDailyWeather, getMapsDemoKey, googleMapsUrl, saveMapsDemoKey, validateMapsDemoKey, type DailyWeather, type RouteIntel, type WeatherSnapshot } from '../services/googleMaps'
import { getPrivateDoc, openPrivateDoc, savePrivateDoc } from '../services/privateDocs'
import { Modal, ModalHead } from './Modal'

const money=(n:number)=>`₹${Math.round(n).toLocaleString('en-IN')}`
const taskStatus=(r:Ride,t:{id:string;status:RideTaskStatus})=>r.operations.tasks[t.id]??t.status
const dayProgress=(r:Ride,d:RideDay)=>Math.round(d.tasks.filter(t=>['done','skipped'].includes(taskStatus(r,t))).length/Math.max(1,d.tasks.length)*100)
const spent=(e:ExpenseState)=>Object.values(e).reduce((a,b)=>a+Number(b||0),0)

type Tool='expenses'|'fuel'|'notes'|'issue'|'packing'|'content'|'backup'|'tomorrow'|'emergency'|'traffic'|'summary'|'dayAudit'|null

export function RideDetail({rideId,onBack}:{rideId:string;onBack:()=>void}){
  const store=useRiderHub();const ride=store.state.rides.find(x=>x.id===rideId)
  const [rideMode,setRideMode]=useState(false);const [tool,setTool]=useState<Tool>(null);const [mapsSetup,setMapsSetup]=useState(false);const [delayTaskId,setDelayTaskId]=useState<string|null>(null)
  if(!ride)return <div className="emptyState">Ride not found.</div>
  const dayIndex=Math.min(ride.operations.selectedDay,ride.days.length-1),day=ride.days[dayIndex]
  const openRideMode=()=>{setRideMode(true);history.pushState({...history.state,rideMode:true},'',location.href)}
  const closeRideMode=()=>{if(history.state?.rideMode)history.back();else setRideMode(false)}
  useEffect(()=>{if(!rideMode)return;const pop=()=>{setTool(null);setRideMode(false)};window.addEventListener('popstate',pop,{once:true});return()=>window.removeEventListener('popstate',pop)},[rideMode])
  return <>
    <button className="backLink" onClick={onBack}>‹ My rides</button>
    <section className="card rideHero"><div className="kicker">UPCOMING RIDE</div><h1>{ride.name}</h1><p>{ride.startDate} → {ride.endDate} · {ride.riders} riders · TVS Ronin</p><div className="rideModeCta"><button className="primary" onClick={openRideMode}>Open Ride Mode · Day {day.day}</button><NextTask ride={ride} day={day}/></div></section>
    <WeatherCard day={day} onNeedKey={()=>setMapsSetup(true)}/>
    <HotelCard ride={ride}/>
    <div className="sectionHead"><div><div className="kicker">CHOOSE DAY</div><h2>Ride plan</h2></div></div>
    <div className="dayTabs">{ride.days.map((x,i)=><button className={i===dayIndex?'active':''} onClick={()=>store.selectRideDay(ride.id,i)} key={x.day}>Day {x.day} · {x.from} → {x.to}</button>)}</div>
    <section className="card dayCard"><div className="row between"><div><div className="kicker">DAY {day.day}</div><h3>{day.title}</h3></div><span className="pill soon">{dayProgress(ride,day)}% DONE</span></div><div className="progress"><i style={{width:`${dayProgress(ride,day)}%`}}/></div><div className="timeline">{day.tasks.map(t=><TaskRow key={t.id} ride={ride} task={t} onOpen={()=>setDelayTaskId(t.id)} onStatus={s=>store.setTask(ride.id,dayIndex,t.id,s)}/>)}</div></section>
    <div className="sectionHead"><div><div className="kicker">TRIP TOOLKIT</div><h2>Ride operations</h2></div></div><ToolGrid onTool={setTool}/>
    <div className="sectionHead"><div><div className="kicker">ROUTE</div><h2>Motorcycle route parts</h2></div></div><section className="card routeWrap"><div className="alert">Long routes are deliberately split into 2–3 controlled parts so Google Maps does not silently drop waypoints.</div>{day.segments.map(s=><RouteCard key={s.id} segment={s} onTraffic={()=>{setTool('traffic')}}/>)}</section>
    {rideMode&&<RideMode ride={ride} dayIndex={dayIndex} onClose={closeRideMode} onTool={setTool} onDelay={setDelayTaskId}/>} 
    <ToolModal tool={tool} onClose={()=>setTool(null)} ride={ride} dayIndex={dayIndex} onNeedKey={()=>{setTool(null);setMapsSetup(true)}}/>
    <MapsSetup open={mapsSetup} onClose={()=>setMapsSetup(false)}/>
    <DelayModal open={!!delayTaskId} onClose={()=>setDelayTaskId(null)} onSave={m=>{if(delayTaskId)store.delayTask(ride.id,dayIndex,delayTaskId,m);setDelayTaskId(null)}}/>
  </>
}

function NextTask({ride,day}:{ride:Ride;day:RideDay}){const next=day.tasks.find(t=>!['done','skipped'].includes(taskStatus(ride,t)));return <div className="countdown"><div className="kicker">NEXT</div><b>{next?.time??'DONE'}</b></div>}

function TaskRow({ride,task,onOpen,onStatus}:{ride:Ride;task:RideDay['tasks'][number];onOpen:()=>void;onStatus:(s:RideTaskStatus)=>void}){const s=taskStatus(ride,task),delay=ride.operations.delays[task.id];return <div className={`task ${s}`}><time>{task.time}</time><div><strong>{task.title}</strong><p>{task.desc}{delay?` · delayed ${delay} min`:''}</p></div><button onClick={onOpen}>{s.toUpperCase()}</button><div className="taskQuick"><button onClick={()=>onStatus('done')}>Done</button><button onClick={onOpen}>Delay</button><button onClick={()=>onStatus('skipped')}>Skip</button></div></div>}

function WeatherCard({day,onNeedKey}:{day:RideDay;onNeedKey:()=>void}){
  const [current,setCurrent]=useState<WeatherSnapshot|null>(null),[daily,setDaily]=useState<DailyWeather[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('')
  const refresh=useCallback(async()=>{if(!getMapsDemoKey()){onNeedKey();return}setLoading(true);setError('');try{const [c,d]=await Promise.all([fetchCurrentWeather(),fetchDailyWeather()]);setCurrent(c);setDaily(d)}catch(e){setError(e instanceof Error?e.message:'Weather unavailable')}finally{setLoading(false)}},[onNeedKey])
  useEffect(()=>{void refresh()},[refresh])
  const forecast=daily.find(x=>x.date===day.date)
  return <section className="card weatherCard"><div className="weatherTop"><div><div className="kicker">LIVE WEATHER</div>{current?<><div className="weatherBig">{Math.round(current.temperature??0)}°C</div><div className="weatherStatus">Banswara · {current.description} · updated {new Date(current.updatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</div></>:<strong>{getMapsDemoKey()?'Weather loading…':'Connect Maps Demo Key'}</strong>}</div><button className="secondary" onClick={refresh} disabled={loading}>{loading?'Refreshing…':'Refresh'}</button></div>{forecast&&<div className="grid3 weatherGrid"><div className="tile"><label>DAY {day.day} RAIN RISK</label><b>{forecast.rainChance==null?'—':`${forecast.rainChance}%`}</b></div><div className="tile"><label>EXPECTED HIGH</label><b>{forecast.max==null?'—':`${Math.round(forecast.max)}°`}</b></div><div className="tile"><label>EXPECTED LOW</label><b>{forecast.min==null?'—':`${Math.round(forecast.min)}°`}</b></div></div>}{current&&<div className="weatherFacts"><span>Feels {current.feelsLike==null?'—':`${Math.round(current.feelsLike)}°`}</span><span>Humidity {current.humidity??'—'}%</span><span>Wind {current.windKph==null?'—':`${Math.round(current.windKph)} km/h`}</span><span>Thunder {current.thunderChance??'—'}%</span></div>}{forecast?.rainChance!=null&&forecast.rainChance>=60&&<div className="alert red">High rain probability. Re-check road conditions before departure and use the wet-weather route if needed.</div>}{error&&<div className="alert red">Weather could not refresh. {error}</div>}</section>
}

function HotelCard({ride}:{ride:Ride}){const [attach,setAttach]=useState(false),[name,setName]=useState('');if(!ride.hotel)return null;const h=ride.hotel;const open=async()=>{if(!await openPrivateDoc('hotelBooking'))setAttach(true)};return <><section className="card booking"><div className="row between"><div><div className="kicker">STAY CONFIRMED</div><h3>{h.name}</h3><div className="caption">28–30 Aug · {h.nights} nights · {h.room} · {money(h.paid)} paid</div></div><span className="pill good">PAID</span></div><div className="bookingActions"><button className="secondary" onClick={open}>Open booking</button><button className="secondary" onClick={()=>window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(h.address)}`,'_blank','noopener')}>Map hotel</button></div></section><Modal open={attach} onClose={()=>setAttach(false)} title="Attach booking"><ModalHead kicker="PRIVATE BOOKING PDF" title="Attach original booking once" onClose={()=>setAttach(false)} desc="The file stays only in this browser's private IndexedDB. It is never published to GitHub."/><label className="filePicker"><span>Choose booking PDF</span><input type="file" accept="application/pdf" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setName(f.name);await savePrivateDoc('hotelBooking',f)}}/></label><div className="caption">{name||'No PDF selected'}</div><div className="modalActions"><button className="secondary" onClick={()=>setAttach(false)}>Close</button><button className="confirm" onClick={()=>setAttach(false)}>✓ Done</button></div></Modal></>}

function RouteCard({segment}:{segment:RouteSegment;onTraffic:()=>void}){return <div className="routeCard"><div className="row between"><strong>{segment.label}</strong><button className="secondary" onClick={()=>window.open(googleMapsUrl(segment),'_blank','noopener')}>Open route</button></div><p>{[segment.origin,...segment.waypoints,segment.destination].map((x,i)=><span key={i}>{i+1}. {x}<br/></span>)}</p></div>}

function ToolGrid({onTool}:{onTool:(t:Tool)=>void}){const tools:Array<[string,string,Tool]>=[['₹','Expenses','expenses'],['📝','Notes','notes'],['⛽','Fuel log','fuel'],['⚠','Bike issue','issue'],['◉','Content','content'],['☁','Media backup','backup'],['▣','Packing','packing'],['→','Tomorrow','tomorrow'],['SOS','Emergency','emergency'],['↕','Traffic','traffic'],['✓','Day review','dayAudit'],['Σ','Ride Summary','summary']];return <div className="toolGrid">{tools.map(([i,l,t])=><button className="tool" key={l} onClick={()=>onTool(t)}><b>{i}</b><span>{l}</span></button>)}</div>}

function RideMode({ride,dayIndex,onClose,onTool,onDelay}:{ride:Ride;dayIndex:number;onClose:()=>void;onTool:(t:Tool)=>void;onDelay:(id:string)=>void}){const store=useRiderHub();const day=ride.days[dayIndex],i=day.tasks.findIndex(t=>!['done','skipped'].includes(taskStatus(ride,t))),cur=i>=0?day.tasks[i]:null;return <div className="rideMode"><div className="rideModeInner"><header className="rideModeHeader"><div><div className="kicker">RIDE MODE · DAY {day.day}</div><div className="caption">{day.from} → {day.to}</div></div><div className="row"><button className="round" disabled={!store.canUndo} onClick={store.undo}>↶</button><button className="round" onClick={onClose}>×</button></div></header><section className="nowCard"><div className="kicker">{cur?.time??'COMPLETE'} · CURRENT</div><h2>{cur?.title??'Day complete'}</h2><p>{cur?.desc??'All tasks are accounted for.'}</p><div className="progress"><i style={{width:`${dayProgress(ride,day)}%`}}/></div></section>{cur&&<div className="action3"><button className="confirm" onClick={()=>store.setTask(ride.id,dayIndex,cur.id,'done')}>Done</button><button className="secondary" onClick={()=>onDelay(cur.id)}>Delay</button><button className="secondary" onClick={()=>store.setTask(ride.id,dayIndex,cur.id,'skipped')}>Skip</button></div>}<div className="modeTools"><button onClick={()=>window.open(googleMapsUrl(day.segments.find(s=>!s.backup)??day.segments[0]),'_blank','noopener')}>⌖<span>Map</span></button><button onClick={()=>onTool('expenses')}>₹<span>Expenses</span></button><button onClick={()=>onTool('emergency')}>SOS<span>Emergency</span></button><button onClick={()=>onTool('summary')}>Σ<span>Ride Summary</span></button></div><div className="sectionHead"><div><div className="kicker">CHECKS</div><h2>Pre-ride checks</h2></div></div><section className="card preflight">{[['tyres','Tyres','Pressure, condition, puncture kit'],['luggage','Luggage','Straps, balance, exhaust clearance'],['electronics','Electronics','Phone, maps, intercom, Action 5'],['hydration','Rider essentials','Water, gear fit and rest plan']].map(([k,t,s])=>{const key=`${dayIndex}_${k}`,on=!!ride.operations.preflight[key];return <div className="checkRow" key={k}><div><strong>{t}</strong><small>{s}</small></div><button className={on?'on':''} onClick={()=>store.togglePreflight(ride.id,dayIndex,k)}>✓</button></div>})}</section><div className="sectionHead"><div><div className="kicker">DAY TIMELINE</div><h2>Schedule</h2></div></div><section className="card dayCard"><div className="timeline">{day.tasks.map(t=><TaskRow key={t.id} ride={ride} task={t} onOpen={()=>onDelay(t.id)} onStatus={s=>store.setTask(ride.id,dayIndex,t.id,s)}/>)}</div></section></div></div>}

function DelayModal({open,onClose,onSave}:{open:boolean;onClose:()=>void;onSave:(m:number)=>void}){const [m,setM]=useState('30');return <Modal open={open} onClose={onClose} title="Delay"><ModalHead kicker="DELAY" title="How long?" onClose={onClose} desc="The delay is recorded inside Rider Hub without blindly shifting every hard time."/><div className="field"><label>MINUTES</label><input inputMode="numeric" value={m} onChange={e=>setM(e.target.value)}/></div><div className="modalActions"><button className="secondary" onClick={onClose}>Cancel</button><button className="confirm" onClick={()=>onSave(Math.max(0,Math.round(Number(m)||0)))}>✓ Save delay</button></div></Modal>}

function MapsSetup({open,onClose}:{open:boolean;onClose:()=>void}){const [key,setKey]=useState(getMapsDemoKey()),[status,setStatus]=useState('');const connect=async()=>{if(!key.trim())return setStatus('Paste your Maps Demo Key.');setStatus('Checking key…');try{await validateMapsDemoKey(key.trim());saveMapsDemoKey(key.trim());setStatus('Connected. Weather and route intelligence are ready.')}catch(e){setStatus(`Could not validate this key: ${e instanceof Error?e.message:'unknown error'}`)}};return <Modal open={open} onClose={onClose} title="Maps setup"><ModalHead kicker="₹0 MAPS PROTOTYPE" title="Connect Maps Demo Key" onClose={onClose} desc="Stored only on this device. The key is never committed to GitHub."/><div className="field"><label>MAPS DEMO KEY</label><input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="Paste copied demo key"/></div>{status&&<div className="inlineNote">{status}</div>}<div className="modalActions"><button className="secondary" onClick={()=>{clearMapsDemoKey();setKey('');setStatus('Key removed from this device.')}}>Remove</button><button className="confirm" onClick={connect}>✓ Connect</button></div></Modal>}

function ToolModal({tool,onClose,ride,dayIndex,onNeedKey}:{tool:Tool;onClose:()=>void;ride:Ride;dayIndex:number;onNeedKey:()=>void}){const store=useRiderHub();const day=ride.days[dayIndex];const [draft,setDraft]=useState<ExpenseState>(ride.operations.expenses);const [notes,setNotes]=useState(ride.operations.notes);const [fuel,setFuel]=useState({odo:String(store.state.bike.currentOdometer),litres:'',amount:''});const [issue,setIssue]=useState('');const [severity,setSeverity]=useState<'Monitor'|'Needs attention'|'Stop riding'>('Monitor');const [intel,setIntel]=useState<RouteIntel|null>(null);const [loading,setLoading]=useState(false);const [contacts,setContacts]=useState(ride.operations.customEmergency.length?ride.operations.customEmergency:['','','']);
  useEffect(()=>{setDraft(ride.operations.expenses);setNotes(ride.operations.notes);setContacts([...ride.operations.customEmergency,'','',''].slice(0,3))},[ride.operations.expenses,ride.operations.notes,ride.operations.customEmergency,tool])
  const title=tool==='expenses'?'Expenses':tool==='fuel'?'Fuel log':tool==='notes'?'Notes':tool==='issue'?'Bike issue':tool==='packing'?'Packing':tool==='content'?'Content tracker':tool==='backup'?'Media backup':tool==='tomorrow'?'Tomorrow':tool==='emergency'?'Emergency':tool==='traffic'?'Traffic / route':tool==='dayAudit'?'Day-end review':'Ride Summary'
  return <Modal open={!!tool} onClose={onClose} title={title}><ModalHead kicker="RIDE TOOL" title={title} onClose={onClose}/>{tool==='expenses'&&<><div className="grid3"><Tile l="ACTUAL SPENT" v={money(spent(draft))}/><Tile l="HIGH TARGET" v={money(ride.budgetMax)}/><Tile l="REMAINING" v={money(Math.max(0,ride.budgetMax-spent(draft)))}/></div>{(Object.keys(draft) as Array<keyof ExpenseState>).map(k=><div className="moneyRow" key={k}><strong>{k[0].toUpperCase()+k.slice(1)}</strong><input inputMode="decimal" value={draft[k]||''} onChange={e=>setDraft({...draft,[k]:Math.max(0,Number(e.target.value)||0)})}/></div>)}<div className="modalActions"><button className="secondary" onClick={onClose}>Close</button><button className="confirm" onClick={()=>{store.commitExpenses(ride.id,draft);onClose()}}>✓ Confirm</button></div></>}
    {tool==='fuel'&&<><div className="grid2"><Tile l="FUEL SPEND" v={money(ride.operations.expenses.fuel)}/><Tile l="LOGS" v={String(ride.operations.fuelLogs.length)}/></div><div className="grid2"><div className="field"><label>ODOMETER KM</label><input inputMode="numeric" value={fuel.odo} onChange={e=>setFuel({...fuel,odo:e.target.value})}/></div><div className="field"><label>LITRES</label><input inputMode="decimal" value={fuel.litres} onChange={e=>setFuel({...fuel,litres:e.target.value})}/></div></div><div className="field"><label>AMOUNT ₹</label><input inputMode="decimal" value={fuel.amount} onChange={e=>setFuel({...fuel,amount:e.target.value})}/></div><button className="confirm full" onClick={()=>{store.addFuel(ride.id,Number(fuel.odo),Number(fuel.litres),Number(fuel.amount));setFuel({...fuel,litres:'',amount:''})}}>✓ Add fuel stop</button><div className="miniList">{ride.operations.fuelLogs.slice().reverse().map(x=><div className="routeCard" key={x.id}><strong>{x.odometer} km · {money(x.amount)}</strong><p>{x.litres?`${x.litres} L · `:''}{new Date(x.createdAt).toLocaleString()}</p></div>)}</div></>}
    {tool==='notes'&&<><div className="field"><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></div><div className="modalActions"><button className="secondary" onClick={onClose}>Close</button><button className="confirm" onClick={()=>{store.setNotes(ride.id,notes);onClose()}}>✓ Confirm</button></div></>}
    {tool==='issue'&&<><div className="field"><label>ISSUE</label><input value={issue} onChange={e=>setIssue(e.target.value)} placeholder="Noise, loose strap, warning light…"/></div><div className="field"><label>SEVERITY</label><select value={severity} onChange={e=>setSeverity(e.target.value as typeof severity)}><option>Monitor</option><option>Needs attention</option><option>Stop riding</option></select></div><button className="confirm full" onClick={()=>{if(issue.trim()){store.addIssue(ride.id,{note:issue.trim(),severity});setIssue('')}}}>✓ Save issue</button>{ride.operations.issues.map(x=><div className="routeCard" key={x.id}><strong>{x.severity} · {x.odometer} km</strong><p>{x.note}</p></div>)}</>}
    {(tool==='packing'||tool==='content'||tool==='backup')&&<Checklist group={tool} ride={ride}/>} 
    {tool==='tomorrow'&&<Tomorrow ride={ride} dayIndex={dayIndex}/>} 
    {tool==='emergency'&&<><div className="grid2"><a className="primary buttonLink" href="tel:112">Call 112</a><a className="secondary buttonLink" href="tel:108">Ambulance 108</a></div><button className="secondary full" onClick={shareLocation}>Share current location</button>{contacts.map((x,i)=><div className="field" key={i}><label>CUSTOM CONTACT {i+1}</label><input value={x} onChange={e=>{const n=[...contacts];n[i]=e.target.value;setContacts(n)}} placeholder="Name / number"/></div>)}<button className="confirm full" onClick={()=>store.setEmergencyContacts(ride.id,contacts)}>✓ Save contacts</button></>}
    {tool==='traffic'&&<><div className="alert">Traffic-aware route intelligence uses the no-billing Maps Demo Key when supported. If the demo quota/feature is unavailable, Rider Hub falls back to a basic route estimate instead of inventing live traffic.</div><div className="field"><label>ROUTE PART</label><select id="segmentPick">{day.segments.filter(s=>!s.backup).map((s,i)=><option value={i} key={s.id}>{s.label}</option>)}</select></div><button className="primary full" disabled={loading} onClick={async()=>{if(!getMapsDemoKey()){onNeedKey();return}const idx=Number((document.getElementById('segmentPick') as HTMLSelectElement)?.value||0),seg=day.segments.filter(s=>!s.backup)[idx];setLoading(true);try{setIntel(await computeRouteIntel(seg))}catch(e){setIntel(null);alert(e instanceof Error?e.message:'Route unavailable')}finally{setLoading(false)}}}>{loading?'Checking…':'Check route now'}</button>{intel&&<div className="grid2"><Tile l="DISTANCE" v={`${intel.distanceKm.toFixed(0)} km`}/><Tile l="ETA" v={`${Math.round(intel.durationMin)} min`}/><div className="alert" style={{gridColumn:'1/-1'}}>{intel.notice}</div></div>}<button className="secondary full" onClick={onNeedKey}>{getMapsDemoKey()?'Manage Maps Demo Key':'Connect Maps Demo Key'}</button></>}
    {tool==='summary'&&<div className="grid3"><Tile l="PROGRESS" v={`${dayProgress(ride,day)}%`}/><Tile l="SPENT" v={money(spent(ride.operations.expenses))}/><Tile l="FUEL LOGS" v={String(ride.operations.fuelLogs.length)}/><div className="routeCard" style={{gridColumn:'1/-1'}}><strong>Bike issues</strong><p>{ride.operations.issues.length} recorded</p></div></div>}
    {tool==='dayAudit'&&<DayAudit ride={ride} dayIndex={dayIndex}/>} 
  </Modal>}

function Tile({l,v}:{l:string;v:string}){return <div className="tile"><label>{l}</label><b>{v}</b></div>}
function Checklist({group,ride}:{group:'packing'|'content'|'backup';ride:Ride}){const store=useRiderHub();const labels:Record<string,string>=group==='packing'?{rain:'Rain gear + waterproof bags',firstaid:'First-aid + ORS',puncture:'Puncture kit + inflator',tools:'Basic tools',power:'Power + charging',documents:'DL / RC / insurance / PUC',water:'Water + snacks',socks:'Dry socks / walking shoes'}:group==='content'?{departure:'Departure shot',mangarh:'Mangarh',chacha:'Chacha Kota',mahi:'Mahi Dam',singhpura:'Singhpura Falls',jagmer:'Jagmer',arthuna:'Arthuna',arrival:'Arrival'}:{action5:'Action 5 footage copied',phone:'Phone media backed up',photos:'Favourite photos selected',booking:'Booking saved offline'};return <div className="checkList">{Object.entries(labels).map(([k,l])=><div className="checkRow" key={k}><strong>{l}</strong><button className={ride.operations[group][k]?'on':''} onClick={()=>store.toggleChecklist(ride.id,group,k)}>✓</button></div>)}</div>}
function Tomorrow({ride,dayIndex}:{ride:Ride;dayIndex:number}){const n=ride.days[dayIndex+1];return n?<div>{n.tasks.slice(0,5).map(x=><div className="routeCard" key={x.id}><strong>{x.time} · {x.title}</strong><p>{x.desc}</p></div>)}</div>:<div className="alert">This is the final ride day.</div>}
function DayAudit({ride,dayIndex}:{ride:Ride;dayIndex:number}){const store=useRiderHub();const d=ride.days[dayIndex],pending=d.tasks.filter(t=>!['done','skipped'].includes(taskStatus(ride,t)));return <div>{pending.length?pending.map(t=><div className="routeCard" key={t.id}><strong>{t.time} · {t.title}</strong><p>{t.desc}</p><div className="grid2"><button className="confirm" onClick={()=>store.setTask(ride.id,dayIndex,t.id,'done')}>Done now</button><button className="secondary" onClick={()=>store.setTask(ride.id,dayIndex,t.id,'skipped')}>Did not do</button></div></div>):<div className="alert">Everything for this day is already accounted for.</div>}</div>}
function shareLocation(){if(!navigator.geolocation)return alert('Geolocation unavailable');navigator.geolocation.getCurrentPosition(async p=>{const url=`https://maps.google.com/?q=${p.coords.latitude},${p.coords.longitude}`;try{if(navigator.share)await navigator.share({title:'My Rider Hub location',url});else{await navigator.clipboard.writeText(url);alert('Location link copied')}}catch{}},e=>alert(e.code===1?'Location permission denied. Enable location for this site and retry.':'Location unavailable. Check GPS/network.'),{enableHighAccuracy:true,timeout:12000,maximumAge:15000})}
